### ISSUE TITLE
Curly braces in bash variables

### ISSUE THREAD

**Issue by takaomag** [coreos/fleet#1045]
Hi,

It seems fleet does not understand curly braces in bash(sh) variable.
(though normal systemd can understand such unit file)
- Example unit file (test.service)

```
[Unit]
Description=test

[Service]
Type=simple
ExecStart=/usr/bin/bash -ec '\
VAL="test";\
while true; do\
    echo "This is ${VAL}.";\
    echo "This is $VAL.";\
    sleep 3;\
done;'
```
- Output of "fleetctl start test.service"

```
Dec 01 09:37:21 localhost bash[2146]: This is .
Dec 01 09:37:21 localhost bash[2146]: This is test.
Dec 01 09:37:24 localhost bash[2146]: This is .
Dec 01 09:37:24 localhost bash[2146]: This is test.
Dec 01 09:37:27 localhost bash[2146]: This is .
Dec 01 09:37:27 localhost bash[2146]: This is test.
```

Yes, we can avoid it by removing curly braces.
But I feel this is a kind of pitfall for every users.

fleet version: 0.8.3

**Comment by msumme** [comment]
I'm running into this with a script that needs curly braces for string manipulation in bash.  I'm using this for local settings detection - so that other services can know where the development database is located (in production we'd use something outside of docker/fleet).

The issue is that my conditional ( ` if [ "${e_var:0:6}" = "MYSQL_" ]` ) always fails because of the braces.  Is there a way to escape curly braces in Systemd unit files?

File below

```
ExecStart=/bin/bash -c '\
    while true; do \
    ip_address=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" database ); \
    running=$(docker ps | grep "database" | wc -l); \
    if [ $running -gt 0 ]; then \
        env_vars=$(docker inspect -f "{{ range .Config.Env }}{{ . }} {{ end }}" database); \
        echo $env_vars; \
        for e_var in $env_vars; do \
        	echo $e_var; \
            if [ "${e_var:0:6}" = "MYSQL_" ];then \
                var="${e_var:6}"; \
                setting_name=$(echo ${var%=*}|awk "{ print tolower(\$0) }"); \
                setting=${var#*=}; \
                echo "$setting_name $setting"; \
                etcdctl set /database/$setting_name $setting --ttl 30; \
            fi; \
        done; \
        etcdctl set /database/port 3306 --ttl 30; \
        etcdctl set /database/host $ip_address --ttl 30; \
    else \
        etcdctl rmdir /database; \
    fi; \
    sleep 20; \
    done'
```

Anybody know a workaround?

**Comment by msumme** [comment]
Ah - in case anyone else runs into this, using a "$$" works - it escapes the "$" so that systemd doesn't try variable expansion ( i.e. `$${e_var}` )
