### ISSUE TITLE
Auto-scaling services according to etcd key

### ISSUE THREAD

**Issue by yaronr** [coreos/fleet#1060]
Hi

Yes, it's another one of my crazy ideas, but. :)
Wouldn't it be great if there was a way to run a service in fleet, leaving the specification of 'how many' to run - to something external, like an etcd key.

For example:
fleetctl start kuku@{scale/kukus}.service

Then, you could control how many kukus are running, by setting the etcd key 'scale/kukus'. Setting either manually, or by some sort of process. Like - for example - a process that monitors the load on kuku, or latency.

This could be very very useful for scaling up or down services, and - in turn - clusters.

**Comment by bcwaldon** [comment]
Given the direction of #1055, I believe it is safe to say that fleet itself will not support this.
