### ISSUE TITLE
ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input

### ISSUE THREAD

**Issue by fishyumiao** [coreos/fleet#1083]
I have a machine with CoreOS 550.0.0,

This is my cloud-config.yml file:
#cloud-config

hostname: etcd
coreos:
  fleet:
    etcd_servers: http://127.0.0.1:4001
    metadata: role=etcd
  etcd:
    name: etcd
    addr: 192.168.1.162:4001
    bind-addr: 0.0.0.0
    peer-addr: 192.168.1.162:7001
    cluster-active-size: 1
    snapshot: true
  units:
    - name: static.network
      command: start
      content: |
        [Match]
        Name=eno16777736
        [Network]
        Address=192.168.1.162/24
        DNS=192.168.1.1
        Gateway=192.168.1.1
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
  update:
    group: alpha
    reboot-strategy: etcd-lock

The etcd runs fine. But there are some error logs in fleet journal, is there something wrong:

Jan 06 10:19:24 etcd systemd[1]: Started fleet daemon.
Jan 06 10:19:24 etcd fleetd[904]: INFO fleet.go:58: Starting fleetd version 0.9.0
Jan 06 10:19:24 etcd fleetd[904]: INFO fleet.go:162: No provided or default config file found - proceeding without
Jan 06 10:19:24 etcd fleetd[904]: INFO server.go:153: Establishing etcd connectivity
Jan 06 10:19:24 etcd fleetd[904]: INFO server.go:164: Starting server components
Jan 06 10:19:24 etcd fleetd[904]: INFO engine.go:186: Engine leadership acquired
Jan 06 10:24:24 etcd fleetd[904]: INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: unexpected EOF
Jan 06 10:24:24 etcd fleetd[904]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jan 06 10:24:24 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:29:24 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:29:24 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:34:25 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:34:25 etcd fleetd[904]: INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: unexpected EOF
Jan 06 10:34:25 etcd fleetd[904]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jan 06 10:39:25 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:39:26 etcd fleetd[904]: INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: unexpected EOF
Jan 06 10:39:26 etcd fleetd[904]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jan 06 10:44:25 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:44:26 etcd fleetd[904]: INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: unexpected EOF
Jan 06 10:44:26 etcd fleetd[904]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jan 06 10:49:25 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:49:26 etcd fleetd[904]: INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: unexpected EOF
Jan 06 10:49:26 etcd fleetd[904]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jan 06 10:54:25 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:54:26 etcd fleetd[904]: INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: unexpected EOF
Jan 06 10:54:26 etcd fleetd[904]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jan 06 10:57:39 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jan 06 10:59:25 etcd fleetd[904]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input

There was no folder named "job" in etcd:
abcuser@etcd ~ $ etcdctl ls /_coreos.com --recursive
/_coreos.com/fleet
/_coreos.com/fleet/engine
/_coreos.com/fleet/engine/version
/_coreos.com/fleet/lease
/_coreos.com/fleet/lease/engine-leader
/_coreos.com/fleet/machines
/_coreos.com/fleet/machines/fc6c66ffdb204fae862c203519e9cca3
/_coreos.com/fleet/machines/fc6c66ffdb204fae862c203519e9cca3/object

When a submit a service with fleet, the error logs no long appeared!

**Comment by fishyumiao** [comment]
It's mentioned at #3216
https://github.com/GoogleCloudPlatform/kubernetes/issues/3216

**Comment by jonboulle** [comment]
Please see #888 - thanks.
