### ISSUE TITLE
why restart all service when restart fleetd process?

### ISSUE THREAD

**Issue by holmes86** [coreos/fleet#1086]
Hi, I found all service be restarted in fleet when i use "systemctl restart fleet". 

 fleetctl status hello.service
hello.service - Hello World
   Loaded: loaded (/run/fleet/units/hello.service; linked-runtime)
   Active: active (running) since Fri 2015-01-09 16:06:34 CST; 9s ago
 Main PID: 39760 (bash)
   CGroup: /system.slice/hello.service
           ├─39760 /bin/bash -c while true; do echo "Hello, world"; sleep 1; done
           └─39793 sleep 1

systemctl restart fleet
fleetctl status hello.service
hello.service - Hello World
   Loaded: loaded (/run/fleet/units/hello.service; linked-runtime)
   Active: active (running) since Fri 2015-01-09 16:08:42 CST; 1s ago
 Main PID: 40234 (bash)
   CGroup: /system.slice/hello.service
           ├─40234 /bin/bash -c while true; do echo "Hello, world"; sleep 1; done
           └─40251 sleep 1

I think fleet should not restart all services. because I only want to restart fleet process.

Thanks
Best Regards.

**Comment by jonboulle** [comment]
Right now this is by design because we don't distinguish between fleet shutting down permanently or temporarily, and so we gracefully stop all units that it is controlling

What are you trying to achieve by restarting the fleet process?

**Comment by bcwaldon** [comment]
To add to this, you can send the SIGKILl signal to shut down the fleetd process without first unscheduling all locally-scheduled units. This simulates a catastrophic machine failure.

**Comment by holmes86** [comment]
@jonboulle thanks for you relay. In my opinion, fleet is a management program.  When  the program is  starting or stoping , it should not affect the management unit.  For example, we use the fleet to manage  many docker containers.  But once the fleet is restarted, it will lead to the restart action of  all  containers .  I think it is a big risk for production environment.

**Comment by jonboulle** [comment]
@holmes86 To tug on this thread a little further: how should fleet distinguish between when the machine is being shut down (and hence all units under its control should be terminated), and between a temporary restart when the units should not be interrupted?

More pertinently, I am really curious to know why you are restarting the fleet daemon in production environments - is there a problem you're experiencing?

**Comment by holmes86** [comment]
@jonboulle For production environment, whatever machine is being shut down or fleet temporary  restart. We can know fleet is not working through by monitor system.Before I modify fleet.conf config options, but I can't reload there config options. So I just restart fleet process.Then it made me got this idea.
Thanks

**Comment by jonboulle** [comment]
@holmes86 fleet already has the ability to reload its configuration without restarting completely: just send it a `SIGHUP` and it will re-read the configuration file. Can you give that a try instead? :-)

**Comment by holmes86** [comment]
OK. thank you jonboulle

**Comment by sukrit007** [comment]
My fleet service restarted automatically as it was unable to talk to etcd . But it caused all app containers to restart which was totally undesirable.
