### ISSUE TITLE
fleetctl list-machines returns error on one node in Vagrant cluster

### ISSUE THREAD

**Issue by tleyden** [coreos/fleet#1087]
I'm running coreos stable 494.4.0 (slightly out of date) under Vagrant, and all the sudden I'm getting this error after running `vagrant halt && vagrant up`.  It started happening shortly after I saw https://github.com/coreos/etcd/issues/2063, though I don't know if they are related.

Here is the vagrant output when I boot up:

https://gist.github.com/tleyden/a9bd816876f55440b40e

When I ssh into core-02 and core-03, `fleetctl list-machines` and `systemctl status etcd` both look fine:

* [core-02 output](https://gist.github.com/tleyden/db8c6f7c3df662a8f4c3)
* [core-03 output](https://gist.github.com/tleyden/963a9c39afb5f87a650c)

But core-01 has a problem when I run `fleetctl list-machines`:

```
2015/01/10 23:16:01 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: too many redirects
```

* [Full core-01 output](https://gist.github.com/tleyden/3a72c56a7db896bd496f)  (in particular, note the line where [etcd stops](https://gist.github.com/tleyden/3a72c56a7db896bd496f#file-gistfile1-txt-L31))

Not sure if this is relevant, but if I manually look into etcd from core-01, I can see three unique machine ids:

```
core@core-01 ~ $ etcdctl ls /_coreos.com/fleet/machines
/_coreos.com/fleet/machines/0f26e50a64dd4941b622e7f0bdc82929
/_coreos.com/fleet/machines/900b519c8e6548778b4cf7dff16ab7b4
/_coreos.com/fleet/machines/b43a0698c2374a659bfcec4e12722d7a
```

So far it's been 100% reproducible, I've ran `vagrant halt && vagrant up` several times, and each time have gotten the same issue.

Should I upgrade to a later coreos version and retry?  Or is it worth debugging?

**Comment by jonboulle** [comment]
@tleyden would you mind filing this as a bug against [etcd](https://github.com/coreos/etcd/issues/new) to continue debugging there, since this isn't really an issue with fleet proper? Thanks!

**Comment by tleyden** [comment]
Done - https://github.com/coreos/etcd/issues/2070

**Comment by jonboulle** [comment]
Thanks!
