### ISSUE TITLE
Discovery service failed to start even it is started after main service

### ISSUE THREAD

**Issue by phuongnd08** [coreos/fleet#1088]
So I have main service loaded and started. Then I load and start the discovery service. The discovery service look like this:

```
[Unit]
Description=Web server %i etcd registration
Requires=etcd.service
Requires=web@%i.service
After=etcd.service
After=web@%i.service
BindsTo=web@%i.service

[Service]
Restart=always
RestartSec=10s
User=core
EnvironmentFile=/etc/environment
ExecStart=/bin/bash -c '   while true; do      [ $(curl -s -o /dev/null -w \'%{http_code}\' "http://${COREOS_PRIVATE_IPV4}:$((3000 + %i))") == 301 ];      if [ $? -eq 0 ]; then        etcdctl set /services/web/%i "{host: \'%H\', ipv4_addr: \'${COREOS_PRIVATE_IPV4}\', thin_port: \'$((3000 + %i))\', nginx_port: \'$((80 + %i))\'}" --ttl 15;      else        etcdctl rm /services/web/%i;      fi;      sleep 10;    done'
ExecStop=/usr/bin/etcdctl rm /services/web/%i

[X-Fleet]
X-ConditionMachineOf=web@%i.service
```

Basically the discovery service keep checking until a http request on port 3001 return status 301.
Occasionally, I see this error in `systemctl status web-discovery@1.service`

```
systemd[1]: Stopped Web server 1 etcd registration.
systemd[1]: Stopped Web server 1 etcd registration.
systemd[1]: Dependency failed for Web server 1 etcd registration. 
```

It's confusing because the `web-discovery@.service` is told to always restart, but it not started, but failed due to dependency. Though at the moment I check and `web@1.service` being active.

**Comment by bcwaldon** [comment]
Does the `Dependency failed` line correspond to any logs in `systemctl status web@1.service` of `etcd.service`? systemd is clearly stopping it, likely due to the `BindsTo` option you have defined. When it tries to restart, one of the `Requires` might be unfulfillable.
