### ISSUE TITLE
"fleetctl start unit" can not work  when unit was crash or killed -9

### ISSUE THREAD

**Issue by holmes86** [coreos/fleet#1091]
I did the following attemption:
$ fleetctl list-units
UNIT		MACHINE			ACTIVE	SUB
hello.service	d16f9669.../10.0.33.214	active	running
$ fleetctl status hello.service
hello.service - Hello World
   Loaded: loaded (/run/fleet/units/hello.service; linked-runtime)
   Active: active (running) since Thu 2015-01-15 20:52:04 CST; 1h 16min ago
 Main PID: 14128 (bash)
   CGroup: /system.slice/hello.service
           ├─14128 /bin/bash -c while true; do echo "Hello, world"; sleep 1; done
           └─20307 sleep 1

$ sudo kill -9 14128
$ fleetctl list-units
UNIT		MACHINE			ACTIVE	SUB
hello.service	d16f9669.../10.0.33.214	failed	failed
$ fleetctl list-unit-files
UNIT		HASH	DSTATE		STATE		TARGET
hello.service	e55c0ae	launched	launched	d16f9669.../10.0.33.214
$ fleetctl start hello.service
$ fleetctl list-units
UNIT		MACHINE			ACTIVE	SUB
hello.service	d16f9669.../10.0.33.214	failed	failed

I found  the unit file status is still launched. So "fleetctl start hello.service" is not working.
$ fleetctl list-unit-files
UNIT		HASH	DSTATE		STATE		TARGET
hello.service	e55c0ae	launched	launched	d16f9669.../10.0.33.214

If I use "fleetctl stop hello.service" first, then "fleetctl start hello.service" is  working.  Is this fleet policy or bug? thanks.

**Comment by bcwaldon** [comment]
@holmes86 most of the fleetctl commands (load, start, stop, unload) are declarative, not imperative. When you run `fleetctl start foo.service`, you're instructing the cluster that the unit `foo.service` should transition to the "launched" state: this transition requires the unit be scheduled somewhere and started. Once the transition happens, subsequent calls to `fleetctl start foo.service` will have no effect.

We've discussed the confusing naming here: https://github.com/coreos/fleet/issues/1025

**Comment by holmes86** [comment]
@bcwaldon I mean fleet change ACTIVE and SUB status when unit was exception. why not change unit DSTATE or STATE?

**Comment by bcwaldon** [comment]
`DSTATE` is set by the user, not in reaction to any events in the cluster. `STATE` is a concept defined independently of the states exposed by any given instance of systemd [0], so it is not logical for that field to change in response to a systemd-level event. The `ACTIVE` and `SUB` fields are populated by systemd, not by fleet, so they change based on what's happening in the actual instance of systemd running your unit.

[0] https://github.com/coreos/fleet/blob/master/Documentation/states.md
