### ISSUE TITLE
Docker pull not working for private registry when run from fleet

### ISSUE THREAD

**Issue by sukrit007** [coreos/fleet#1094]
**Given**: Core OS cluster: v 550 (alpha)
```
cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=550.0.0
VERSION_ID=550.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 550.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**And**:  .dockercfg file present in /home/core directory  and /root directory.
```
cat /home/core/.dockercfg
{
  "https://quay.io/v1/": {
    "auth": "<<PASTE YOUR VALID KEY>>",
    "email": ""
  }
}
```

**And** : Docker pull works from command line on core os server for private repo
```
docker pull quay.io/<private org>/<private repo>
..... Status: Downloaded newer image for quay.io/........
```

**When**: I run a unit from fleet with StartPre as
```
ExecStartPre=/bin/bash -xc "docker pull quay.io/<private org>/<private repo>"
```

**Then**: Docker pull fails with error 403
```
time="2015-01-18T01:53:18Z" level="fatal" msg="HTTP code: 403"
```

**Workaround**: 
It looks like issue is caused because env variable HOME is empty when command is run through fleet. As as result docker pull does not find .dockercfg . Explicitly setting HOME path to /home/core  provides a workaround for this issue.

```
ExecStartPre=/bin/bash -xc "env HOME=/home/core docker pull quay.io/<private org>/<private repo>"
```
Ideally I would expect fleetd/systemd to set the HOME path prior to scheduling the unit.

**Comment by jonboulle** [comment]
@sukrit007 per https://coreos.com/docs/launching-containers/building/registry-authentication , you should just need to set `User=core` in the systemd unit file. Let us know if that doesn't fix your issue.
