### ISSUE TITLE
Fleet: Why Global and Conflicts should not be combined ?

### ISSUE THREAD

**Issue by yskrishnan** [coreos/fleet#1102]
I have a usecase where I want to run Global unit services A in first 5 nodes, and service B in remaining (n - 5) nodes. Now how can I specify this in Fleet conditions ?
For A I gave
[X-Fleet]
Global=true
MachineMetadata=ip1
MachineMetadata=ip2
MachineMetadata=ip3

For B
[X-Fleet]
Global=true
Conflicts=A   // But why this is not accepted ?

For this to work, either I should be able to specify Conflicts along with Global, or is there any way I can specify negative condition using MachineMetadata, like 
MachineMetadata=public_ip != ip1

**Comment by bcwaldon** [comment]
There's no reason other than it hasn't been implemented. Filed a feature ticket here: https://github.com/coreos/fleet/issues/1109
