### ISSUE TITLE
fleet not start container unit after docker stop

### ISSUE THREAD

**Issue by huikang** [coreos/fleet#1103]
Hi,
I have a unit file that defines a container as 

execstart=docker run --name apache ....

I used fleetctl submit/start apache.test to a physical host. If I reboot the host, fleet will automatically recover the container in a different physical machine. However, if I use "docker stop" to kill the container, fleet does not perform the automatic rescheduling and fleetctl list-units show as a failed state.

How can I let fleet to move the container after "docker stop"? Thanks.

- Hui

**Comment by jonboulle** [comment]
fleet only reschedules in the case of machine failure. At the system level,
restarts are handled by systemd; for example, a "Restart=always" directive
in the unit file means that systemd will restart it when it fails.

Alternatively if you stop the fleet service on a machine, that will cause
it to reschedule the unit elsewhere.

**Comment by huikang** [comment]
Hi, Jonathan,
Thanks for your response.

There are other container units on the host. As I only want to stop and
move one unit by fleet, so stopping the fleet service may not be a good
solution.

I will try adding "Restart=always" in the unit file. Thanks.

- Hui

**Comment by bcwaldon** [comment]
Let us know if this didn't address the issue.

**Comment by huikang** [comment]
Hi, Brian and Jonathan,
Adding "Restart=always" solves the problem for the container unit. However,
the sidekick process can not be restarted.

My sidekick unit file is like this

Description=RabbitMQ monitoring and etcd registration


Requires=etcd.service
Requires=main-service@%i.service

# Dependency ordering and binding
After=etcd.service
After=main-service@%i.service
BindsTo=main-service@%i.service

[Service]
EnvironmentFile=/etc/environment

Adding  "Restart=always"to the sidekick file does not solve the problem of
restarting sidekick process.

- Hui

**Comment by bcwaldon** [comment]
When your `BindsTo` option is triggered, the `Restart=always` is going to be ignored. You could just drop `BindsTo`

**Comment by huikang** [comment]
Hi, Brian,
Thanks. This solves the problem.

- Hui
