### ISSUE TITLE
I lost SSH to one of the server. Though fleetctl list-machines still show it as a part of the cluster

### ISSUE THREAD

**Issue by phuongnd08** [coreos/fleet#1105]
Could I potentially gain access to it again.

**Comment by bcwaldon** [comment]
What do you mean "lost SSH to one of the server[s]"? fleet has nothing to do with hosting SSH, so maybe you need to look into your IaaS provider?

**Comment by phuongnd08** [comment]
Right, I recover my access by contacting support. What I was asking is that in case ssh access is accidentally blocked on a machine, can fleet continue to distribute services over it?

**Comment by bcwaldon** [comment]
@phuongnd08 Yes - the fleet daemons only depend on etcd being available. You won't be able to use fleetctl commands that depend on SSH, but fleet will continue to operate.

**Comment by phuongnd08** [comment]
Thanks. Last question: Which fleetctl commands depend on SSH? Like `load/start`?

**Comment by bcwaldon** [comment]
If you use the --tunnel flag, all requests will be tunneled over SSH to the cluster. Without --tunnel, the only commands that use SSH are status, journal, and ssh.
