### ISSUE TITLE
Support Conflicts when Global=true

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#1109]
When `Global=true` is set in the `[X-Fleet]` section, the only additional option applied is `MachineMetadata`. The `Conflicts` option should also be supported such that a machine must pass both the `MachineMetadata` and `Conflicts` filters in order to run a given unit. If `MachineMetadata` is not set but `Conflicts` is, only the `Conflicts` option must be checked.

**Comment by JeanMertz** [comment]
:+1: for this one.

Use case:

Using [Consul](https://consul.io), I want to start the Consul agent in "server" mode on the first three instances, and the rest should fill up with non-server agents.

**Comment by xied75** [comment]
:+1:

@JeanMertz and your use case is exactly what I want. :)
