### ISSUE TITLE
container moved to another host, but can not get the new IP

### ISSUE THREAD

**Issue by huikang** [coreos/fleet#1111]
Hi,
In my fleet unit file, I created a container and pass the COREOS_PUBLIC_IPV4 as a docker environment variable to the container, like this
               EnvironmentFile=/etc/environment
               docker run    -h service-%i      \
                                    --name service-%i               \
                                    -e HOST_IP=$COREOS_PUBLIC_IPV4        \
                                    command
Such that the script in the container can use the host IP to do some configuration. For exmple, the instance 01 is created on host IP 172.16.1.101.

However, after I reboot the 172.17.1.101 host and the container moved to another host (172.17.1.102), I found that the container environment variable still uses the old IP (101), instead of the new one (172.17.1.102).

I further stop and destroy the instance, and the restart the instance on the new host. It stills use the old IP. 
Could anyone help on the problem? Thanks.

- Hui

**Comment by bcwaldon** [comment]
Can you tell us a bit more about how you're deploying your cluster? What tools are you using? How many nodes? What are the contents of /etc/environment on each node? What version of CoreOS is this?

**Comment by huikang** [comment]
Hi, Brian,
First, I found that only after I destroy all instances (from the same
template file) and the template file, the instance is able to get the IP of
the new host.

In my testbed, I have 3 nodes and coreos stable channel. There is no other
special tool I am using.


Output of uname:
Linux core-05 3.17.8+ #2 SMP Fri Jan 9 23:58:08 UTC 2015 x86_64 Intel(R)
Xeon(R) CPU E5649 @ 2.53GHz GenuineIntel GNU/Linux

Thanks.

- Hui

**Comment by bcwaldon** [comment]
How are you installing CoreOS? Are these baremetal nodes? What are the contents of /etc/environment on each of the three nodes?

**Comment by huikang** [comment]
I used vagrant to install coreos on my virtualbox environment.

core@core-01 ~ $ cat /etc/environment
COREOS_PUBLIC_IPV4=172.168.1.101
COREOS_PRIVATE_IPV4=172.168.1.101

core@core-02 ~ $ cat /etc/environment
COREOS_PUBLIC_IPV4=172.168.1.102
COREOS_PRIVATE_IPV4=172.168.1.102

**Comment by bcwaldon** [comment]
Ok, so this isn't adding up. Your environment file is clearly set up properly. Did you have two instances of the same unit running on both core-01 and core-02? What makes you believe that something went wrong here?

**Comment by huikang** [comment]
Both instances are linked to the same template file, i.e., main@.service.
Then
I created fleetctl start instance@001.service, instance@002.service

In the unit file, I used execstart=docker kill and rm to remove any
existing containers. So I think there are no same instance on the host.

- Hui

**Comment by huikang** [comment]
Hi, Brian,
Could you help to clarify one thing about how fleet starts a container?

In my container unit file, I have

EnvironmentFile=/etc/environment

docker run -h service-%i \
                  --name service-%i  \
                  -e HOST_IP=$COREOS_PUBLIC_IPV4 \

On failure, when the container is started from a new host, will
enviromentfile will be read again? If not, I suspect that the new container
will still use the old value of $COREOS_PUBLIC_IPV4 on the old host. Any
comment? Thanks.

- Hui

**Comment by bcwaldon** [comment]
The environment is read and applied whenever ExecStart is executed.

**Comment by huikang** [comment]
Maybe I should try a differetn version of coreos or fleet.

I am currently using the stable channel for vagrant. Which version will you
recommend I try?

- Hui

**Comment by bcwaldon** [comment]
The version of CoreOS should be fine. Feel free to try out the alpha and beta channels, but I suspect there is an issue with your local environment.

**Comment by huikang** [comment]
I will try a different container unit file and let you know. Thanks.

- Hui
