### ISSUE TITLE
API docs don't mention the fact that there needs to be a v1-alpha in the URL

### ISSUE THREAD

**Issue by tleyden** [coreos/fleet#1115]
I followed [these instructions](https://github.com/coreos/fleet/blob/7b516b06c4e04c95cb5c5fc741776fc9057d23e9/Documentation/deployment-and-configuration.md#api) on getting fleet to listen on port 49153 for REST api calls.

Initially I tried:

```
curl localhost:49153/machines
```

which returned a 404.  After some trial and error and googling, I managed to figure it out:

```
curl localhost:49153/v1-alpha/machines
```

which returned valid JSON.

I think the docs should be updated to mention that all REST api calls should be prefixed with **/v1-alpha/**

I'm on CoreOS (stable) 522.6.0.

**Comment by robszumski** [comment]
The docs are tracking 0.9, which is the release where the API was finalized. The current stable channel hasn't been updated with this version, which is why you're seeing `/v1-alpha/` work. Sorry for the confusion.

You can find the release notes for CoreOS here: https://coreos.com/releases/

**Comment by bcwaldon** [comment]
@tleyden are you asking for a blurb be added to that doc telling a user where the API will be hosted once the socket is deployed?

**Comment by tleyden** [comment]
> The current stable channel hasn't been updated with this version, which is why you're seeing /v1-alpha/ work

Ah ok.  So on 0.9, you would simply use `curl localhost:49153/machines`?

**Comment by tleyden** [comment]
> are you asking for a blurb be added to that doc telling a user where the API will be hosted once the socket is deployed?

I was just confused about the endpoint URL's, which I think @robszumski cleared up.

**Comment by bcwaldon** [comment]
@tleyden I don't think he did. The API lives at `$IP:$PORT/fleet/v1/...` as of v0.9, with backwards compatibility for the `.../v1-alpha/...` path that we started with. `.../machines` is not hosted at the root resource in pre-v0.9 or v0.9+

**Comment by tleyden** [comment]
Ah ok.  Yeah I think the docs should be enhanced to mention that the endpoint URL's should be of the form `$IP:$PORT/fleet/v1/...` as of v0.9.

**Comment by bcwaldon** [comment]
@tleyden See https://github.com/coreos/fleet/pull/1116

**Comment by tleyden** [comment]
Thanks
