### ISSUE TITLE
Upload unit file with Fleet API

### ISSUE THREAD

**Issue by tleyden** [coreos/fleet#1117]
Is there any way to upload a unit file to Fleet via a multipart/form-data POST request?

The reason I'm asking: I currently keep my fleet files in github, and they are easy to view and edit.  From my understanding of [uploading a unit via the fleet api](https://github.com/coreos/fleet/blob/master/Documentation/api-v1.md#request), I'd have to convert this to JSON first, which seems a bit painful to maintain.  (I guess things like escaping double quotes and so forth seems a bit daunting)

What's the recommended approach here?

**Comment by tleyden** [comment]
After looking over it a bit closer, it doesn't look that bad.  It turns out the only double-quotes I had in my fleet file didn't need to be there anyway.

I did notice one problem though.  In my fleet script:

```
...
ExecStartPre=-/usr/bin/docker rm couchbase
ExecStartPre=/usr/bin/docker pull tleyden5iwx/couchbase-server-3.0.1
...
```

The first ExecStartPre command is allowed to fail, while the second one is not.  How would I express this in the JSON?

**Comment by tleyden** [comment]
Answering my own question, I think it would be this:

```
        {
            "section":"Service",
            "name":"ExecStartPre",
            "value":"-/usr/bin/docker rm couchbase"
        },
        {
            "section":"Service",
            "name":"ExecStartPre",
            "value":"/usr/bin/docker pull tleyden5iwx/couchbase-server-3.0.1"
        },
```

Haven't confirmed it works yet.

**Comment by bcwaldon** [comment]
@tleyden yes, that looks correct. fleet uses github.com/coreos/go-systemd/unit for unit (de)serialization, which you could also use in your code.

**Comment by tleyden** [comment]
Everything is pretty much working, so I'm closing the ticket.
