### ISSUE TITLE
Kicking off unit files with @ unit templates via fleet api

### ISSUE THREAD

**Issue by tleyden** [coreos/fleet#1118]
I'm on fleet version 0.8.3, and I'm trying to do the following via the REST api:

```
PUT /units/foo@.service HTTP/1.1

{
  "desiredState": "inactive",
  "options": [{"section": "Service", "name": "ExecStart", "value": "/usr/bin/sleep 3000"}]
}
```

This creates the "unit template".  After doing this, I can launch it on the command line via `fleetctl start foo@1.service`

However, it's not working if I try to launch it via the fleet REST api.

```
PUT /units/foo@1.service HTTP/1.1

{
  "desiredState": "launched"
}
```

I'm getting: `{"error":{"code":409,"message":"unit does not exist and options field empty"}}`

Do I need to be on a more recent version of fleet?  Or is this the wrong approach?

**Comment by bcwaldon** [comment]
@tleyden fleet does not manage pure template unit files, so you should never create a `foo@.service`. Do the following:

```
PUT /units/foo@1.service HTTP/1.1

{
  "desiredState": "launched",
  "options": [{"section": "Service", "name": "ExecStart", "value": "/usr/bin/sleep 3000"}]
}
```

The fleetctl client is doing a little magic for you and looking at the unit templates available locally before creating a `foo@1.service`. 

We know the UX around instance units is not perfect in fleet, and we would appreciate any feedback you might have.

**Comment by bcwaldon** [comment]
https://github.com/coreos/fleet/issues/969

**Comment by tleyden** [comment]
OK that makes sense.  

To give a little more context: I am doing the initial fleet unit creation through an automated script, but afterwards I want to make it easy to manually stop/launch these fleet units via unit templates, which is why I wanted to take the unit template approach.

My current approach is that the automated scripts create :

```
PUT /units/foo@1.service HTTP/1.1

{
  "desiredState": "launched",
  "options": [{"section": "Service", "name": "ExecStart", "value": "/usr/bin/sleep 3000"}]
}
```

and

```
PUT /units/foo@.service HTTP/1.1

{
  "desiredState": "inactive",
  "options": [{"section": "Service", "name": "ExecStart", "value": "/usr/bin/sleep 3000"}]
}
```

so then I'm left with a system where I can easily launch new foo services by running `fleetctl start foo@11.service`, even though there wasn't an explicit foo@11.service unit created .. but the unit template will kick in.

**Comment by bcwaldon** [comment]
I may be wrong (I didn't go look at the code), but I believe fleetctl will use any available instance of `foo@.service` if you try to create a new instance.

**Comment by tleyden** [comment]
So you are saying the `PUT /units/foo@.service HTTP/1.1` is redundant?  I'll do some testing and let you know.

**Comment by bcwaldon** [comment]
I'm saying it's possible :)

**Comment by tleyden** [comment]
In my test that didn't seem to work.  Here's my console session output: https://gist.github.com/tleyden/04385bf074bb29c5a07b

**Comment by bcwaldon** [comment]
@tleyden ok, thanks for doing that. `fleetctl` will look on the local filesystem (and possibly in the cluster) for a template unit that corresponds to the instance you're trying to start.

**Comment by kayrus** [comment]
Have the same issue.

```
Feb 16 14:47:31 coreos3 fleetd[20310]: ERROR reconcile.go:80: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name servicename@.service is not valid.
```
Can not remove it. Is there a temporarily solution to remove invalid service?
