### ISSUE TITLE
AWS private IP and %H

### ISSUE THREAD

**Issue by strangemonad** [coreos/fleet#1120]
many of the docks around setting up a sidekick unit mention using %H when broadcasting to etcd. The hostname on ec2 instances will be a DNS name that resolves to the public ip.

It seems like best practice would be to targeting either the public or private ip directly (as exposed in /etc/environment) and bypass DNS in the ec2 environment.

**Comment by robszumski** [comment]
You can use the IP addresses recorded into `/etc/environment` if you'd like. In a unit file, include `EnvironmentFile=/etc/environment` and then reference `$COREOS_PRIVATE_IPV4` in your unit. You maybe need to wrap your commands in `/bin/sh -c ''` in order for the variable replacement to work.

You can see a full example of that here: https://github.com/coreos/unit-examples/blob/master/blog-vulcan-example/mixed-register-v1.0.0-A.service#L9

For anyone else that stumbles upon this issue, `/etc/environment` is only populated on systems that provide this information to CoreOS via a metadata service. Most cloud providers provide a metadata service and are compatible.
