### ISSUE TITLE
Start a unit based on a template via the REST API?

### ISSUE THREAD

**Issue by shadoi** [coreos/fleet#1129]
I can't currently see a way to do it given the schema.  If I try to start a unit with a name like `service-name@1.service` based on a unit template named `service-name@.service` I've already loaded it fails with: `{"error":{"code":409,"message":"unit does not exist and options field empty"}}`

If I start a template unit via the API it changes state to launched, but doesn't launch a unit (nothing shows up in `fleetctl list-units`

**Comment by bmorton** [comment]
I'm trying to do something similar, but ended up just doing a PUT for each instance and including the unit options every time.  The API calls succeed, but as I just posted in #1131, only 1 unit seems to come up cleanly and the others fail.  Not sure if I'm doing it the right way, but hopefully this issue or #1131 will get a response about the right way to do this.

**Comment by shadoi** [comment]
I looked at what fleetctl using the API does under the hood and it basically just matches the filename pattern and does multiple requests to get the template, and re-upload it for the new unit.  This is my workaround for now, but it does seem like a prime candidate to get put into the API server-side.

**Comment by bcwaldon** [comment]
Proper template unit support is something we have been playing around with for a while. If you have any ideas as to how fleet should accomplish this, we are more than happy to talk through potential designs.
