### ISSUE TITLE
failed unit should not be started when rescheduled

### ISSUE THREAD

**Issue by zyndiecate** [coreos/fleet#1135]
Hi there, we have currently >1000 units running on a cluster. Some are running, some are failed, some are restarting, all good. Having automatic coreos updates enabled, machines reboot from time to time, that is, units are rescheduled from time to time. Problem is that there are all units started again when rescheduled, even the failed ones. This causes a lot of unnecessary load on machines that desperately try to restart units that actually are not able to start. 

We now would need to implement something at [giantswarm](https://giantswarm.io/) to keep track of failed units, to actively stop them, so that they are not started after rescheduling. IMO the more proper solution would be to handle this in `fleet` itself, because this is where such a feature should belongs to. 

I would like to hear what you guys think about that, how it is supposed to be, and what we can do here.

**Comment by bcwaldon** [comment]
It seems like native support for oneshot units would actually be the right solution here. fleet assumes everything is a long-running service that should never fail. If it fails, it does rely on the builtin systemd unit restart policies, but when fleet migrates a long-running service, it *must* start it up again. See https://github.com/coreos/fleet/issues/562
