### ISSUE TITLE
fleetd[606]: ERROR event.go:107

### ISSUE THREAD

**Issue by hapnermw** [coreos/fleet#1139]
I'm running the ami-8297d4ea in an EC2 t2.medium instance. No containers have been loaded. This is a vanilla image. Nothing has been added/changed. No containers have been loaded. This is a single instance cluster.

The cloud-config is:

#cloud-config

coreos:
  etcd:
    name: coreos-1
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/4d258dea6c614f7cbb0f4774d9375091
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    metadata: instance=1,layer=1,function=1
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

The instance boots and appears to be operating well; however, fleet is logging the following error messages repeatedly.

Mar 05 23:14:26 ip-10-0-4-196.corp.resilient-networks.com fleetd[606]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON
Mar 05 23:14:12 ip-10-0-4-196.corp.resilient-networks.com fleetd[606]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON
Mar 05 23:13:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:13:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:12:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:12:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:11:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:11:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:10:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:10:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:09:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:09:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:09:26 ip-10-0-4-196.corp.resilient-networks.com fleetd[606]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON
Mar 05 23:09:11 ip-10-0-4-196.corp.resilient-networks.com fleetd[606]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON
Mar 05 23:08:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:08:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:08:04 ip-10-0-4-196.corp.resilient-networks.com etcd[605]: [etcd] Mar  5 23:08:04.085 INFO      | coreos-1: snapshot of 10004 events at index 210062 completed
Mar 05 23:07:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:07:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:06:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:06:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:05:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:05:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:04:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Started Generate /run/coreos/motd.
Mar 05 23:04:36 ip-10-0-4-196.corp.resilient-networks.com systemd[1]: Starting Generate /run/coreos/motd...
Mar 05 23:04:26 ip-10-0-4-196.corp.resilient-networks.com fleetd[606]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON
Mar 05 23:04:11 ip-10-0-4-196.corp.resilient-networks.com fleetd[606]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON

The etcd content of /_coreos.com/fleet is 

core@ip-10-0-4-196 ~ $ etcdctl ls /_coreos.com/fleet
/_coreos.com/fleet/machines
/_coreos.com/fleet/engine
/_coreos.com/fleet/lease

There is no /_coreos.com/fleet/job entry.

**Comment by hapnermw** [comment]
The copy/paste of cloud-config removed the yaml indention. It was processed correctly on boot. For instance the fleet metadata for the instance was correctly set.

core@ip-10-0-4-196 /run/systemd/system/fleet.service.d $ cat 20-cloudinit.conf 
[Service]
Environment="FLEET_METADATA=instance=1,layer=1,function=1"

core@ip-10-0-4-196 /run/coreos $ ls
motd  motd-failed
core@ip-10-0-4-196 ~ $ cat /run/coreos/motd
CoreOS stable (557.2.0)

**Comment by bcwaldon** [comment]
This is expected. etcd periodically closes watchers. See https://github.com/coreos/fleet/issues/888
