### ISSUE TITLE
BUG? etcdctl environment not loaded within unit files

### ISSUE THREAD

**Issue by popsikle** [coreos/fleet#1140]
If you have an off-host etcd cluster or server and have setup your system based on the documentation here : https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services and  you try to run etcdctl set xxx xxx inside of a unit file the system-wide peers configured are not used.

Example unit Commands:
```
[Service]
TimeoutStartSec=0

EnvironmentFile=/etc/environment
ExecStart=/bin/bash -c '\
  while true; do \
      etcdctl set /services/test/${COREOS_PRIVATE_IPV4} TEST --ttl 30; \
    sleep 20; \
  done'
```

This will set the key on the default etcd host of 127.0.0.1 and not your cluster.  You will need to source /etc/profile.d/etcdctl.sh in order to achieve the desired results.

**Comment by bcwaldon** [comment]
I don't quite understand. Are you saying that etcdctl is making requests against `127.0.0.1` and you expect otherwise, or that `/services/test/${COREOS_PRIVATE_IPV4}` is being rendered to `/services/test/127.0.0.1`?

**Comment by uschen** [comment]
@bcwaldon the first one `etcdctl is making requests against 127.0.0.1`

**Comment by paulcichonski** [comment]
I've run into this as well, and fixed by sourcing the `/etc/profile.d/etcdctl.sh` before running any other commands in the `ExecStart`.

For the above example it would be:

```
ExecStart=/bin/bash -c 'source /etc/profile.d/etcdctl.sh && \
  while true; do \
      etcdctl set /services/test/${COREOS_PRIVATE_IPV4} TEST --ttl 30; \
    sleep 20; \
  done'
```
Not sure if this is the most ideal solution.

**Comment by pebo** [comment]
The documentation at https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services only sets the ETCDCTL and FLEETCTL variables using profile.d. As far as I understand this works great when you ssh into the host but less so from unit files. Maybe the docs and example config for the production cluster could be updated to with a working example for units too?

Too avoid sourcing before each command in the unit one option is write the environment variables to an a file and the load it from the unit using [EnvironmentFile=] (http://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=). Here's an example of that setup: https://github.com/coreos/etcdctl/issues/115#issuecomment-73987286.

**Comment by visit1985** [comment]
@pebo :+1:

The one-shot service, which writes `/etc/environment` from `/etc/profile.d/*` should be added to coreos by default.

**Comment by wptad** [comment]
@pebo 

I have the same issue. And I fixed it by change the file owner from `core` to `root`


```
write_files:
  - path: /etc/profile.d/etcdctl.sh
    permissions: 0644
    owner: root
    content: |
      export ETCDCTL_PEERS="http://10.12.1.51:2379"

```

Wish it helps

**Comment by Dynom** [comment]
So, to clarify, this ticket is that `EnvironmentFile=/etc/environment` isn't actually making the defined variables available in Exec* statements in the unit-file, right?

In that case: I have a problem too, I either have to wrap several commands in a bash statement to make it work. An example that currently fails:

```
EnvironmentFile=/etc/environment
ExecStart=/usr/bin/docker run --name SomeService -p $COREOS_PRIVATE_IPV4:80:8080 some/image start
```

**Comment by scole-scea** [comment]
@Dynom: look at the systemd man pages (http://www.freedesktop.org/software/systemd/man/systemd.service.html), especially the "Command lines" section, which talks about how environment variables work. You want to add curly braces to yours, because it's not whitespace delimited.

**Comment by Dynom** [comment]
Thanks @scole-scea I was apparently looking at the problem in the wrong area (-: Oddly work around I find mostly is: ```ExecStart=/bin/sh -c ' source /etc/environment && ..'``` Which does the trick without the braces.

I'll update my command to add the safety bars!

**Comment by scole-scea** [comment]
Yeah, the variable substitution rules in systemd unit files are not the same as the rules for bash, so when you instead send your command as a command string to bash, it works.

**Comment by visit1985** [comment]
@Dynom, @scole-scea: This bug is about /etc/environment not defining COREOS_{PRIVATE,PUBLIC}_IPV4. At least that was the issue 3 months ago.

**Comment by bcwaldon** [comment]
If the /etc/envrionment file is not being populated, that is an OEM issue with CoreOS linux.

**Comment by bcwaldon** [comment]
And @scole-scea's point that systemd's substitution is different than bash's substitution is very important to understand. Something obviously has to implement the logic that renders ${COREOS_PUBLIC_IPV4} into 172.17.9.101, which is typically bash. If you aren't running under bash, you have to rely on something else to do it - in this case, systemd.
