### ISSUE TITLE
Unable to re-configure machine METADATA after initial config

### ISSUE THREAD

**Issue by imjacobclark** [coreos/fleet#1141]
I am attempting to modify a machines METADATA after initial cloud-init config, however, I am unable to do so.

My first attempt was to create a /fleet/fleet.config and change the METADATA within, I rebooted the machine, and saw no update.

```
metadata="node=coreos01,region=london-1,host=digitalocean"
```

I also attempted to copy the cloud-init file and supersede it within `/etc/systemd/system/ ` with the updated metadata, rebooted the machine, and saw no update.

I fail to find any reasonable level of documentation around this, my question being, is this bug, is there a better way to achieve this, or is this data immutable after initial configuration.

Please note, I am not looking to update this at runtime, the node being rebooted or fleet being killed is not an issue, I am simply looking to update the METADATA.

**Comment by blackwaterdevops** [comment]
Same issues here

**Comment by imjacobclark** [comment]
I resolved this by:

```shell
cp -R /run/systemd/system/fleet.service.d/ /etc/systemd/system/ 
vi /etc/systemd/system/fleet.service.d/*.conf # updating with new metadata
sudo reboot
```

Verifying my metadata had updated via: `systemctl status fleet`, ensuring the Drop-In is now `/etc/systemd/system/fleet.service.d/*.conf`.

Maybe this needs formally documenting, as this is probably a common issue people will encounter.

**Comment by ForbiddenEra** [comment]
+1

I agree, I had to do this once and it was a PITA. Documentation would be nice.

Actually, a command to update metadata would be even more awesome. You could do dynamic metadata this way maybe.

**Comment by bcwaldon** [comment]
It seems like there are a few fundamental misunderstandings here that need to be cleared up. Unit files in /var/run/systemd/system override those in /etc/systemd/system, which in turn override those in /usr/lib/systemd/system. You cannot add a unit to /etc/sytemd/system and expect it to have any effect if the unit is already defined in /var/run/systemd/sytstem. If you had just modified the existing units directly in /var/run/systemd/system, called `systemctl daemon-reload` and restarted `fleet.service`, the changes would have been applied.

Additionally, you should *not* make changes at runtime on top of whatever cloud-init is doing. If your machine reboots, your changes will be reverted as your cloud-config will be reapplied.

fleet's default config file is at `/etc/fleet/fleet.conf`, which you are free to modify, but I believe environment variables override whatever values are defined in that config. However, if you are able to use that config file, you can make changes then `systemctl kill --signal SIGHUP fleet` to force fleet to reload it.
