### ISSUE TITLE
Using fleetctl

### ISSUE THREAD

**Issue by terrylai** [coreos/fleet#1151]
Hello all, 

I am studying recently coreos and have a problem not able to solve:

Firstly, I learned by the tutorial in the following links:

https://coreos.com/docs/launching-containers/building/getting-started-with-docker/

and 

https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/

to study docker and fleet.

Docker is ok for me but when I used fleetctl I found the following problem:

I make a apache@.service file as the following:

[Unit]
Description=My Apache Frontend
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill apache1
ExecStartPre=-/usr/bin/docker rm apache1
ExecStartPre=/usr/bin/docker pull terrylai/apache
ExecStart=/usr/bin/docker run --rm --name apache1 -p 80:80 terrylai/apache /usr/sbin/apache2ctl -D FOREGROUND
ExecStop=/usr/bin/docker stop apache1

[X-Fleet]
Conflicts=apache@*.service

Then I run the following:

$ fleetctl submit apache@.service

$ fleetctl start apache@1
Unit apache@1.service launched on 4b736769.../172.16.69.176

$ fleetctl start apache@2

Here I waited a long time and then press ctrl-break

Then

$ fleetctl list-unit-files
UNIT			HASH	DSTATE		STATE		TARGET
apache@1.service	a84e786	launched	launched	4b736769.../172.16.69.176
apache@2.service	a84e786	launched	inactive	-

And I found the IP shown is my host IP (172.16.69.176), not guest IP.

Could anyone teach me how to do so that I can run 2 instances simultaneously?

Thanks!

BR,
Terry

**Comment by jonboulle** [comment]
It looks like you're using a single machine cluster, but you have this
option which means at most one will be scheduled on each machine:

    Conflicts=apache@*.service
Can you either remove the Conflicts, or add more machines to the cluster?

**Comment by terrylai** [comment]
Thanks for your kind answer.

It seems that the coreos example about the fleet should be updated as I
followed the full steps at there.

The link is here:
https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/

BR,
Terry


BR,
Terry

**Comment by xfer** [comment]
> Could anyone teach me how to do so that I can run 2 instances simultaneously?

probably https://coreos.com/docs/running-coreos/platforms/vagrant/
