### ISSUE TITLE
Fleet units fail - no such file or directory, corrected by daemon-reload

### ISSUE THREAD

**Issue by guruvan** [coreos/fleet#1152]
@bcwaldon  FINALLY... I caught one NEW unit doing this, and conveniently, one that needs no sanitization for posting.

The dependency of %p-disk@%i.service loaded fine, the following unit did not run

The host in question is on 607.0, and the etcd hosts are not yet on 607 (this may be the issue here, it's not 100% clear yet) - the etcd machines are on either 557.2 or 584.0 (they've not gotten their turn to rewrite cloudconfigs that are broken in 607.0) 

I'm guessing there's something to be looking for on an etcd host, but .....which one, and exactly what is something that I need to know to find that. 
 - I've asked a few times for specific log error messages you're looking for. I'll find 'em if you'll tell me, but if I don't know what they are it's nearly impossible to find them unless I get lucky and spot something on a brand new host with nothing running on it.

```
# /run/fleet/units/electrum-grs@usw2.electrum.service
[Unit]
Description=Electrum: %p for %i
After=%p-disk@%i.service
Requires=%p-disk@%i.service

[Service]
User=root
Type=notify
NotifyAccess=all
TimeoutStartSec=900
TimeoutStopSec=15
Restart=always
RestartSec=10s
ExecStartPre=/usr/bin/docker run --rm -v /opt/bin:/opt/bin ibuildthecloud/systemd-docker
ExecStartPre=-/usr/bin/docker kill %p_%i
ExecStartPre=-/usr/bin/docker rm %p_%i
ExecStart=/opt/bin/systemd-docker run --name %p_%i  -v /opt/tmp/%i/%p/var/electrum-grs-server:/var/electrum-grs-server  -v /opt/tmp/%i/%p/home/coin:/home/coin  -v /opt/tmp/%i/%p/app/certs:/app/certs   -p 50001:50001  -p 50002:50002  -p 8000:8000  -h %p.electrum-grs-server.domain  registry.domain/electrumgrs/electrumgrs-groestlcoind
ExecStop=-/usr/bin/docker kill %p_%i
ExecStopPost=-/usr/bin/docker rm %p_%i

[X-Fleet]
Conflicts=%p@*.service *@*.tate-server.service
MachineMetadata="srv=wrkr" "nat=0" "role=txn"
MachineMetadata="srv=wrkr" "nat=0" "role=api"
MachineOf=%p-disk@%i.service
```

````
Mar 12 16:10:40 aws-txn-68-209 fleetd[651]: INFO manager.go:262: Writing systemd unit electrum-grs@usw2.electrum.service (972b)
Mar 12 16:10:41 aws-txn-68-209 fleetd[651]: ERROR manager.go:136: Failed to trigger systemd unit electrum-grs@usw2.electrum.service start: Unit electrum-grs@usw2.electrum.service failed to load: No such file or directory.
Mar 12 16:10:41 aws-txn-68-209 fleetd[651]: INFO reconcile.go:311: AgentReconciler completed task: type=LoadUnit job=electrum-grs@usw2.electrum.service reason="unit scheduled here but not loaded"
Mar 12 16:10:41 aws-txn-68-209 fleetd[651]: INFO reconcile.go:311: AgentReconciler completed task: type=StartUnit job=electrum-grs@usw2.electrum.service reason="unit currently loaded but desired state is launched"
```

**Comment by guruvan** [comment]
Follow up:

ssh to offending host, 
```
core@this.box /opt/tmp/usw2.electrum/electrum-grs-disk $ systemctl status electrum-grs@usw2.electrum.service                                            
● electrum-grs@usw2.electrum.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
core@this.box /opt/tmp/usw2.electrum/electrum-grs-disk $ systemctl cat electrum-grs@usw2.electrum.service 
core@this.box /opt/tmp/usw2.electrum/electrum-grs-disk $
core@this.box /opt/tmp/usw2.electrum/electrum-grs-disk $ systemctl daemon-reload
core@this.box /opt/tmp/usw2.electrum/electrum-grs-disk $ systemctl cat electrum-grs@usw2.electrum.service 
# /run/fleet/units/electrum-grs@usw2.electrum.service
[Unit]
Description=Electrum: %p for %i
After=%p-disk@%i.service
Requires=%p-disk@%i.service
```
ETC

**Comment by balboah** [comment]
Same here, very annoying. Random service failures becuase of service files disappearing.
```Loaded: not-found (Reason: No such file or directory)```

**Comment by balboah** [comment]
Might be related to out of memory in this case

**Comment by pmorton** [comment]
Hi - I am having the same problem. Hosts are 607 (both etcd and workers). 

```
Unit: fleet.service; Image: /usr/bin/fleetd; Message: INFO manager.go:275: Removing systemd unit worker@40.service
Unit: fleet.service; Image: /usr/bin/fleetd; Message: INFO reconcile.go:311: AgentReconciler completed task: type=UnloadUnit job=worker@40.service reason="unit loaded but not scheduled here"
Unit: fleet.service; Image: /usr/bin/fleetd; Message: INFO engine.go:272: Scheduled Unit(worker@40.service) to Machine(6af7de28a0a640f68983c9abb10882ec)
Unit: fleet.service; Image: /usr/bin/fleetd; Message: INFO reconciler.go:163: EngineReconciler completed task: {Type: AttemptScheduleUnit, JobName: worker@40.service, MachineID: 6af7de28a0a640f68983c9abb10882ec, Reason: "target state launched and unit not scheduled"}
Unit: fleet.service; Image: /usr/bin/fleetd; Message: INFO manager.go:262: Writing systemd unit worker@40.service (1097b)
Unit: fleet.service; Image: /usr/bin/fleetd; Message: ERROR manager.go:136: Failed to trigger systemd unit worker@40.service start: Unit worker@40.service failed to load: No such file or directory.
```

Our process is that we delete a destroy around 40 units, wait for that to be complete and then submit, load and start 40 more units. In the process a number of them randomly fail to start. Usually anywhere from 1-13 units. This feels like it might be a race condition between the writing of the batch of unit files and reloading the unit-file into systemd.

**Comment by bcwaldon** [comment]
@pmorton Could you please share the contents of `worker@40.service`?

**Comment by tleyden** [comment]
@bcwaldon I reported a similar bug with complete steps to repro including unit files -- see https://github.com/coreos/fleet/issues/1149.  

The unit file that failed in my case was [this one](https://github.com/tleyden/couchbase-cluster-go/blob/master/data/couchbase_sidekick%40.service.template)  (its a go template, where CONTAINER_TAG is related to the tag of the docker image, and UNIT_NUMBER is generated at runtime depending on how many units the user wants to kick off)

**Comment by bcwaldon** [comment]
I was able to get together a set of repro steps and file https://github.com/coreos/fleet/issues/1158. Please coordinate further communication there.
