### ISSUE TITLE
Fleet units getting failed due to no reason when starting

### ISSUE THREAD

**Issue by arunoda** [coreos/fleet#1159]
I'm using the latest stable fleet version (fleetctl version 0.9.1) and using a CoreOS cluster on digitalocean.
We've a 3 etcd nodes and dozen of worker nodes.

when we are starting units, sometimes they get failed due to no reason. Underline service behind the unit is getting started perfectly. But, systemd stops the unit after it gets started. 

This is what's happening

We start a unit with `fleetctl start storeman@1`

It got failed, here's the status.

~~~shell
core@core-etcd1 ~/unit-files $ fleetctl status storeman@1.service
● storeman@1.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Fri 2015-03-20 08:51:36 UTC; 6min ago
 Main PID: 4883 (code=exited, status=137)

Mar 20 08:50:57 core-storeman1 sh[4883]: M => Processed:       0     Queue Size:       0   (60s)
Mar 20 08:50:57 core-storeman1 sh[4883]: T => Processed:       0     Queue Size:       0   (60s)
Mar 20 08:51:04 core-storeman1 sh[4883]: 2015/03/20 08:51:04 INF    1 [metrics/store] querying nsqlookupd http://10.132.67.160:4161/lookup?topic=metrics
Mar 20 08:51:05 core-storeman1 sh[4883]: 2015/03/20 08:51:05 INF    2 [traces/store] querying nsqlookupd http://10.132.67.160:4161/lookup?topic=traces
Mar 20 08:51:36 core-storeman1 systemd[1]: Stopping Storeman...
Mar 20 08:51:36 core-storeman1 systemd[1]: storeman@1.service: main process exited, code=exited, status=137/n/a
Mar 20 08:51:36 core-storeman1 docker[5652]: storeman1
Mar 20 08:51:36 core-storeman1 systemd[1]: Stopped Storeman.
Mar 20 08:51:36 core-storeman1 systemd[1]: Unit storeman@1.service entered failed state.
Mar 20 08:51:36 core-storeman1 systemd[1]: storeman@1.service failed.
~~~

And here's our unit-file

~~~conf
[Unit]
Description=Storeman
Requires=dockerauth.service
After=dockerauth.service

[Service]
User=core
TimeoutStartSec=0
TimeoutStopSec=0
EnvironmentFile=/etc/environment
ExecStartPre=/usr/bin/docker pull xxxxxxx:latest
ExecStartPre=-/usr/bin/docker rm -f storeman%i
ExecStart=/bin/sh -c "\
  source /etc/profile.d/etcdctl.sh; \
  L1=`etcdctl get /kadira/service/nsqd-lookup/1/http-address`; \
  L2=`etcdctl get /kadira/service/nsqd-lookup/2/http-address`; \
  /usr/bin/docker run \
    --name storeman%i \
    -e MONGO_URL=mongodb://xxxxxxx \
    -e MONGO_GOROUTINES=128 \
    -e MONGO_BUFFER_SIZE=4096 \
    -e NSQLOOKUPD_ADDRESSES=\"$L1,$L2\" \
    -e NSQ_MAX_INFLIGHT=5000 \
    -e NSQ_METRICS_TOPIC=metrics \
    -e NSQ_METRICS_CHANNEL=store \
    -e NSQ_TRACES_TOPIC=traces \
    -e NSQ_TRACES_CHANNEL=store \
    -e LOG_INTERVAL=60 \
    -e GOMAXPROCS=2 \
    xxxxxxx \
"
ExecStop=/usr/bin/docker rm -f storeman%i

[X-Fleet]
MachineMetadata=type=storeman
Conflicts=storeman@*.service
~~~

We see these kind issues a lot and we are running a lot of services and queues. So, this is not something we can bare.

We are pretty new both CoreOS and SystemD. Wanna a know we are doing something wrong or is this relevant to some existing bug. If so, how we can help you?

**Comment by philips** [comment]
It looks as if the process exited with a 137 exit code. If you want systemd to restart it for you you will need to add a restart policy. http://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

**Comment by arunoda** [comment]
Thanks. I can do that.
But, how does it got 137 anyway.

That's my issue. Who's is going to SIGKILL this unit. It seems like fleet is systemd stops the service.
What could be the potential reason for that?

**Comment by philips** [comment]
@arunoda I don't know what is SIGKILL'ing the process. Perhaps there is something in the full system journal around that time that might indicate `journalctl --since "2015-03-20 08:49"`? Try running `dmesg` too? Maybe the kernel is killing it?

**Comment by arunoda** [comment]
Okay. I'll check that.

**Comment by bcwaldon** [comment]
@arunoda were you able to make any progress here?

**Comment by arunoda** [comment]
I think we can close this for now. We couldn't find out the reason. But Restart=always works for us.
