### ISSUE TITLE
Multiple lines for ExecStart script?

### ISSUE THREAD

**Issue by olalonde** [coreos/fleet#1161]
I was wondering if it was possible to split the `ExecStart=...` line into multiple lines for easier readibility? I know this is probably a systemd question but I didn't know where to ask it.

**Comment by olalonde** [comment]
Oops, answer to my own question from http://www.freedesktop.org/software/systemd/man/systemd.unit.html: 

Empty lines and lines starting with # or ; are ignored. This may be used for commenting. Lines ending in a backslash are concatenated with the following line while reading and the backslash is replaced by a space character. This may be used to wrap long lines.

**Comment by czerasz** [comment]
Example which works:

```
[Unit]

...

ExecStart=/usr/bin/docker run --name=nginx \
                              --net=host --restart=no \
                              --volume='${VOLUMES_DIRECTORY}/nginx/wwww:/usr/share/nginx/html:ro' \
                              --volume='${VOLUMES_DIRECTORY}/nginx/config:/etc/nginx:ro' \
                              nginx:1.9.10

...
```
