### ISSUE TITLE
Empty warning Messages

### ISSUE THREAD

**Issue by databus23** [coreos/fleet#1164]
I'm using fleet 0.9.1 and in the fleet log I can see lines like:

    Mar 23 15:15:45 mampe fleetd[2940]: WARN reconcile.go:61:
    ...
    Mar 23 14:59:02 mampe fleetd[2940]: WARN engine.go:116:

Looking at https://github.com/coreos/fleet/blob/v0.9.1/agent/reconcile.go#L61 and https://github.com/coreos/fleet/blob/v0.9.1/engine/engine.go#L116 it seems to me `log.Warning(msg)` is somehow dropping the message.  Maybe it should also be `log.V(1).Warning(msg)` ?

**Comment by denderello** [comment]
Seeing many of those too in our clusters.

**Comment by bcwaldon** [comment]
Fixed by https://github.com/coreos/fleet/pull/1068. Will be available in the next release.
