### ISSUE TITLE
Add ability to limit leadership to a dedicated set of machines

### ISSUE THREAD

**Issue by denderello** [coreos/fleet#1166]
Currently the leadership can be taken by every agent that is running within a cluster. However it would be nice to limit the leadership to just a subset of the machines available. This could make sense for setups like ["Production Cluster with Central Services"](https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services) where the fleet leader could be only running on machines that e.g. have `role=services` configured as metadata.

**Comment by bcwaldon** [comment]
@denderello Playing devil's advocate here: what would this feature actually allow you to do?

**Comment by denderello** [comment]
Imagine a setup like the one described in ["Production Cluster with Central Services"](https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services) where one sets aside a dedicated number of machines for central services. These machines also run etcd as a central service. All other machines are considered workers to run jobs on it for all the tasks that have to be done by the applications that are scheduled on the cluster.

Since the fleet leader is [responsible for scheduling decisions](https://github.com/coreos/fleet/blob/master/Documentation/architecture.md#engine) I would consider it to be a central service too and therefore it should be possible to run it only on the machines that are set aside for this purpose. This would make the separation of the two types of machines in this cluster setup clearer.

From a technical standpoint we can clearly see that the fleet leader consumes more CPU cycles and that a mechanism like this could come in handy to make it run on a machine having enough resources available. I admit that this should not mainly drive the decision but it's still something to think about.
