### ISSUE TITLE
fleetctl list-units can not get all units

### ISSUE THREAD

**Issue by holmes86** [coreos/fleet#1172]
hi, I found this problem as follow. I have 102 unit files and all unit files is running. but I use "fleetctl list-units“ that It's different every time. what's the problem? thanks. 

```
# fleetctl list-unit-files | wc -l
102
# fleetctl list-units| wc -l
77
# fleetctl list-units| wc -l
79
# fleetctl list-units| wc -l
80
# fleetctl list-units| wc -l
80
# fleetctl list-units| wc -l
83
```

**Comment by jonboulle** [comment]
Assuming a healthy cluster and that every unit is schedulable (i.e. that they don't have unfulfillable requirements), the numbers _should_ converge. Does list-units reach a steady state?

**Comment by holmes86** [comment]
I think list-units should get all units state. At least adding a argument can get all units state. and the  api /state also can not do this. I don't know why random get to units of the state?

**Comment by holmes86** [comment]
@jonboulle  yes, all units is schedulable  and running. every list-units can not reach a steady state. thanks.

**Comment by jonboulle** [comment]
Are you running this on one of the machines in the cluster or remotely?

**Comment by holmes86** [comment]
I running units on a cluster of  two machines.
```
MACHINE         IP              METADATA
21abf58f...     10.x.x.x   host=10.x.x.x,zone=test
9c33fade...     10.x.x.x   host=10.x.x.x,zone=test
```

**Comment by jonboulle** [comment]
@holmes86 can you run `sudo systemctl kill --signal SIGUSR1 fleet` and then provide the output that gets dumped to the journal? (`journalctl -u fleet`)

**Comment by holmes86** [comment]
@jonboulle because of fleet always restart all units(https://github.com/coreos/fleet/issues/1181), so I stopped fleet proccess. I will make a test evnroment. I think I can reproduce this problem. I will put journal late. thanks

**Comment by bcwaldon** [comment]
@holmes86 any more info here?

**Comment by bcwaldon** [comment]
No update in 2 months
