### ISSUE TITLE
v0.9.2: fleetctl locally vs tunnel reports different files, tunnel does not allow starting of services, can't stop services either

### ISSUE THREAD

**Issue by nickjj** [coreos/fleet#1174]
#### Versions
**fleetctl:** v0.9.2 on both machines
**Local:** coreos 640.0 (alpha)
**Tunneling in from:** xubuntu 14.04 64bit

When tunneling it gives back the correct IP.
I also get the same results using both the env variable and --tunnel flag.

##### Listing units

- [LOCAL] `fleetctl list-unit-files` I get back the 8 units I have
- [TUNNEL] I only get back 6

##### Start

- [LOCAL] `fleetctl start foo` starts foo as expected
- [TUNNEL] it says it starts it on the correct IP but it's not started

##### Stop (does not function at all)

- [LOCAL] `fleetctl stop foo` foo container is still running, verified with `docker ps`
- [TUNNEL] same results as local

##### Destroy

- [LOCAL] `fleetctl destroy foo` foo container is stopped and removed
- [TUNNEL] it says it's destroyed but the container is still running

**Comment by bcwaldon** [comment]
@nickjj Can you share the explicit output of these commands rather than a summary?

**Comment by nickjj** [comment]
@bcwaldon, Unfortunately I cannot. I've torn down the infrastructure since then.

**Comment by bcwaldon** [comment]
Ok, there's not much I can do here. Please reopen if you are able to collect actual debug output.
