### ISSUE TITLE
Obsolete entries in etcd when destroying units

### ISSUE THREAD

**Issue by denderello** [coreos/fleet#1179]
Fleet agents create obsolete entries in etcd's `/_coreos.com/fleet/job` folder when a certain amount of units are started within a cluster and `fleetctl destroy` is called. The number of units result in a long reconciliation time in the agents. When the leader now deletes a job and an agent is inside his loop, the agent will write a state update while the leader has already deleted the job folder. 
This leads to obsolete entries in the `/_coreos.com/fleet/job` folder (as the leader and agent ignore incomplete job entries), which will just grow and result in a lot of unnecessary json unmarshalling operations and memory consumption.

I was able to reproduce this on a 3 node cluster on AWS where 1000 units had been started using [giantswarm/fleet-stress](https://github.com/giantswarm/fleet-stress). After all those 1000 units had been running, starting up additional 6 units and destroying them afterwards resulted in the described scenario.

However when I did all state transitions by hand (`start -> stop -> unload -> destroy`) instead of taking the "short track" of just destroying a started unit, no obsolete got created. I assume that this is a race condition between agent and leader.

If you need more information I am happy to help.

**Comment by bcwaldon** [comment]
This would be solved if we rearchitect how presence information is gathered and communicated (#746). In the meantime, it might be worth considering a garbage-collection routine in the fleet engine to stop this memory leak.

**Comment by dongsupark** [comment]
I fully agree with the original request, but it could be addressed by PRs like https://github.com/coreos/fleet/pull/1426 or https://github.com/coreos/fleet/pull/1510.
So I'm closing it for now.
