### ISSUE TITLE
Release 0.9.3 w/ all the changes

### ISSUE THREAD

**Issue by radeksimko** [coreos/fleet#1180]
The latest release is really just retagged `0.9.1`, which you can see on the Releases page, so both `0.9.1` & `0.9.2` are identical (except the version number), unless I'm missing something obvious?

![screen shot 2015-04-08 at 18 57 09](https://cloud.githubusercontent.com/assets/287584/7051683/e14b0bc8-de21-11e4-88d4-9cfe2e4fd5cc.png)

https://github.com/coreos/fleet/compare/v0.9.2...master

Could you please do an actual release? :smiley_cat: 
cc @bcwaldon

**Comment by jonboulle** [comment]
I think GitHub has gone a bit wonky because the tagged commit is not on
master..

**Comment by radeksimko** [comment]
The bug [fixed 20th January](https://github.com/coreos/fleet/pull/1092) still exists in the latest release = my assumption is that Github is actually right in this case.

**Comment by bcwaldon** [comment]
@radeksimko I don't know what GitHub thinks it's doing, but it's definitely not right. I've released v0.9.1 and v0.9.2 off of separate release branches to fix specific bugs. Consider the following:

```
% git log v0.9.0..v0.9.1 | cat
commit 037e9996d85f4c4a9c66b891b7343acf533aa28d
Author: Brian Waldon <brian@waldon.cc>
Date:   Fri Feb 27 14:09:01 2015 -0800

    version: bump to v0.9.1

commit 6f60d76ada4c7bf85ed785aa29628b9cc1d777e2
Author: Brian Waldon <brian@waldon.cc>
Date:   Thu Feb 26 18:05:55 2015 -0800

    agent: replace taskChain with sorted []task

    Agents need to execute all unit file load operations before
    attemping to start anything. The taskChain approach did not
    provide this safetly. An ordered list of tasks gives us what
    we need and greatly simplifies the codebase.

    This is a backport of 7b44072630b15f469c14ea6c5a27497348b9240f.

% git log v0.9.1..v0.9.2 | cat
commit e0f7a2316dc6ae610979598c4efe127ac8ff1ae9
Author: Brian Waldon <brian@waldon.cc>
Date:   Mon Mar 30 17:04:57 2015 -0700

    version: bump to v0.9.2

commit 369c3ad98e893e6c9f95156c4d94ca8f2c8353e2
Author: Brian Waldon <brian@waldon.cc>
Date:   Mon Mar 30 16:42:52 2015 -0700

    agent: sort unit names for deterministic results

commit 1c1bda683def1efa15ef774ec3c506f8fee2e46b
Author: Brian Waldon <brian@waldon.cc>
Date:   Mon Mar 30 15:52:50 2015 -0700

    agent: reload unit files on load/unload

commit b5e10c1e44dcb8251ff6745a72034174ca627495
Author: Brian Waldon <brian@waldon.cc>
Date:   Mon Mar 30 14:59:15 2015 -0700

    systemd: rely on caller to reload unit files

commit 4287506e6c4abffb4c0a64b975c19951d64ace77
Author: Brian Waldon <brian@waldon.cc>
Date:   Mon Mar 30 14:56:02 2015 -0700

    unit: add UnitManager.ReloadUnitFiles
```

master does contain patches that have yet to be released, but this is because master also contains features that we are not ready to push out.

**Comment by radeksimko** [comment]
> master does contain patches that have yet to be released, but this is because master also contains features that we are not ready to push out.

I see, that's understandable then.

**Comment by bcwaldon** [comment]
FYI We just cut v0.10.0
