### ISSUE TITLE
Mount unit bind to a named service

### ISSUE THREAD

**Issue by dloic** [coreos/fleet#1194]
Hi!

I'm trying to achieve the following, with the latest CoreOS stable (633.1.0): have a service that rely on an mounted device (mainly for backup). Here is how I plan to do it, I'm using AWS terminology below:

- Create an EBS volume (one time) during my stack creation
- Create three units:
    * One dedicated for my service A that require a mount point at /mnt/A : **A@.service**
    * One dedicated to attach the EBS to an instance at /dev/xvbf : **A-volume@.service**
    * One dedicated to mount /dev/xvbf at /mnt/A : **mnt-A.mount**

Then, when I want to schedule the service, I would run:
```
fleetctl start mnt-A.mount A@vol-ID.service A-volume@vol-ID.service
```
Now complicated stuff: how to bind each unit together so everything will be launch on the same instance. I've tried in different ways:

- **A@.service** requires/after **mnt-A.mount** AND **mnt-A.mount** requires **A-volume@.service**
- Define **mnt-A.mount** like **mnt-A@.mount** giving me the possibility to do **mnt-A@vol-ID.mount** and be sure that in the unit file I add an X-Fleet condition with MachineOf **A-volume@%i.service**

Every time I tried to template my mount unit, fleetctl did not return when starting the unit. After check, unit file is deployed but will never start. I'm not sure if I'm trying to achieve something that is not possible and if I'm doing it wrong. If I do not template it, it can start, but without any condition regarding the instance.

Any help would be appreciated :)

**Comment by dmitryint** [comment]
Look at [mountWait](https://github.com/ceph/ceph-docker/blob/master/rbd-volume/mountWait/main.go) program. I use it for similar tasks.
This is go-based daemon, that keeps systemd service running while volume is mounted.
In your case you need to replace mnt-A@.mount unit on mnt-A@.service containing mountWait call.

**Comment by bcwaldon** [comment]
@dloic I don't know what you mean by "Every time I tried to template my mount unit" - can you explain this?

**Comment by dloic** [comment]
Hi @bcwaldon!

I tried to template the unit used to mount my volume. What I did is to have file named mnt-A@.mount and then run fleetctl start mnt-A@vol-ID.mount (replacing vol-ID by any EBS volume id).

With this, I can have a mount file like this:

```
[Unit]
Description = Mount for Rabbitmq volume
Requires=rabbitmq-volume@%i.service
After=rabbitmq-volume@%i.service

[Mount]
What=/dev/xvdf
Where=/mnt/rabbitmq
Type=ext4

[X-Fleet]
MachineOf=rabbitmq-volume@%i.service
```

which is bind to the proper rabbitmq-volume unit.
But when I start this, got no response from fleetctl (neither success or errors).

**Comment by arthur-c** [comment]
Hi @dloic , do you have any update ?

I tried to load a systemd mount unit with fleetcl, all I got is:

```
Jun 16 11:51:20 aws-beta-coreos-02 systemd[1]: [/run/fleet/units/data-mongodb-log@1.service:4] Unknown section 'Mount'. Ignoring.
Jun 16 11:51:20 aws-beta-coreos-02 systemd[1]: data-mongodb-log@1.service lacks both ExecStart= and ExecStop= setting. Refusing.
```

It doesn't seem possible to handle mount points with fleet, am I right ?

**Comment by dloic** [comment]
Hi!

Sorry, no update on my side. I've implemented a workaround to do almost the same thing but without templating the unit.

**Comment by madeddie** [comment]
This is probably caused by systemd's rule that "Mount units must be named after the mount point directories they control." (from the systemd.mount manpage)

**Comment by bcwaldon** [comment]
No update, and @madeddie provided the likely solution

**Comment by arthur-c** [comment]
Hi,

I ran into the same problem, I want to schedule a mount unit from a template and it's not possible because systemd doesn't like it:

```
 fleetd[766]: ERROR generator.go:65: Failed fetching current unit states: Unknown interface 'org.freedesktop.systemd1.Unit'.
ERROR reconcile.go:79: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unknown interface 'org.freedesktop.systemd1.Unit'.
```

The documentation need to be fixed (https://coreos.com/fleet/docs/latest/unit-files-and-scheduling.html) because it doesn't precise we can't template mount units:
"suffix must be one of the following unit types: service, socket, device, mount, automount, timer, path"
and
"You can then instantiate units by creating new units that match the instance pattern <name>@<instance>.<suffix>"

A workaround in fleet could be very cool. The more I manage my cluster units with fleetctl, the happier I am !
