### ISSUE TITLE
client pkg imports too much

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#1196]
A user of the `client` package is required to vendor a large dependency tree just to use the fleet API client. Ideally, everything the user needs is contained in the client package itself. One exception to this might be the schema package.

**Comment by dongsupark** [comment]
I'm not sure I understand this issue. At least in the current tree with native go vendoring, I don't think it's necessary to import so many packages, only for using the client package.
So I'm closing it for now.
