### ISSUE TITLE
need a strong validation on unit file

### ISSUE THREAD

**Issue by duffqiu** [coreos/fleet#1199]
When I try to do a side kick for a unit, I made a mistaken on the unit file for the key word "BindsTo"
I wrote it as "BindTo" without "s"
But fleet/fleetctl doesn't report any error.
But sometimes, it is blocked during start this wroing unit and there is no error logs in etcd, or fleet or systemd

So I hope fleet can do some strong validation on the uint file at the submit stage.

**Comment by bcwaldon** [comment]
fleet is not going to validate the content of systemd options it does not control. We cannot chase systemd releases with validation code. Asserting the format using github.com/coreos/go-systemd/unit is all we can reasonably do for now.
