### ISSUE TITLE
sidekick unit state doesn't sync with main unit after stop

### ISSUE THREAD

**Issue by duffqiu** [coreos/fleet#1200]
When I write a sidekick unit for the main unit, I find the below issue (maybe there are some reasons for it?)

After I stop the main unit, I can start it agian
But for the sidekick unit, the fleetctl client can't start the sidekick uint agin, why?
And there is not any error log in the fleet, or systemctl or etcd

Finally, I found the workaround way that I need to the `load` and then `start` the sidekick.

But I got the below message from fleet daemon

```
Apr 25 03:26:44 coreos-107 fleetd[27079]: INFO reconcile.go:311: AgentReconciler completed task: type=StartUnit job=test@1.service reason="unit currently loaded but desired state is launched"
```

Any suggestion to this issue?

**Comment by bcwaldon** [comment]
That log you referenced is not an error - it is communicating to you that it ran a StartUnit systemd job on test@1.service because it needed to launch the unit. Look at #1025 for more information on why `fleetctl  start` does not behave like you expect.
