### ISSUE TITLE
Fleet units fail - no such file or directory, corrected by daemon-reload

### ISSUE THREAD

**Issue by guruvan** [coreos/fleet#1206]
@bcwaldon Revisiting this issue. I have just rebuilt my cluster and all my workers on  coreos 633.1.0 and this is still constant. Failed units do not respond to "fleetctl stop ; fleetctl start" - only correction is to login to the offending machine and do a daemon-reload. 

Basically, I have to manage all my services by hand, logging into the box and running a deamon-reload before running most fleet services, and then running the services. Almost never will fleet start up a failed unit (so if I remove a worker host, I have to 100% manually restart the services on another host) 

What can I provide that will help this become fixed? This all worked fine in 494 and previous.

**Comment by scole-scea** [comment]
That fix went into fleet 0.9.2. CoreOS 633.1.0 (the stable channel) still has fleet 0.9.1, which is why you still see the issue. 

If you want a workaround while we wait for 0.9.2 to move to stable, you can try the service I use to handle this in our environment: https://gist.github.com/scole-scea/177a367c51d0b93d51f6

**Comment by guruvan** [comment]
IAh. I didn't notice that as we went back into stable for the time being - and we'd definitely had the issue on mixed 0.9.1 / 0.9.2 network. 

@scole-scea not only is that a great script, but the escaping... I will put this into service asap.

@bcwaldon my bad for not noticing I'm back on 0.9.1 - will revisit this issue when my entire network is up to 0.9.2 - maybe you'd rename this issue with "possible workaround" if you'd think the above will get folks by?

**Comment by bcwaldon** [comment]
This has already been documented at-length in other issues, and will be fixed in stable shortly.
