### ISSUE TITLE
fleet enters into confusing state if run a High Availability Service but without instance number

### ISSUE THREAD

**Issue by duffqiu** [coreos/fleet#1207]
fleet0.9.1 in CoreOS633.1.0

I submit a High Availability Service for example test@.service
But I make a mistake when I run this serivce without instance number, I just call `fleetctl start test@service`. then the command is blocked. I have to use ctrl+c to exit.

Then fleet doesn't work on the first machine, the log show there is some wrong state in etcd. After I restart fleet service, then it returns to work.

I hope we can add some validtaion when start the High Availability Service. if there is no instance number, we need to return error.

**Comment by bcwaldon** [comment]
See https://github.com/coreos/fleet/issues/969
