### ISSUE TITLE
How does fleet determine it's IP shown in list-machines?

### ISSUE THREAD

**Issue by hookenz** [coreos/fleet#1215]
How does fleetctl determine which IP unit is on?

e.g.  I have machines with 2 interfaces, one has the 10.1.10.0/24 ethernet network
The main one is an infiniband network with IP 10.10.10.0/24.

However, With a unit file contain identical units, the MACHINE IP changes between them.  Otherwise it still seems to work.  

The setting applied in cloud-init for pubblic-ip on a machine showing in the 10.1.10.x range contains a10.10.10.x ip.

UNIT                            MACHINE                 ACTIVE  SUB
consul-discovery@1.service      2a117042.../10.10.10.42 active  running
consul-discovery@2.service      7dc7eabc.../10.1.10.24  active  running
consul-discovery@3.service      8087f924.../10.1.10.23  active  running
consul@1.service                2a117042.../10.10.10.42 active  running
consul@2.service                7dc7eabc.../10.1.10.24  active  running
consul@3.service                8087f924.../10.1.10.23  active  running

**Comment by bcwaldon** [comment]
By default, it uses netlink to look up the default route [0]. You can alternatively configure the IP directly in fleetd's config file [1].

[0] https://github.com/coreos/fleet/blob/master/machine/coreos.go#L170-L196
[1] https://github.com/coreos/fleet/blob/master/Documentation/deployment-and-configuration.md#public_ip
