### ISSUE TITLE
Race condition in unloading units

### ISSUE THREAD

**Issue by patrickbcullen** [coreos/fleet#1216]
I have noticed a race condition in production where job is supposed to be unloaded, but never stops.

I think I found the bug here https://github.com/coreos/fleet/blob/7a648771ca405019486f52d83ec8ee3f6810a6ce/agent/agent.go#L98. 

I have an example where the systemd file is gone, but the unit is still running. This happened because the kill command in the systemd file did not succeed. Since this code does not check for error it happily removes all the systemd files. Now that the systemd files are gone I cannot stop it through fleet since fleet cannot call the systemd stop because it already deleted the systemd file.

**Comment by bcwaldon** [comment]
@patrickbcullen Can you provide an explicit set of repro steps for this?
