### ISSUE TITLE
Fleetd should prevent to run more than one daemon

### ISSUE THREAD

**Issue by wuqixuan** [coreos/fleet#1220]
Currently, fleetd doesn't prevent to run more than one daemon, it may has some potential problem. Should create fleet.pid in /var/run/

**Comment by bcwaldon** [comment]
From #1229:

> I don't think this is necessary, and will prevent legitimate use cases where multiple fleet daemons can run on the same machine. Solving #615 solves the actual issue here.

I believe we will solve this more appropriately via #615
