### ISSUE TITLE
I wonder what's wrong with this , any one can help me ?!

### ISSUE THREAD

**Issue by ZhiqinYang** [coreos/fleet#1222]
ERROR reconcile.go:79: Unable to determine agent's current state: failed fetching unit states from UnitManager: No such method 'ListUnits'
ERROR generator.go:65: Failed fetching current unit states: No such method 'ListUnits'

with ubuntu14.04

I rebuild it  it come out that :ERROR reconcile.go:79: Unable to determine agent's current state: failed fetching unit states from UnitManager: Rejected send message, 2 matched rules; type="method_call", sender=":1.32" (uid=1000 pid=5321 comm="./fleetd /etc/fleet/fleet.conf ") interface="org.freedesktop.systemd1.Manager" member="ListUnits" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=3502 comm="/usr/lib/x86_64-linux-gnu/systemd-shim ")
ERROR generator.go:65: Failed fetching current unit states: Rejected send message, 2 matched rules; type="method_call", sender=":1.32" (uid=1000 pid=5321 comm="./fleetd /etc/fleet/fleet.conf ") interface="org.freedesktop.systemd1.Manager" member="ListUnits" error name="(unset)" requested_reply="0" destination="org.freedesktop.systemd1" (uid=0 pid=3502 comm="/usr/lib/x86_64-linux-gnu/systemd-shim ")

**Comment by mischief** [comment]
@ZhiqinYang as far as i can tell, ubuntu 14.04 does not use systemd. fleetd depends on systemd and there are no plans to support a different init system.
