### ISSUE TITLE
Allow Fleet to schedule with Conflicts against units not scheduled with fleet or that are not certain machine id's

### ISSUE THREAD

**Issue by hookenz** [coreos/fleet#1226]
I have some machines with some unit files placed into /etc/systemd/system.
These machines have physical drives attached and unit files to mount file systems and start databases.
Although these machines are part of the CoreOS cluster and can run other things, some units I wouldn't want to schedule there.  

Unfortunately, suppose I have a unit /etc/systemd/system/mysql.service and then schedule another unit with fleet and place Conflicts=mysql.service, it causes the scheduler to hang when trying to schedule the unit.

Also, fleet only has the ability to work with glob patters in Go which seem to be very limited.  
It would seem natural to me to be able to specify things like:

MachineOf = ! machineA

But I understand that doesn't make sense for the way MachineOf works.  Because the inverse of ! machineA would be every other machine in the cluster.  I suppose if you are only scheduling a single unit then this would make sense.

Another option would be to have Conflicts= take a machine id as well.

Are there any planned improvements in the pipeline around this area?

**Comment by bcwaldon** [comment]
Could you use the machine metadata feature to do this? You could tag all safe machines with something like `role=schedulable`, or the inverse, tag the unsafe machines as `role=unschedulable`, then create units with matching Metadata options. It might be cleaner if we could use a `!=` operator in the metadata, which is coming in https://github.com/coreos/fleet/pull/1294

**Comment by dongsupark** [comment]
I suppose the question was already answered. Closing.
