### ISSUE TITLE
Metrics for fleet daemon via Prometheus

### ISSUE THREAD

**Issue by mwitkow** [coreos/fleet#1233]
Etcdv2 seems to have preliminary support for Prometheus metrics (2.1alpha). Are you guys planning on adding support for Prometheus metrics as well? It would be fantastic to be able to monitor:
 * whether this fleet instance is the current engine leader
 * task completion broken down by:
   * outcome (success, failure)
   * failure reason code, e.g. `machine_left_cluster`
 * number of locally scheduled fleet tasks (on that instance)
 * number of machines in the cluster by tag string

If it's not on your roadmap anytime soon, can you provide pointers on how to start hacking on this?

**Comment by anglerud** [comment]
I'm planning to have a look at implementing Prometheus metrics - but I'd like to double-check first that I'm not duplicating any effort that he fleet team currently has under way.

**Comment by bcwaldon** [comment]
We haven't considered adding this, but if someone were to add it to fleet, I would be more than happy to review it.

**Comment by webwurst** [comment]
Any news on this? Just found https://github.com/gambol99/prometheus-fleet but haven't tried yet.

**Comment by jonboulle** [comment]
There's a PR at #1415 in need of review - help welcome.

**Comment by kayrus** [comment]
covered by #1524

**Comment by tixxdz** [comment]
https://github.com/coreos/fleet/pull/1524 merged.
