### ISSUE TITLE
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: EOF

### ISSUE THREAD

**Issue by ianbytchek** [coreos/fleet#1237]
I'm trying to get my head around with fleetctl on OS X with CoreOS running through vagrant. I got the latest versions of `coreos-vagrant` where I only changed `$num_instances=2` and followed the [fleet-using-the-client/#vagrant](https://coreos.com/docs/launching-containers/launching/fleet-using-the-client/#vagrant). When I try `fleetctl list-machines` I get the error.

```
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: EOF
```

fleetctl is 0.10.1. What might be wrong?

**Comment by ianbytchek** [comment]
Was my mistake, didn't configure the vagrant as per instructions. Shouldn't there be a more prominent error?

**Comment by karthik101** [comment]
I am getting the same error,  i followed this https://github.com/mohitarora/coreos-vagrant

**Comment by spesnova** [comment]
@karthik101 

Where you are using `fleetctl` on?
If you use `fleetctl` on OS X with CoreOS (Vagrant), you should configure `fleetd` to serve the fleet API over a network address and `fleetctl` to use the API.
I think this documents helps you about this configuration: [Deploying and Configuration fleet
](https://github.com/coreos/fleet/blob/master/Documentation/deployment-and-configuration.md)

If you use `fleetctl` on CoreOS, it looks the `fleetd` (fleet.service) failed to start.
Then `/var/run/fleet.dock` didn't exist.
I recommend you to try [coreos-vagrant upstream](https://github.com/coreos/coreos-vagrant). And don't forget to renew the etcd token.

**Comment by karthik101** [comment]
@spesnova thanks a lot , i use fleetctl on coreos, upstream worked great.

**Comment by bcwaldon** [comment]
@ianbytchek Can you check on fleet.service on the machines in question?

**Comment by pykiss** [comment]
@ianbytchek how did you solve it?

**Comment by ianbytchek** [comment]
@pykiss sorry, can't remember what it was exactly. It remember that I deviated slightly from the instructions and it was something very obvious. Basically try to follow closely the docs and docs in the vagrant repo. Hope this helps.

**Comment by pykiss** [comment]
I've got yet this working, i just change the host machines' names

I dunno what was wrong before, but now it works.

Thanks

**Comment by l15k4** [comment]
I'm struggling with this for hours. It started all of a sudden, a week ago it was working. if I spin up 2 Vagrant machines I get : 
```
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: dial unix /var/run/fleet.sock: no such file or directory
```

If I start a single machine I get : 
```
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: EOF
```

I do exactly as [fleetctl documentation](https://coreos.com/fleet/docs/latest/using-the-client.html) says...

**Comment by nooks** [comment]
Who solved the problem?

**Comment by kulbida** [comment]
halo, any updates?

**Comment by jonboulle** [comment]
This issue has become a bit of a catchall. If you're still experiencing a similar problem could you please file a new one and we can chase up there? thanks.

**Comment by fkpwolf** [comment]
you need change `user-data` to add fleet service, as the coreos-vagrant upstream does.
