### ISSUE TITLE
global=true and MachineMetaData not working - CoreOS stable (647.0.0)

### ISSUE THREAD

**Issue by mvanholsteijn** [coreos/fleet#1239]
I have created a fleet unit file with the following Fleet configuration

[X-Fleet]
MachineMetadata="consul_role=server"
Global=true

The cluster looks like this:
core@core-01 ~ $ fleetctl list-machines
MACHINE		IP		METADATA
65f674a8...	172.17.8.101	region=consul_role=server
89a9ee86...	172.17.8.102	region=consul_role=server
f1f4a2bc...	172.17.8.103	region=consul_role=server

When I do a fleetctl submit and start, the LoadState is not-found. If I remove the MachineMetaData selection, it works fine.

**Comment by scole-scea** [comment]
I think you need to take out the doublequotes. At any rate, none of my unit files have them in the MachineMetadata sections.

They all look like:
```
[X-Fleet]
MachineMetadata=tag=value
```

**Comment by mvanholsteijn** [comment]
Unfortunately, that does not make a difference.

**Comment by mvanholsteijn** [comment]
metadata in user-data was incorrect. It was prefixed with 'region='.
