### ISSUE TITLE
How to do service registration in side-kick file when using flannel

### ISSUE THREAD

**Issue by karthikus** [coreos/fleet#1240]
Before using flannel, I was registration my service ( COREOS_PRIVATE_IPV4) of the host after performing health checks in my side-kick unit file. I have implemented flannel now and with that I need to register the container IP address in the side-kick unit file. Is there a suggested workflow to do that ?

-Karthik

**Comment by bcwaldon** [comment]
@karthikus this isn't really a fleet-specific problem. You need to be able to determine what IP address you have allocated to a given container (assuming that's your use case here), which tools like docker and kubernetes help you solve.
