### ISSUE TITLE
HTTP API authentication

### ISSUE THREAD

**Issue by markrendle** [coreos/fleet#1243]
Is there any built-in authentication support when consuming the Fleet HTTP API directly, or should it be behind a proxy with some kind of authentication handled there? Sorry if this is covered in the docs, I couldn't find it there.

**Comment by bcwaldon** [comment]
There is no native authentication built into the fleet API. You can secure it using file permissions of the unix domain socket, or an HTTP proxy if you want to expose fleet API over a network address.
