### ISSUE TITLE
support environment variable in the Unit part

### ISSUE THREAD

**Issue by duffqiu** [coreos/fleet#1246]
Hi,

I define the unit file's Unit part like below

```
[Unit]
Description=activemq edge for hub1 service unit
After=docker.service
Wants=activemq-hub${HUBID}-edge-master-presence@%i.service
```

but it doesn't work,
the error message is 

```
[/run/fleet/units/activemq-hub1-edge-master@1.service:4] Failed to add dependency on activemq-hub${HUBID}-edge-master-presence@1.service, ignoring: Invalid argument
```

But I can use the environment in the other parts (service  part and x-fleet part)

is it a limitation or do i miss anything?

**Comment by duffqiu** [comment]
more limitation:

in the X-Fleet part, 
I only can use the environment varaible in "Conflicts"
but can't use environment varaible in "MachineOf"

**Comment by jp-gouigoux** [comment]
+1

**Comment by mwhooker** [comment]
I think a potential issue is that the [unit] sections are sent directly to systemd, which doesn't support this, so if fleet added support it would be a compatibility breaking change.

You may be able to use another specifier, like `%p` (see http://www.freedesktop.org/software/systemd/man/systemd.unit.html)

for example, you could have it be

```
Wants=%p-presence@%i.service
```

**Comment by jp-gouigoux** [comment]
Thanks for the solution proposition. Sadly, these qualifiers only work with pre-determined values like %H for the host name or %u for the user name, and what I need is to pass any environment variable. But maybe the best way would be to try and pass this through the cloud-config.yaml file, or when creating the machines themselves. I will try and do so and update this thread if I get it to work.

**Comment by bcwaldon** [comment]
@duffqiu I'm a little confused. What do you mean when you say " I can use the environment in the other parts"? Can you show me an example of this? fleet does absolutely nothing with environment variables in unit files, as far as I know.

**Comment by duffqiu** [comment]
Hi,

I can use environment value (for example ${DOMAIN_NAME}) in `[Service]`, but i can't use it in other part (for example, [Unit])

my example
```
[Unit]
Description=activemq edge for hub1 service unit
After=docker.service
Wants=activemq-hub1-edge-master-presence@%i.service

[Service]
Restart=always
RestartSec=15
TimeoutSec=120
EnvironmentFile=/etc/environment
Environment="DOMAIN_NAME=cluster.duffqiu.org"
Environment="HUBID=1"
ExecStartPre=-/usr/bin/docker kill activemq-hub${HUBID}-edge-master-%i
ExecStartPre=-/usr/bin/docker rm  activemq-hub${HUBID}-edge-master-%i
ExecStartPre=-/usr/bin/docker pull duffqiu/activemq-edge:latest
ExecStart=/usr/bin/docker run  \
                              --name activemq-hub1-edge-master-%i \
                              -e ZK_STR=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 \
                              -e NODE_ID=%i \
                              -e ROLE=0 \
                              -e HUB_ID=${HUBID} \
                              -e REPLIC_NUM=2 \
                              -e REPLIC_WEIGHT=100 \
                              --hostname edge${HUBID}-%i-0.${DOMAIN_NAME} \
                              --dns-search ${DOMAIN_NAME} \
                              --dns ${COREOS_PRIVATE_IPV4} \
                              -p ${COREOS_PRIVATE_IPV4}:61616:61616 \
                              -p ${COREOS_PRIVATE_IPV4}:61619:61619 \
                              -p ${COREOS_PRIVATE_IPV4}:1883:1883 \
                              -p ${COREOS_PRIVATE_IPV4}:5672:5672 \
                              -p ${COREOS_PRIVATE_IPV4}:61613:61613 \
                              -p ${COREOS_PRIVATE_IPV4}:61614:61614 \
                              -p ${COREOS_PRIVATE_IPV4}:8161:8161 \
                              -v /mirror/activemq-edge/hub${HUBID}/%i/master/data:/activemq/data \
                              duffqiu/activemq-edge:latest
ExecStop=-/usr/bin/docker stop activemq-hub${HUBID}-edge-master-%i

[X-Fleet]
Conflicts=activemq-hub1-edge-master@*.service 
Conflicts=activemq-hub1-edge-slave1@%i.service 
Conflicts=activemq-hub1-edge-slave2@%i.service
MachineMetadata=role=back
```

**Comment by devurandom** [comment]
@duffqiu You can use them in `[Service]`, because that is where they are being read: `EnvironmentFile` and `Environment`.

When starting a service, systemd first sets up the env vars as specified by `EnvironmentFile` and `Environment`. Then it runs the `ExecStartPre` and `ExecStart` commands in that environment. `[Unit]` is separate from "starting a service" (`[Service]` section) and thus you don't have access to envvars there.

What you propose would require "global" `EnvironmentFile` and `Environment` instructions in the `[Unit]` sections, which would probably require greater changes in systemd.

**Comment by dongsupark** [comment]
This issue doesn't look like a fleet issue, but rather a design issue on the systemd side.
So closing.
