### ISSUE TITLE
Loading Unit with @ symbol but no index will cause generator.go to spinlock

### ISSUE THREAD

**Issue by jalev** [coreos/fleet#1251]
Hi there,

I'm using Fleet v0.9.2 (CoreOS Stable 647.2.0)

We have a unit called `smoker@.service`. This unit is intended to launch multiple instances of the `smoker` service. 

When running `fleetctl load smoker@.service`, you will immediately get the following logs from Fleet:

```
Jun 16 12:56:43 core-01-01 fleetd[595]: ERROR generator.go:67: Failed fetching current unit states: Unit name smoker@.service is not valid.
Jun 16 12:56:44 core-01-01 fleetd[595]: ERROR generator.go:67: Failed fetching current unit states: Unit name smoker@.service is not valid.
Jun 16 12:56:45 core-01-01 fleetd[595]: ERROR generator.go:67: Failed fetching current unit states: Unit name smoker@.service is not valid.
Jun 16 12:56:46 core-01-01 fleetd[595]: ERROR generator.go:67: Failed fetching current unit states: Unit name smoker@.service is not valid.
Jun 16 12:56:47 core-01-01 fleetd[595]: ERROR generator.go:67: Failed fetching current unit states: Unit name smoker@.service is not valid.
Jun 16 12:56:47 core-01-01 fleetd[595]: ERROR reconcile.go:81: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name smoker@.service is not valid.
```

This causes Fleet to behave in the following ways:
* You won't be able to delete the offending unit from Fleet's registry
* Any attempt to destroy via fleetctl won't be honoured
* You can continue submitting units to Fleet, but it will no longer keep track of them
* Fleet will no longer keep track of job states of all existing units.
* If Fleet is restarted, you won't be able to see units in `fleetctl list-units` as generator is looping on `smoker@.service`

The only way to fix this is to stop Fleet, remove the offending unit from the filesystem, and remove all references to the unit in `etcd`.

Steps to replicate:

1. Create `test@.service` with the following content:
```
[Unit]
Description=This is a test

[Service]
ExecStart=/usr/bin/docker run --name=%p-%i -i debian:latest echo "Hello World!"
ExecStop=/usr/bin/docker rm %p-%i
```

2. Load into fleet with `fleetctl load test@.service`
3. Watch fleet's journal (`journalctl -u fleet -f`)

**Comment by EtienneBruines** [comment]
Sounds like what's happening in #1236?

**Comment by jalev** [comment]
Yep. I'll close this and contribute to that report.
