### ISSUE TITLE
Please provide some more complex fleet scheduling examples

### ISSUE THREAD

**Issue by hookenz** [coreos/fleet#1255]
I'd like to be able to put in the fleet section of cloud-init:
    
    metadata: role=render role=ceph-osd

And I can.  It even appears in fleetctl list-machines.
However, when scheduling if you have a unit file containing

    [X-Fleet]
    MachineMetadata=role=render
    Global=true

And then submit and start that task, I'd expect ti to work wherever role=render is set.  However, it doesn't work presumably because role=ceph-osd is also set. 

Perhaps I can set role=render,ceph-osd
And use MachineMetadata=role=*render*.  But that may not always give the correct results if you're metadata names are not entirely distinct.

Most likely I'd have to instead go the route of

    metadata: render=true ceph-osd=true

And 

    [X-Fleet]
    MachineMetadata=render=true
    Global=true

**Comment by hookenz** [comment]
Ok, it seems that the documentation is also incorrect. 
    metadata: role=render role=ceph-osd

should really be
    metadata: role=render,role=ceph-osd

Then what actually ends up happening is the second role overrides the first definition. 
Also this:
    metadata: render=true ceph-osd=true
Should be:
    metadata: render=true,ceph-osd=true

Then it'll actually work.  The documentation is poor in this area and needs fixing.

**Comment by Dynom** [comment]
That would be very helpful indeed! I too have trouble getting slightly more complex metadata scheduling to work.

**Comment by michalmedvecky** [comment]
Guys, would it be possible to add something like 

MachineMetadata=color!=red 

To schedule units to nodes NOT posessing the "red" color attribute.
