### ISSUE TITLE
Question: is possible to add the capability for goroutine dumping on SIGQUIT/USR1?

### ISSUE THREAD

**Issue by aledbf** [coreos/fleet#1258]
I see this in one of the nodes:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  691 root      20   0 5116796 4.621g   5040 S   3.4 12.4   1508:16 fleetd
```

and I don't have a way to know where the problem is. Besides the memory consumptions fleet is working.
Thanks

**Comment by jonboulle** [comment]
What exactly do you want to dump? You should already be able to see a stack
by sending SIGQUIT, but I'm not sure how that helps you with memory usage.

(fwiw we currently use SIGUSR1 for dumping some other state on what fleet
is doing.)

**Comment by aledbf** [comment]
> What exactly do you want to dump?

Something to get enough information and see if is a particular problem in my cluster or a possible bug.

I rebooted the node so if I see the problem again I will use the SIGUSR1 signal.
Thanks.
