### ISSUE TITLE
No download for 0.10.2?

### ISSUE THREAD

**Issue by eightyeight** [coreos/fleet#1261]
Release [0.10.2](https://github.com/coreos/fleet/releases/tag/v0.10.2) has no binary downloads, unlike [other releases](https://github.com/coreos/fleet/releases/). Is this deliberate, or an oversight?

**Comment by crawford** [comment]
I released 0.10.2 but cannot compile all of the binaries from my systems. @bcwaldon, could you do the builds. I forgot to ask you before.

**Comment by zachlatta** [comment]
:+1: need this so I can update the AUR package.

**Comment by Nosmoht** [comment]
:+1: need this to deploy our local environments to control our fleet

**Comment by bcwaldon** [comment]
I just published the release artifacts: https://github.com/coreos/fleet/releases/tag/v0.10.2

**Comment by eightyeight** [comment]
Thanks :grinning:

**Comment by crawford** [comment]
Thank you, @bcwaldon.

**Comment by zachlatta** [comment]
AUR package updated!
