### ISSUE TITLE
Can I access Container in Fleet A from Fleet B with diff clusters?

### ISSUE THREAD

**Issue by charlesa101** [coreos/fleet#1269]
I am doing a high availability setup with replication between DC1 and DC2

DC1 connects with VPN to DC2

Two different clusters, can I access the containers in FleetA from FleetB

**Comment by mwhooker** [comment]
Access from where? You can have fleetd listen on a port, and then you can pass the port to your fleet client.

**Comment by robszumski** [comment]
Do you want to communicate with services hosted in DC1 with services in DC2? You can do this with your VPN set up, IP/DNS, etc.

If you want to manipulate or read information about units running via fleet, you can expose the fleet API on a port and read/write to it from anywhere. For example, your deployment software/pipeline could launch 2 units of your new container in each DC, for a total of 4 units running. Throw a load balancer in front of that and you're up and running.

Does that help?

**Comment by charlesa101** [comment]
@mwhooker,  @robszumski thanks!
i want to be able to replicate container content from Cluster1 to Cluster2 ....2 different subnets

**Comment by mwhooker** [comment]
np. What you want seems to be out of the scope of fleet.

**Comment by wuqixuan** [comment]
Yes, I also feel it's none of fleet's business.

**Comment by bcwaldon** [comment]
Yep, out of scope.
