### ISSUE TITLE
[0.10.2] 

### ISSUE THREAD

**Issue by akaspin** [coreos/fleet#1275]
Fleet upgraded to 0.10.2:
```
Error running remote command: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running. See https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md for help.
```
WTF?

**Comment by mischief** [comment]
hi @akaspin, can you give more information like what command you ran to produce this error?

**Comment by bcwaldon** [comment]
@akaspin fleet is trying to communicate that you do not have an SSH agent available to authenticate further SSH connections into your cluster. It likely has something to do with you switching terminals, restarting your computer and not starting up ssh-agent again, or something like that. No behavior has changed in fleet.

**Comment by akaspin** [comment]
Sorry, my fall. Broken container.
