### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by devurandom** [coreos/fleet#1282]
Does CoreOS have an Ubuntu PPA for its utilities, such as fleetctl?

**Comment by spesnova** [comment]
See: https://github.com/coreos/fleet/issues/1222#issuecomment-116873084

**Comment by devurandom** [comment]
I was speeking primarily about fleetctl, not fleetd.

**Comment by mischief** [comment]
there is no ubuntu ppa, sorry.
