### ISSUE TITLE
fleetd socket not created

### ISSUE THREAD

**Issue by EtienneBruines** [coreos/fleet#1312]
# Setup
I'm trying to run `fleetd` locally, at my notebook. I just downloaded the latest source code, and build it successfully. I'm also running `etcd2` and `systemd`. 

# Reproducing
Without setting `public_ip`, I'm not sure where (and if) the socket is created. Perhaps the socket location defaults to `/var/run/fleet.sock`?

So, I'm setting `public_ip` to `unix:///var/run/fleet-socket`, something that is non-standard. 

As the logs show, it is created:
```
$ FLEET_VERBOSITY=1 FLEET_PUBLIC_IP=unix:///var/run/fleet-socket ./fleetd 
INFO fleetd.go:64: Starting fleetd version 0.11.1+git
INFO fleetd.go:168: No provided or default config file found - proceeding without
DEBUG fleetd.go:87: Creating Server
DEBUG coreos.go:37: Created CoreOSMachine with static state { unix:///var/run/fleet-socket map[] 0.11.1+git}
...
```

# The problem
But somehow, `ls /var/run/ | grep fleet` only returns a single `fleet` directory (containing a `units` directory). 

No socket to be found, so `fleetctl` hasn't got anything to connect to. 

So either this is a flaw in `fleetd`, or a flaw in the docs...

**Comment by mischief** [comment]
@EtienneBruines, fleetd is socket activated by systemd. in coreos the unit files in https://github.com/coreos/coreos-overlay/tree/master/app-admin/fleet/files are used.

**Comment by wuqixuan** [comment]
Fleetd Configuration "Public_IP"'s validation is not checked now. It will be written into the etcd, and will be got by fleetctl while doing ssh command. So the IP address should be correct. 
@EtienneBruines @mischief @bcwaldon,  what do you think ?

**Comment by mischief** [comment]
@wuqixuan it should probably be validated if it isn't already.

**Comment by mischief** [comment]
@EtienneBruines `public_ip` is an address advertised through etcd to other fleet nodes. it is not used for binding. fleetd does no socket binding of its own, and needs systemd to bind addresses (tcp, unix) for it. please see the systemd units i linked above.
