### ISSUE TITLE
Error when trying to launch multiple homogenious containers with single command

### ISSUE THREAD

**Issue by bigtree3131** [coreos/fleet#1318]
CoreOS stable (717.3.0)
fleetctl version 0.10.2
etcdctl version 2.0.10

When running:

fleetctl start myservice@{1..8}.service 

I get the following error:

Error creating units: failed creating unit myservice@i.service: googleapi: got HTTP response code 500 with body: {"error":{"code":500,"message":""}}

where i is between 1-8

However:

fleetctl start myservice@1.service
fleetctl start myservice@2.service
...
fleetctl start myservice@8.service 

works, so long as i + 1 doesn't following too soon after i

**Comment by mischief** [comment]
can you check the logs of both fleetd and etcd/etcd2?

**Comment by bigtree3131** [comment]
When launching multiple:

Jul 29 19:39:04 coreos1 fleetd[920]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb-discovery@3.service): desiredState=&job.Unit{Name:"rethinkdb-discovery@3.service", Unit:unit.UnitFile

When launching single w pass:

Jul 29 19:39:09 coreos1 fleetd[920]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=rethinkdb-discovery@3.service reason="unit currently loaded but desired state is launched"
Jul 29 19:39:09 coreos1 fleetd[920]: INFO manager.go:127: Triggered systemd unit rethinkdb-discovery@3.service start: job=8759

**Comment by mischief** [comment]
@bigtree3131 i think you're missing some stuff from the logs you pasted

**Comment by bigtree3131** [comment]
do you want the output of journalctl?

**Comment by mischief** [comment]
@bigtree3131, yes, `journalctl -b -u fleet -u etcd2` would be great.

**Comment by bigtree3131** [comment]
I think I may have found the problem -- I originally had:

etcd:
peer-heartbeat-interval: 1000
peer-election-timeout: 5000

**Comment by bigtree3131** [comment]
-- Logs begin at Thu 2015-07-30 15:35:50 UTC, end at Thu 2015-07-30 16:19:18 UTC. --
Jul 30 16:19:18 coreos2 fleetd[935]: d20)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8340)
Jul 30 16:19:18 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:19:13 coreos2 fleetd[935]: e30)}}, TargetState:""} currentState=(*job.JobState)(0xc20847f0e0)
Jul 30 16:19:13 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:19:08 coreos2 fleetd[935]: 210)}}, TargetState:""} currentState=(*job.JobState)(0xc208262620)
Jul 30 16:19:08 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:19:03 coreos2 fleetd[935]: ce0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8d80)
Jul 30 16:19:03 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:58 coreos2 fleetd[935]: 1b0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8240)
Jul 30 16:18:58 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:53 coreos2 fleetd[935]: 1d0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8d80)
Jul 30 16:18:53 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:48 coreos2 fleetd[935]: d20)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8340)
Jul 30 16:18:48 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:43 coreos2 fleetd[935]: 1d0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8f00)
Jul 30 16:18:43 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:38 coreos2 fleetd[935]: d80)}}, TargetState:""} currentState=(*job.JobState)(0xc208470f80)
Jul 30 16:18:38 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:33 coreos2 fleetd[935]: ce0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8340)
Jul 30 16:18:33 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:28 coreos2 fleetd[935]: 870)}}, TargetState:""} currentState=(*job.JobState)(0xc2080f05a0)
Jul 30 16:18:28 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:23 coreos2 fleetd[935]: e30)}}, TargetState:""} currentState=(*job.JobState)(0xc20844d740)
Jul 30 16:18:23 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:18 coreos2 fleetd[935]: 500)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8e40)
Jul 30 16:18:18 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:13 coreos2 fleetd[935]: e30)}}, TargetState:""} currentState=(*job.JobState)(0xc208446f20)
Jul 30 16:18:13 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:08 coreos2 fleetd[935]: 210)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8e20)
Jul 30 16:18:08 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:18:03 coreos2 fleetd[935]: ce0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8ea0)
Jul 30 16:18:03 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:58 coreos2 fleetd[935]: 870)}}, TargetState:""} currentState=(*job.JobState)(0xc208479000)
Jul 30 16:17:58 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:53 coreos2 fleetd[935]: e30)}}, TargetState:""} currentState=(*job.JobState)(0xc208234180)
Jul 30 16:17:53 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:48 coreos2 fleetd[935]: 500)}}, TargetState:""} currentState=(*job.JobState)(0xc20821cce0)
Jul 30 16:17:48 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:43 coreos2 fleetd[935]: dd0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a83e0)
Jul 30 16:17:43 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:38 coreos2 fleetd[935]: 210)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a86a0)
Jul 30 16:17:38 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:33 coreos2 fleetd[935]: c80)}}, TargetState:""} currentState=(*job.JobState)(0xc20845eac0)
Jul 30 16:17:33 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:28 coreos2 fleetd[935]: 150)}}, TargetState:""} currentState=(*job.JobState)(0xc208446f80)
Jul 30 16:17:28 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:23 coreos2 fleetd[935]: d10)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8c20)
Jul 30 16:17:23 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:18 coreos2 fleetd[935]: cc0)}}, TargetState:""} currentState=(*job.JobState)(0xc2080a8d20)
Jul 30 16:17:18 coreos2 fleetd[935]: ERROR reconcile.go:314: Unable to determine how to reconcile Job(rethinkdb@3.service): desiredState=&job.Unit{Name:"rethinkdb@3.service", Unit:unit.UnitFile{Contents:map[string
Jul 30 16:17:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=ReloadUnitFiles job=N/A reason="always reload unit files"
Jul 30 16:17:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=LoadUnit job=rethinkdb@3.service reason="unit scheduled here but not loaded"
Jul 30 16:17:13 coreos2 fleetd[935]: INFO manager.go:182: Instructing systemd to reload units
Jul 30 16:17:13 coreos2 fleetd[935]: INFO manager.go:246: Writing systemd unit rethinkdb@3.service (1192b)
Jul 30 16:16:15 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: cancelled
Jul 30 16:16:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=rethinkdb-discovery@3.service reason="unit currently loaded but desired state is launched"
Jul 30 16:16:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=ReloadUnitFiles job=N/A reason="always reload unit files"
Jul 30 16:16:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=LoadUnit job=rethinkdb-discovery@3.service reason="unit scheduled here but not loaded"
Jul 30 16:16:13 coreos2 fleetd[935]: INFO manager.go:127: Triggered systemd unit rethinkdb-discovery@3.service start: job=3983
Jul 30 16:16:12 coreos2 fleetd[935]: INFO manager.go:182: Instructing systemd to reload units
Jul 30 16:16:12 coreos2 fleetd[935]: INFO manager.go:246: Writing systemd unit rethinkdb-discovery@3.service (335b)
Jul 30 16:10:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:10:47 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:05:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:16:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=ReloadUnitFiles job=N/A reason="always reload unit files"
Jul 30 16:16:13 coreos2 fleetd[935]: INFO reconcile.go:330: AgentReconciler completed task: type=LoadUnit job=rethinkdb-discovery@3.service reason="unit scheduled here but not loaded"
Jul 30 16:16:13 coreos2 fleetd[935]: INFO manager.go:127: Triggered systemd unit rethinkdb-discovery@3.service start: job=3983
Jul 30 16:16:12 coreos2 fleetd[935]: INFO manager.go:182: Instructing systemd to reload units
Jul 30 16:16:12 coreos2 fleetd[935]: INFO manager.go:246: Writing systemd unit rethinkdb-discovery@3.service (335b)
Jul 30 16:10:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:10:47 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:05:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:05:47 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:00:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 16:00:47 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:55:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:55:47 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:50:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:50:47 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:45:59 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:45:46 coreos2 fleetd[935]: ERROR event.go:105: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Jul 30 15:41:01 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jul 30 15:41:01 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:41:01 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Jul 30 15:41:01 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:41:01 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: unexpected EOF
Jul 30 15:41:01 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: unexpected EOF
Jul 30 15:36:01 coreos2 fleetd[935]: INFO engine.go:79: Engine leader is dccef572fa6449f1a963fd78167ccf09
Jul 30 15:36:01 coreos2 fleetd[935]: INFO server.go:163: Starting server components
Jul 30 15:35:59 coreos2 etcd[932]: [etcd] Jul 30 15:35:59.826 INFO      | coreos2: peer added: 'coreos6'
Jul 30 15:35:59 coreos2 etcd[932]: [etcd] Jul 30 15:35:59.826 INFO      | coreos2: peer added: 'coreos4'
Jul 30 15:35:59 coreos2 etcd[932]: [etcd] Jul 30 15:35:59.825 INFO      | coreos2: peer added: 'coreos3'
Jul 30 15:35:59 coreos2 etcd[932]: [etcd] Jul 30 15:35:59.825 INFO      | coreos2: peer added: 'coreos1'
Jul 30 15:35:59 coreos2 etcd[932]: [etcd] Jul 30 15:35:59.825 INFO      | coreos2: peer added: 'coreos7'
Jul 30 15:35:59 coreos2 etcd[932]: [etcd] Jul 30 15:35:59.825 INFO      | coreos2: peer added: 'coreos5'
Jul 30 15:35:59 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Create /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 800ms
Jul 30 15:35:59 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:59 coreos2 fleetd[935]: INFO client.go:298: Response 500 Internal Server Error from http://localhost:4001/ unusable
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.826 INFO      | coreos2: state changed from 'initialized' to 'follower'.
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.826 INFO      | coreos2 starting in peer mode
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.826 INFO      | peer server [name coreos2, listen on :7001, advertised url http://10.1.40.22:7001]
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.826 INFO      | etcd server [name coreos2, listen on :4001, advertised url http://10.1.40.22:4001]
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.824 INFO      | coreos2 joined the cluster via peer 10.1.40.26:7001
Jul 30 15:35:58 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Create /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 400ms
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:58 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Create /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 200ms
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:58 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Create /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 100ms
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.250 INFO      | Send Join Request to http://10.1.40.26:7001/join
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.249 INFO      | Discovery fetched back peer list: [10.1.40.26:7001 10.1.40.21:7001 10.1.40.24:7001 10.1.40.23:7001 10.1.40.25:7001 10.1.40.27:7001]
Jul 30 15:35:58 coreos2 etcd[932]: [etcd] Jul 30 15:35:58.249 INFO      | Discovery found peers [http://10.1.40.26:7001 http://10.1.40.21:7001 http://10.1.40.24:7001 http://10.1.40.23:7001 http://10.1.40.25:7001 h
Jul 30 15:35:58 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Update /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 800ms
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:58 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:57 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Update /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 400ms
Jul 30 15:35:57 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:57 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:57 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Update /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 200ms
Jul 30 15:35:57 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:57 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:57 coreos2 etcd[932]: [etcd] Jul 30 15:35:57.486 INFO      | Discovery via https://discovery.etcd.io using prefix /eb1992b3f7744cf4ba53ee0801185fed.
Jul 30 15:35:57 coreos2 fleetd[935]: ERROR client.go:214: Unable to get result for {Update /_coreos.com/fleet/machines/836441c72f5c483aa1e268c79fb63a0f/object}, retrying in 100ms
Jul 30 15:35:57 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jul 30 15:35:57 coreos2 fleetd[935]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
Jul 30 15:35:57 coreos2 fleetd[935]: INFO server.go:152: Establishing etcd connectivity
Jul 30 15:35:57 coreos2 fleetd[935]: INFO fleet.go:160: No provided or default config file found - proceeding without
Jul 30 15:35:57 coreos2 fleetd[935]: INFO fleet.go:56: Starting fleetd version 0.10.2
Jul 30 15:35:57 coreos2 systemd[1]: Starting fleet daemon...
Jul 30 15:35:57 coreos2 systemd[1]: Started fleet daemon.
Jul 30 15:35:57 coreos2 systemd[1]: Starting etcd...
Jul 30 15:35:57 coreos2 systemd[1]: Started etcd.

**Comment by mischief** [comment]
@bigtree3131 ok, closing this issue.

fyi, it seems like fleet wants to connect to 127.0.0.1 but etcd doesn't listen there. you can set `etcd-servers` in cloud-config to tell fleet to connect to the right etcd endpoint.
