### ISSUE TITLE
Question: service scaling based on event-based monitoring

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/fleet#1320]
Is it possible for fleet to use some form of monitoring to deploy containers to machines? For example, if a HTTP connection to a service takes too long, or a remote monitoring service tells us that things are failing, then fleet knows to deploy _n_ new units for a specific service - effectively acting as scaling policies (both up and down).

If fleet doesn't support this out of the box, is there a standard way to accomplish this?

**Comment by wuqixuan** [comment]
@jamiehannaford ,
Firstly, apart from run docker container, it can run other normal service. 

Secondly, fleet is just the cluster version of systemd. Normally, it's the systemd to accomplish the local simple monitoring work, that is just to monitor whether the service is exited or not. So if need add other complex local monitor work, better modify the systemd part. 

But if systemd identified that one service is failing, fleet need get this information and move the service at another node automatically. This is the one that fleet can be enhanced. More over, fleet can implement the replica feature like kubernetes. 

As for "HTTP connection to a service takes too long", it's the SLA issue, I think fleet can not help to identify such issue. Fleet only get the status (running or failling) of service from systemd, if the SLA has issue, the status of service is still running. Systemd or fleet can not identify, maybe need another specific tool.
