### ISSUE TITLE
Incorrectly starting a unit killed the fleet agent.

### ISSUE THREAD

**Issue by grahamjenson** [coreos/fleet#1326]
I accidentally ran

`fleetctl start service_name@.service` (instead of `service_name@1.service`)

This caused this error to occur and stop the fleet agent working:

`ERROR reconcile.go:79: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name service_name@.service is not valid.`

This stopped running any units on this machine.

`fleetctl destroy service_name@.service` did nothing, probably because the agent wasn't running.

My workaround fix was to just delete the unit file:

`sudo rm /run/fleet/units/service_name@.service`

Probably not the best idea, but it worked.

**Comment by mischief** [comment]
@grahamjenson this problem is actually fixed in fleetd as of a0667c150da5760f378b21dcfc1e2a37aecdb324. it will be in coreos soon.

**Comment by grahamjenson** [comment]
@mischief Awesome cheers

**Comment by mischief** [comment]
@grahamjenson fleet 0.11.4 is in alpha now, and the fleetd server api will prevent starting templates.
