### ISSUE TITLE
fleet won't talk to etcd2 on boot

### ISSUE THREAD

**Issue by vaijab** [coreos/fleet#1329]
Fleet will just get stuck on a reboot and will not connect to etcd2 running on https://localhost:2379.

5 etcd2 master nodes with 5 etcd2 proxy nodes.

* etcd v2.1.1
* fleet 0.11.4
* coreos 774.0

As you can see in the logs below, fleet service gets started, but it does not emit any errors. At this point fleet is stuck and we'll need a service restart.

```
-- Reboot --
Aug 15 01:06:19 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: Started fleet daemon.
Aug 15 01:06:19 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: Starting fleet daemon...
Aug 15 01:06:20 ip-10-50-1-238.eu-west-1.compute.internal fleetd[538]: INFO fleetd.go:64: Starting fleetd version 0.11.4
Aug 15 01:06:20 ip-10-50-1-238.eu-west-1.compute.internal fleetd[538]: INFO fleetd.go:168: No provided or default config file found - proceeding without
Aug 15 01:06:20 ip-10-50-1-238.eu-west-1.compute.internal fleetd[538]: INFO server.go:157: Establishing etcd connectivity
```

Issuing `systemctl restart fleet.service`.

```
Aug 15 01:06:24 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: Started fleet daemon.
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: Stopping fleet daemon...
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: fleet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: fleet.service: Unit entered failed state.
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: fleet.service: Failed with result 'exit-code'.
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: Started fleet daemon.
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal systemd[1]: Starting fleet daemon...
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO fleetd.go:64: Starting fleetd version 0.11.4
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO fleetd.go:168: No provided or default config file found - proceeding without
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO server.go:157: Establishing etcd connectivity
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO server.go:168: Starting server components
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO engine.go:79: Engine leader is c60f1d15c68549bea097d64da8f910f9
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:246: Writing systemd unit kube-apiproxy.service (318b)
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:246: Writing systemd unit kube-kubelet.service (683b)
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:246: Writing systemd unit kube-proxy.service (519b)
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:182: Instructing systemd to reload units
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:127: Triggered systemd unit kube-apiproxy.service start: job=266425
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:127: Triggered systemd unit kube-kubelet.service start: job=266510
Aug 17 09:00:48 ip-10-50-1-238.eu-west-1.compute.internal fleetd[29612]: INFO manager.go:127: Triggered systemd unit kube-proxy.service start: job=266598
```

**Comment by vaijab** [comment]
Just updated above to say that fleet fails to talk to etcd2 running in either proxy or master mode.

**Comment by mischief** [comment]
@vaijab can you provide cloud-configs for the etcd2 master and the proxy nodes? i can't reproduce this in a simple test case with one etcd2 master and one etcd2 proxy, and starting a fleet unit through the proxy.

**Comment by vaijab** [comment]
@mischief I can I suppose, but it would be quite difficult to use that in your environment. What I noticed is that etcd2 fails to start (due to some `ExecStartPre` statement I added) initially, then fleet.service gets started and right after that etcd2.service starts, but fleet is already stuck in a loop and never tries to connect to etcd2 again.

**Comment by mischief** [comment]
what else is going on besides etcd2/fleet?

one thing you might look for is any services accidentally depending on *etcd.service*, which conflicts with *etcd2.service*.

**Comment by vaijab** [comment]
@mischief fleet seems to be stuck in this loop: https://github.com/coreos/fleet/blob/master/server/server.go#L160-L166

**Comment by mischief** [comment]
@vaijab so, fleet can't talk to etcd. check that your etcd client listen urls, and fleet's etcd urls are in sync.

**Comment by vaijab** [comment]
@mischief they are in sync. I cannot reproduce this in vagrant. There must be some weird race condition in my setup. I will update this issue if I figure it out.

**Comment by wuqixuan** [comment]
Seems like this issue is a problem of etcd service. It's nothing about fleet.

**Comment by wuqixuan** [comment]
@vaijab @mischief 
This issue seems like etcd2 is not there. So fleet cannot connect it. I think this PR can be closed. What do you think ?

**Comment by vaijab** [comment]
@wuqixuan you might be correct by saying that etcd2 is not available. But fleet should try to reconnect to etcd2 when it becomes available.

**Comment by wuqixuan** [comment]
@vaijab， I have tested the case you said with the same version. But cannot reproduce the problem. 

First I run fleet service, it get stuck 
```
localhost fleet-v0.11.4-linux-amd64 # ./fleetd -config=/etc/fleet/fleet.conf &
[1] 801
localhost fleet-v0.11.4-linux-amd64 # INFO fleetd.go:64: Starting fleetd version 0.11.4 
INFO fleetd.go:161: Using provided config file /etc/fleet/fleet.conf
INFO server.go:157: Establishing etcd connectivity

localhost fleet-v0.11.4-linux-amd64 #
```

Then I run the etcd2: 
```
localhost etcd-v2.1.1-linux-amd64 # ./etcd -name infra0 -initial-advertise-peer-urls http://192.168.122.30:2380 -listen-peer-urls http://192.168.122.30:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster infra0=http://192.168.122.30:2380  -initial-cluster-state new --listen-client-urls http://192.168.122.30:2379 -advertise-client-urls http://192.168.122.30:2379 &
[1] 806
```

Then fleet service connects etcd2 successfully.  
```
localhost fleet-v0.11.4-linux-amd64 # INFO fleetd.go:64: Starting fleetd version 0.11.4
INFO fleetd.go:161: Using provided config file /etc/fleet/fleet.conf
INFO server.go:157: Establishing etcd connectivity

localhost fleet-v0.11.4-linux-amd64 #
localhost fleet-v0.11.4-linux-amd64 #
localhost fleet-v0.11.4-linux-amd64 #
localhost fleet-v0.11.4-linux-amd64 # INFO server.go:168: Starting server components
ERROR engine.go:217: Engine leadership lost, renewal failed: 100: Key not found (/_coreos.com/fleet/lease/engine-leader) [235]
INFO engine.go:185: Engine leadership acquired
```

I tested when I configure the wrong IP address of etcd2 in fleet.conf, fleet service cannot reconnect etcd2 when it becomes available. So I guess, the fleet servicd conf file may be wrong. 
Can you provide more information?

**Comment by vaijab** [comment]
@wuqixuan thanks for looking into this. I cannot easily reproduce this issue in vagrant. I worked around this problem by adding additional `Requires=` lines to fleet unit file.

I am going to close this issue for now. I will reopen that if I find a way to reproduce the problem easily.
