### ISSUE TITLE
fleetctl uses /root/.ssh while remote machine uses /home/core/.ssh for finding public keys

### ISSUE THREAD

**Issue by twanies** [coreos/fleet#1330]
Hi, 

We have a 3 node CoreOS cluster running and i start experimenting with auto deployment. I am trying to clone a repo in a execStartPre directive like:
`execStartPre=/usr/bin/git clone git@github.com:some/repo.git /tmp/app`

Every time i start the service i get an authentication failed. If i use this snippet `git clone git@github.com:some/repo.git` manually on the CoreOS remote it works perfectly.

After debugging i saw that the fleet client on the remote uses /root/.ssh instead /home/core/.ssh as its directory for looking up keys.

Any idea how to fix this issue?

**Comment by robszumski** [comment]
You can change the user that runs the unit with User=core or User=root. Can you try that and see if it fixes your issue?

**Comment by twanies** [comment]
@robszumski Thanx this solved the issue for me!
