### ISSUE TITLE
fleetctl list-machines doesn't list all machines but fleet and cluster are perfectly working

### ISSUE THREAD

**Issue by skjorrface** [coreos/fleet#1346]
Hi everybody. I've installed and configured a cluster of 4 nodes in my server and everything is just working perfectly except "fleetctl list-machines", which only displays two machines in the list instead of 4: whenever I run this command from any node I only can see the IP of the current node and another IP (of another machine) which is always the same from any other node. How can that happen and how can I fix that? I'm using coreos-stable, etcd and fleet version 0.10.2. P.S. if I run etcdctl cluster-health I repeat I get all the four nodes and if I run a unit it runs on all 4 the nodes.

**Comment by jonboulle** [comment]
@skjorrface typically when we've seen this in the past it's because people
have duplicate machine IDs in the cluster; could you start by confirming
that they're different on each of the machines? /etc/machine-id

**Comment by skjorrface** [comment]
Oh my god. You're right! They're the same! How do I change them?

**Comment by jonboulle** [comment]
@skjorrface the easiest way is just to remove the /etc/machine-id file and
reboot the system - it'll automatically generate a new one at boot time
(alternatively you can manually run `systemd-machine-id-setup` but it's
best to reboot to ensure everything initialises with the new id)

Would I be right in guessing that some of these are cloned VMs? generally
that's not advisable for this exact reason - each system should have a
unique machine-id.

**Comment by skjorrface** [comment]
Yes. they were cloned vms! I just regenerated SMBIOS and everything works like a charm now! Thank you very for your precious advice!

**Comment by jonboulle** [comment]
great! no problem, glad it worked out
