### ISSUE TITLE
Services quit shortly after they started

### ISSUE THREAD

**Issue by ianbytchek** [coreos/fleet#1357]
Having a really bad time with fleet while trying to start a service with a sidekick. The main service launches a docker container, it stays up for 10 seconds and then quits. Same happens with the sidekick. To narrow this down I separated both of them, but that didn't help.

```ini
[Unit]

Description=App (%i release) service.

Requires=etcd2.service
Requires=docker.service

After=etcd2.service
After=docker.service

[Service]

# Let processes take awhile to start up (for first run Docker containers)

TimeoutStartSec=0

# Change killmode from "control-group" to "none" to let Docker remove work correctly.

KillMode=none

# Get CoreOS environmental variables.

EnvironmentFile=/etc/environment

ExecStartPre=-/usr/bin/docker rm --force app-%i
ExecStart=/usr/bin/docker run --detach --name app-%i --publish-all app/app:%i

ExecStop=/usr/bin/docker stop app-%i

[X-Fleet]

Conflicts=app@%i.service
```

It launches the container but after ~10 seconds it stops. If I manually start it again it works as expected without quitting. Journal doesn't show any issues either.

```
Sep 24 11:43:30 ip-10-2-1-220.eu-central-1.compute.internal systemd[1]: Starting App (5ef1410 release) service....
Sep 24 11:43:30 ip-10-2-1-220.eu-central-1.compute.internal docker[2489]: app-5ef1410
Sep 24 11:43:30 ip-10-2-1-220.eu-central-1.compute.internal systemd[1]: Started App (5ef1410 release) service..
Sep 24 11:43:30 ip-10-2-1-220.eu-central-1.compute.internal docker[2497]: ed99831e4ab18d1f24829769054fb87839c971ba07d51dd3f964e6a262e8f569
Sep 24 11:43:41 ip-10-2-1-220.eu-central-1.compute.internal docker[2561]: app-5ef1410
```

I've tried this on stable, beta and alpha CoreOS releases. Where am I going wrong?

**Comment by robszumski** [comment]
Don't run your container detached. systemd needs to be able to introspect the status of the ExecStart line. In this case, the 10 seconds is docker pulling/setting up the container and then forking it into the background. systemd says "looks like the process has exited" and the unit stops.

**Comment by ianbytchek** [comment]
@robszumski thanks man! I've re-read the docs, that's right in there. It can help a lot to others like me to have this information in a fat yellow box with red border :smile: it feels it's understated a little a lot.
