### ISSUE TITLE
Using systemd perhaps not a good choice?

### ISSUE THREAD

**Issue by jaroslavl1** [coreos/fleet#1358]
We are using coreos & fleet & docker in our project and I'm starting to have opinion that using systemd for fleet/coreos was not a very good choice.

systemd is fine when managing services on a single linux machine, but when you go to cluster you may want more features:
1. install/uninstall support, not just start/stop. In install you would typically check if docker image/container already exists and download if not. In start you would merely have docker start. So then when accidental service crash occurs or coreos gets restarted just the "docker start" gets executed. Then when you decide to do fleet destroy you would like the uninstall section to execute and remove docker container & image (if not used multiple times). Install/uninstall concept is currently missing in systemd/fleet leading to various workarounds - you do docker kill/rm/pull in ExecStartPre which is however also executed during accidental service crash or coreos restart. So if you have very simple demo service which (is stupid and) stores data in the docker container itself everything gets deleted during start. In better case the service perhaps just gets upgraded after crash because you use :latest tag (not production env...). Things like docker rm/pull do not belong to ExecStartPre or ExecStart. If you use docker volume containers then these would normally only use install/uninstall since they don't really execute. Start/stop is meaningless for them. Trying to use the current systemd ExecStartPre/ExecStart can be quite dangerous since data could get deleted.
2. service upgrade support. Currently after fleet stop/destroy/submit/start service migrates to other machine. Here you would want it to stay on the same machine out of the box. Upgrade could perhaps execute stop, uninstall, install (with new version decided somehow), start and do this gradually over each node where service is running. It may seem that service upgrade is possible without the point 1. being supported but it will be unnatural.

It would be nice if https://coreos.com/fleet/docs/latest/launching-containers-fleet.html also contained some more realistic example using the best you can get from current systemd limitations and not get side effects like I named in point 1. This means using docker start/stop in ExecStart/ExecStop (and not docker run) and using "docker pull", "docker create" in ExecStartPre first checking if it already exists, so something like this:
ExecStartPre=/bin/bash -a -c '/usr/bin/docker inspect yourcontainername > /dev/null || /usr/bin/docker pull yourimagename && /usr/bin/docker create --name yourcontainername yourimagename'
ExecStart=/usr/bin/docker start yourcontainername
ExecStop=/usr/bin/docker stop yourcontainername

To me it seems either additional features in systemd are needed or fleet & coreos should use another init (custom?) daemon that is perhaps not so complicated but supports exactly what is needed for cluster deployment.

**Comment by robszumski** [comment]
The real answer here is to use a runtime that integrates well with systemd. This is why we built rkt.

Here is a quick getting started guide for using [rkt with systemd](https://coreos.com/rkt/docs/latest/using-rkt-with-systemd.html). You can run your docker containers with rkt like this:

```
/usr/bin/rkt --insecure-skip-verify run docker://redis
```

**Comment by jaroslavl1** [comment]
It may be interesting to readers that there are much more problems with Docker integration in Systemd than what I have described. Fleet developers are most likely already aware of these problems:

https://github.com/docker/docker/issues/6791
https://github.com/ibuildthecloud/systemd-docker

Basically the whole thing is incompatible with it. Sadly rkt is considered still to be very young so its preferred to use Docker for now.

**Comment by jaroslavl1** [comment]
Also interesting discussion here https://groups.google.com/forum/#!topic/coreos-dev/wf7G6rA7Bf4/discussion

**Comment by jonboulle** [comment]
For better or worse (obviously at CoreOS we feel strongly about the "better"), systemd is going to be **the**  init system on the vast majority of Linux deployments - it's already been adopted by all of the major distributions. Yes, it will take a while for the world to completely shift, and there are a number of teething problems as you've pointed out. But we are confident that is the future of managing services on Linux, that it provides a solid architectural base, and that solutions to all such teething problems will emerge. rkt is also moving quickly towards a production-ready state and I would encourage you to try it out as it already integrates very cleanly with systemd and CoreOS.

If your primary concern is running a cluster of Docker containers, I would recommend you explore running [Kubernetes on CoreOS](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos.md)
