### ISSUE TITLE
Different bash variable syntax inside embedded service script

### ISSUE THREAD

**Issue by ianbytchek** [coreos/fleet#1359]
I have a really odd question, hope that's not overlooked documentation. Wtf happens here? Why `${}` syntax works on `COREOS_PRIVATE_IPV4` but not on `FOO`? :flushed:

```ini
ExecStart = /bin/bash -c '\
            while true; do \
                FOO="bar"; \
                echo "foo is $COREOS_PRIVATE_IPV4:$FOO"; \
                echo "foo is ${COREOS_PRIVATE_IPV4}:${FOO}"; \
                sleep 10; \
            done'
```

```log
Sep 25 06:20:21 … bash[17136]: foo is 10.2.1.220:bar
Sep 25 06:20:21 … bash[17136]: foo is 10.2.1.220:
```

**Comment by crawford** [comment]
systemd also does variable expansion. It is expanding `COREOS_PRIVATE_IPV4` and `FOO`, but `FOO` is empty in systemd's context. You can escape the variable with an additional `$`.

```ini
ExecStart = /bin/bash -c '\
            while true; do \
                FOO="bar"; \
                echo "foo is ${COREOS_PRIVATE_IPV4}:$${FOO}"; \
                sleep 10; \
            done'
```

**Comment by ianbytchek** [comment]
I see, I see… I did read about escaping `$` with `$` but didn't figure it out without an example. Thanks man!
