### ISSUE TITLE
Provide a way of getting current machine id

### ISSUE THREAD

**Issue by ianbytchek** [coreos/fleet#1365]
I might be missing something obvious or is this not implemented / documented? I want to launch a unit on the current machine, I've figured the best option is to use `MachineID`, yet, there seems to be no way of finding the current machine id via fleet nor etcd. The only option would be using metadata, but thats an overkill…

**Comment by crawford** [comment]
You can use the "%m" [specifier](http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers) in your unit file.

**Comment by ianbytchek** [comment]
I knew it must be there :angry:

**Comment by ianbytchek** [comment]
I think I closed this too early, it still seems like it would be useful to be able to get machine id directly from fleet. [systemd/man/machine-id.html](http://www.freedesktop.org/software/systemd/man/machine-id.html) says that systemd stores it inside `/etc/machine-id`, which is fairly easy to get by printing the contents of the file. But wouldn't it be more consistent / convenient to have this command inside fleet? Or is it not used that often?

**Comment by mischief** [comment]
is this not sufficient?

```
mischief@delta ~ $ fleetctl list-machines -l | awk '{ print $1 }'
MACHINE
441101b5e14a8f40a98401732a6cd840
8636d9aff3933f48b95ad94891cd1839
d0f2a92c271c984c80e61c974d9908aa
mischief@delta ~ $ fleetctl ssh 441101b5e14a8f40a98401732a6cd840 cat /etc/machine-id
441101b5e14a8f40a98401732a6cd840
mischief@delta ~ $ 
```

**Comment by ianbytchek** [comment]
It is, it definitely works as is. Just was wondering whether it would be a good idea adding this to the fleetctl itself? Feel free to close this. Any chance of you having a look into #1364? It's kind of related.
