### ISSUE TITLE
systemd --user

### ISSUE THREAD

**Issue by kiro** [coreos/fleet#1370]
Hi, is it possible to make fleet talk to systemd --user instance?

**Comment by jonboulle** [comment]
Not right now as we just talk directly to systemd:
https://github.com/coreos/fleet/blob/3178aed8de27b757af6b8c3a89b970ec98156a5e/systemd/manager.go#L44
https://github.com/coreos/go-systemd/blob/0020698a980adf8a2c440d9be709edc85b54544a/dbus/dbus.go#L86

and write unit files into a non-configurable directory: https://github.com/coreos/fleet/blob/3178aed8de27b757af6b8c3a89b970ec98156a5e/server/server.go#L70

At a glance this might be relatively easy to change, so feel free to submit a PR if this is a feature you're interested in.

**Comment by hmalphettes** [comment]
Here is a PR for that: https://github.com/coreos/fleet/pull/1393

**Comment by dongsupark** [comment]
Closed via https://github.com/coreos/fleet/pull/1393. Thanks.
