### ISSUE TITLE
Invalid escape sequences in command line

### ISSUE THREAD

**Issue by ianbytchek** [coreos/fleet#1373]
I know there's a recent #1367 and probably a few more similar issues. But I'm observing a strange behaviour, my unit is working totally fine for hours and then eventually fails with invalid escape sequences in command.

```sh
[/run/fleet/units/foo-discovery-node01@16e5d00.service:11] Invalid escape sequences in command line: "/usr/bin/bash -c 'set -euo pipefail; container=\'foo-%i\'; directory=\'/service/foo/\'; while true; do port_check=false; curl_check=false; ip="$${COREOS_PRIVATE_IPV4}"; key=$$(echo \'%p\' | pcregrep -o \'\w*$$\')\'-%i\'; port=$$(docker inspect --format \'{{ index .NetworkSettings.Ports "80/tcp" 0 "HostPort" }}\' "$${container}") && :; [ $$? == 0 ] && port_check=true; if "$${port_check}"; then host="$${ip}:$${port}"; curl --fail --max-time 1 --silent "$${host}" &> /dev/null && :; [ $$? == 0 ] && curl_check=true; fi; if "$${curl_check}"; then etcdctl set "$${directory}/$${key}" "$${host}" --ttl 20; echo "Succesfully connected to foo container, adding service into discovery."; else etcdctl rm "$${directory}/$${key}" &> /dev/null && :; echo "Failed connecting to foo container, removing service from discovery."; fi; sleep 10; done;'"
```

The unit looks like this.

```systemd
[Unit]
Description=foo (%i release) etcd discovery service.
Requires=etcd2.service
Requires=foo-node01@%i.service
After=etcd2.service
After=foo-node01@%i.service
BindsTo=foo-node01@%i.service

[Service]
EnvironmentFile=/etc/environment
ExecStart=/usr/bin/bash -c 'set -euo pipefail; container=\'foo-%i\'; directory=\'/service/foo/\'; while true; do port_check=false; curl_check=false; ip="$${COREOS_PRIVATE_IPV4}"; key=$$(echo \'%p\' | pcregrep -o \'\w*$$\')\'-%i\'; port=$$(docker inspect --format \'{{ index .NetworkSettings.Ports "80/tcp" 0 "HostPort" }}\' "$${container}") && :; [ $$? == 0 ] && port_check=true; if "$${port_check}"; then host="$${ip}:$${port}"; curl --fail --max-time 1 --silent "$${host}" &> /dev/null && :; [ $$? == 0 ] && curl_check=true; fi; if "$${curl_check}"; then etcdctl set "$${directory}/$${key}" "$${host}" --ttl 20; echo "Succesfully connected to foo container, adding service into discovery."; else etcdctl rm "$${directory}/$${key}" &> /dev/null && :; echo "Failed connecting to foo container, removing service from discovery."; fi; sleep 10; done;'
ExecStop=/usr/bin/etcdctl rm "/service/foo/%i/${COREOS_PRIVATE_IPV4}"

[X-Fleet]
MachineID=a7825d64b3ba4526858d6e599437c684
```

The command gets escaped and embedded into the unit file automatically when it gets deployed. Originally it looks like this.

```sh
set -euo pipefail

container='foo-%i'
directory='/service/foo/'

while true; do
    port_check=false
    curl_check=false

    ip="${COREOS_PRIVATE_IPV4}"
    key=$(echo '%p' | pcregrep -o '\w*$')'-%i'

    port=$(docker inspect --format '{{ index .NetworkSettings.Ports "80/tcp" 0 "HostPort" }}' "${container}") && :
    [ $? == 0 ] && port_check=true

    if "${port_check}"; then
        host="${ip}:${port}"

        curl --fail --max-time 1 --silent "${host}" &> /dev/null && :
        [ $? == 0 ] && curl_check=true
    fi

    if "${curl_check}"; then
        etcdctl set "${directory}/${key}" "${host}" --ttl 20
        echo "Succesfully connected to foo container, adding service into discovery."
    else
        etcdctl rm "${directory}/${key}" &> /dev/null && :
        echo "Failed connecting to foo container, removing service from discovery."
    fi

    sleep 10
done
```

I don't want to deploy a separate script to the host and then call it within unit file, this would make things more complicated for me eventually.

Is there any clue what's going wrong? Also, can you consider adding some sort of debugging / hints for such errors, i.e., point out where exactly bad escape sequence is found? This would be near to invaluable feature.

**Comment by jonboulle** [comment]
On Mon, Oct 12, 2015 at 12:49 AM, Ian Bytchek <notifications@github.com>
wrote:

> I know there's a recent #1367
> <https://github.com/coreos/fleet/issues/1367> and probably a few more
> similar issues. But I'm observing a strange behaviour, my unit is working
> totally fine for hours and then eventually fails with invalid escape
> sequences in command.
>
that is very strange - no hint as to what changes around the time of
failure? Is it getting rescheduled to a different machine? is the state of
the unit otherwise changing? etc.
I'd be curious to know if there's any difference after applying
https://github.com/coreos/fleet/pull/1375 as that changes the way we parse
unit files a bit (specifically, it stops transforming them as we are doing
today)

> Is there any clue what's going wrong? Also, can you consider adding some
> sort of debugging / hints for such errors, i.e., point out where exactly
> bad escape sequence is found? This would be near to invaluable feature.
>
Unfortunately this error message is from systemd, not us, so it's a little
out of our control (although feel free to file it upstream @
github.com/systemd/systemd - I agree it would be useful)

**Comment by ianbytchek** [comment]
> that is very strange - no hint as to what changes around the time of
failure? Is it getting rescheduled to a different machine? is the state of
the unit otherwise changing? etc.

Nope, it's just been out there for a while and then I see this in the logs.

Yep, I'll file an issue there. Seems like the best way forward.
