### ISSUE TITLE
Question: start service with IP-address

### ISSUE THREAD

**Issue by QIvan** [coreos/fleet#1389]
Hi, everyone! 
Is there way to start my service on machine with concrete IP-address? Is it possible only with MachineID or there are other ways?  Something like: 
```javascript
MachineIP=10.0.0.1
```
or even: 
```javascript
MachineIP=192.168.0.0/16
```

Thanks!

**Comment by kayrus** [comment]
@QIvan You can define metadata for fleet daemon using cloud-config:

```yaml
#cloud-config
coreos:
  fleet:
    metadata: "MachineIP=%your_ip_address_here%"
```

Which will generate this systemd [drop-in](https://github.com/coreos/docs/blob/master/os/using-systemd-drop-in-units.md):

`/run/systemd/system/fleet.service.d/20-cloudinit.conf`

```ini
[Service]                                                                                                               
Environment="FLEET_METADATA=MachineIP=%your_ip_address_here%"
```

And then, inside unit file which you would like to schedule just specify this metadata:

```ini
[X-Fleet]
MachineMetadata=MachineIP=%your_ip_address_here%
```
