### ISSUE TITLE
Support templates with some of systemd units

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1390]
Following unit types don't support templates

* automount
* busname
* device
* mount
* scope
* slice
* snapshot
* swap

We can fix that in systemd code. I suppose changing [this string](https://github.com/systemd/systemd/blob/c386f5886466de6022b3b4b1c8ac8df72871fbc7/src/core/mount.c#L1832) should solve at least `*.mount` units. I like this idea as it will add additional flexibility for fleet. But potentially it could case security risks.

Other solution - is to reject such unit files at fleet side. This is most simple solution but it will not increase fleet flexibility.

/cc @antrik @philips @crawford 

relates to https://github.com/coreos/fleet/issues/303 and https://github.com/coreos/fleet/issues/1194

**Comment by mrl045** [comment]
I would appreciate it when these templates will be available in fleet.

**Comment by dongsupark** [comment]
Apparently it's not that simple to support templates for mount units on the systemd side, according to https://github.com/systemd/systemd/issues/2556#issuecomment-211484263.
I'll create a PR for fleet, to reject template units for the particular unit types, until systemd could somehow manage to support templates for them.
