### ISSUE TITLE
fleet server unable to communicate with etcd

### ISSUE THREAD

**Issue by chusson** [coreos/fleet#1392]
Hello everybody,

I've a problem with the cluster

Here my cloud-config for my 3 VM

http://pastebin.com/XHJYCXHu

I don't know why, but i think i've followed the documentation (i'm new with CoreOS), but cluster won't work. 

```
core@srv1 ~ $ fleetctl list-machines
   Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with        etcd

core@srv1 ~ $ journalctl -u fleet -r -l
Nov 19 15:23:30 srv1.coreos fleetd[679]: ERROR client.go:214: Unable to get result for {Create /_coreos.com/fleet/machines/6b9cf1bff90348a18ebaa8b49a044650/object}, retrying in 800ms
Nov 19 15:23:30 srv1.coreos fleetd[679]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Nov 19 15:23:30 srv1.coreos fleetd[679]: INFO client.go:292: Failed getting response from http://localhost:4001/: dial tcp 127.0.0.1:4001: connection refused
```

If somebody can help me, i would be very nice :)

Nice day and thanks for you work !

**Comment by kayrus** [comment]
@chusson your configuration contains two etcd: `etcd` and `etcd2`. You have to use only `etcd2`. Also please pay attention that `$private_ipv4` substitution is available only in selected cloud providers.
