### ISSUE TITLE
New fleet-specific Option "Replaces" (feature)

### ISSUE THREAD

**Issue by onlyjob** [coreos/fleet#1394]
Using Fleet I'm trying to implement high-availability solution for a certain daemon which does  master-slave replication. There are two instances - "master" and "shadow master". When "master" is down, "shadow master" can be promoted to "master" which is trivial to implement with Fleet. However the problem that is difficult to solve is re-starting "shadow master" somewhere else after "shadow master" to "master" fail-over. 

A new fleet-specific option "Replaces" could be helpful in this scenario. Unlike stronger "Conflicts", I suppose "Replaces" could force re-scheduling of another unit to another machine. For example, "master.service" could contain

    [X-Fleet]
    Replaces=shadow.service

so when "master.service" is started on machine where "shadow.service" is running the latter is stopped and automatically re-scheduled to run on another machine.

I hope that such option can be considered useful.

**Comment by scipetr** [comment]
+1

**Comment by antrik** [comment]
I suggest calling it "Displaces": I think that would make it much clearer what it does...

Regarding the functionality, I guess it should work pretty much like "Conflicts", except that it is directional -- i.e. it's always the "displaced" unit that gets moved, never the "displacing" one?

**Comment by kayrus** [comment]
What about taking RPM's dependency name? [Obsoletes](http://www.rpm.org/wiki/PackagerDocs/Dependencies#Obsoletes)

**Comment by kayrus** [comment]
@onlyjob what if `shadow.service` will contain:

```ini
[X-Fleet]
Replaces=master.service
```

How would fleet handle that? Weights? But weights should be implemented by the clustered software itself like it's done in [keepalived](http://www.keepalived.org/LVS-NAT-Keepalived-HOWTO.html).

The workaround for the current fleet version is to combine systemd's [`ExecStartPre=`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=) and [`StartTimeout=0`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStartSec=) inside global master unit and [sidekick](https://coreos.com/fleet/docs/latest/examples/service-discovery.html) for them.

You'll have to implement health check logic using script which will check etcd registry and set keys with the TTL.

ExecStartPre will not allow unit to start until etcd slot is empty. If slot is empty, systemd will start the unit with sidekick. Sidekick will update key's TTL every second.

**Comment by antrik** [comment]
@kayrus well, if my reasoning is correct about Displaces being a directional Conflicts, then mutual Displaces would effectively be identical to a regular Conflicts I guess...

Of course there is no reason to use Displaces in this case at all. Not sure why you are suggesting this scenario?...

**Comment by antrik** [comment]
@kayrus I can't say that I really understand the "workaround" you proposed -- but since you call it a workaround, I guess you don't consider it a proper solution? Or do you think it should be good enough and there is no need for new functionality here?...

**Comment by kayrus** [comment]
@antrik it will be better if you explain in details future fleet logic which will cover this enhancement. I suspect there could be hidden pitfalls.

**Comment by antrik** [comment]
The thing is, to get a reasonable understanding of the specifics, I'd already have to dig deep into the code, and think through most of the implementation... I for my part wouldn't mind doing this -- but if there is already so much doubt up front whether this is something that should be implemented at all, I wonder whether it would be considered good use of development resources?

**Comment by kayrus** [comment]
@antrik I don't mind if you will implement this logic.
