### ISSUE TITLE
destroy command doesn't gracefully stop units if they were ran

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1400]
I suppose we have to stop them gracefully (exec runStopUnit first then destroy).
https://github.com/coreos/fleet/blob/master/fleetctl/destroy.go#L38

**Comment by jonboulle** [comment]
can you elaborate on what the issue is here? We do actually stop units before removin them: https://github.com/coreos/fleet/blob/3178aed8de27b757af6b8c3a89b970ec98156a5e/agent/agent.go#L101

**Comment by kayrus** [comment]
https://github.com/coreos/fleet/blob/master/fleetctl/destroy.go#L38 - doesn't contain unload.

**Comment by jonboulle** [comment]
Why should it? That is an API call. fleet is declarative, not procedural.
The API unloads the unit from the registry, then the fleet agent performs
the actual unload at the host level. The agent knows to stop the unit
before unloading it from systemd.

**Comment by arthur-c** [comment]
Kayrus opened this issue after I talked on irc about a problem I encountered with fleetctl. I saw several times units destroyed without their docker stopped. Now I ensure to stop a unit before destroying it and it doesn't happen anymore. My ExecStop are not fancy (ExecStop=/usr/bin/docker stop %p) and they never failed with fleetctl stop.

**Comment by guilhem** [comment]
I can agree with @arthur-c , unit destroyed aren't "stopped".

This is a huge problem when stop commands are some kind of cleanup tasks.

**Comment by jonboulle** [comment]
@kayrus can you come up with a reproducing case here + dig into the logs to find out what's going on?

**Comment by kayrus** [comment]
@arthur-c @guilhem could you provide problem unit file contents?

**Comment by kayrus** [comment]
dup: https://github.com/coreos/fleet/issues/1000

**Comment by jonboulle** [comment]
ah! thought this looked familiar, let's chase it in there
