### ISSUE TITLE
docs: clarify out-of-scope use cases for fleet

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#1405]
In the README we have a [very brief comment about what fleet should not be used for](https://github.com/coreos/fleet/blame/master/README.md#L7), and then a longer [description of supported usage patterns](https://github.com/coreos/fleet/blame/master/README.md#L44). We should go one step further and probably introduce an explicit list of common use cases that fleet does not cover (e.g. "what fleet is for", "what fleet is not for"). At the same time we could point people towards other projects like Kubernetes where appropriate for specific use cases.

**Comment by jonboulle** [comment]
@joshix you on this?

**Comment by joshix** [comment]
@jonboulle My knowledge is weaker [even than usual] on this. This should probably go to someone else, unless we are ok waiting for me to have time to learn the subject firsthand after 2/19.
