### ISSUE TITLE
Increase fleet security

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1407]
There are two pull request in related coreos repos:
~~https://github.com/coreos/baselayout/pull/38~~
https://github.com/coreos/coreos-overlay/pull/1579

/cc @tixxdz @jonboulle can you review these changes?

**Comment by tixxdz** [comment]
Security notes were written in this https://github.com/coreos/fleet/pull/1427

**Comment by jonboulle** [comment]
Blocked on coreos-overlay.

**Comment by kayrus** [comment]
@jonboulle https://github.com/coreos/coreos-overlay/pull/1579 merged
all dependencies resolved.

**Comment by jonboulle** [comment]
SGTM
