### ISSUE TITLE
fleet downloads should be signed with gpg

### ISSUE THREAD

**Issue by blalor** [coreos/fleet#1408]
Is this something you could embrace going forward?

**Comment by jonboulle** [comment]
We definitely want to do this, will take the same approach for all CoreOS projects.

**Comment by dongsupark** [comment]
I have been aware that this PR was marked as v1.0, but I'm not sure if it's possible at all to get the gpg key.
If that's possible, should we also update release scripts as well as documents?
If that's not the case, we should probably exclude this PR from v1.0.

**Comment by dongsupark** [comment]
Update: It is possible to get the gpg key, according to offline discussion with @jonboulle. It's good news.

**Comment by jonboulle** [comment]
Addressed in #1718
