### ISSUE TITLE
fleetctl submit/start for more than 5 units at a time fails

### ISSUE THREAD

**Issue by r0p0s3c** [coreos/fleet#1425]
When invoking fleetctl as:

`$ fleetctl --tunnel 54.191.250.126 submit 1.service ... 6.service`

with more than 5 units, I get 
`Error creating units: failed creating unit a.service: Put http://domain-sock/fleet/v1/units/6.service?alt=json: ssh: rejected: administratively prohibited (open failed)`

This same error occurs whether the operation is submit, start, or load, but destroy with many services appears to work

**Comment by kayrus** [comment]
relates to https://github.com/coreos/fleet/issues/1352

**Comment by kayrus** [comment]
Have reproduced the issue. It related to `fleetctl fd-forward` proxy and somehow to ssh limits. Need more time investigate it.

**Comment by kayrus** [comment]
Looks like that on any failed request fleetd closes the socket. Closed socket terminates fleetctl fd-forward /var/run/fleet.sock, but fleet doesn't know about that and still tries to send data to ssh.

possible solution is fix `fleetctl fd-forward` to work in forever loop like it is done [here](https://github.com/coreos/sdnotify-proxy/blob/master/main.go#L119). Didn't manage yet how to interrupt goroutine.

**Comment by kayrus** [comment]
It turned out that it is not a reason. Still investigating.

**Comment by kayrus** [comment]
The actual reason was multiple "auth-agent-req@openssh.com" requests, which is not supported by SSH daemon. Had to add additional check whether request was sent or not.

**Comment by kayrus** [comment]
Similar issue in python's paramiko https://github.com/paramiko/paramiko/issues/23

**Comment by ohjames** [comment]
Is there a release with this fix?

**Comment by dongsupark** [comment]
@ohjames This issue was already fixed via https://github.com/coreos/fleet/pull/1540, which belongs to v0.13.0.

**Comment by ohjames** [comment]
Even the CoreOS alpha is on v0.11.8, it's hard to believe all CoreOS users are affected by this bug :(

**Comment by dongsupark** [comment]
@ohjames True. v0.11.8 does not contain the fix.
