### ISSUE TITLE
fleetctl: stop command doesn't show correct message

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1432]
Here is how you can reproduce that. Unit file:

```ini
[Service]
ExecStart=/usr/bin/true
Type=oneshot
```

```sh
$ fleetctl start app.service
Unit app.service inactive
Unit app.service launched on 0eb1b9b6.../coreos1
```

```sh
$ fleetctl status
● app.service
   Loaded: loaded (/run/fleet/units/app.service; linked-runtime; vendor preset: disabled)
   Active: inactive (dead)

Feb 15 15:24:33 coreos1 systemd[1]: Starting app.service...
Feb 15 15:24:33 coreos1 systemd[1]: Started app.service.
```

```sh
$ fleetctl stop app.service
Unit app.service loaded on 0eb1b9b6.../coreos1
```

fleetctl stops unit, but shows incorrect message `Unit app.service loaded on 0eb1b9b6.../coreos1`.

**Comment by tixxdz** [comment]
When you stop a unit I guess it tries to return to the "JobStateLoaded" state which is defined here https://github.com/coreos/fleet/blob/master/job/job.go#L29 to "loaded" string. All the logic is printed here https://github.com/coreos/fleet/blob/master/fleetctl/fleetctl.go#L820

So in this branch https://github.com/endocode/fleet/tree/tixxdz/fleet-code-cleaning-v1 we can pass the correct string state down to these callers without adding or updating JobStates.

**Comment by dongsupark** [comment]
Closed via https://github.com/coreos/fleet/issues/1577.
