### ISSUE TITLE
tests: add overview of the passed / non-passed functional tests

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1436]
At the moment it is hard to find which tests were failed and which passed. I suppose we have to add an overview of passes/non-passed tests like:

```
PASS: test1
PASS: test2
FAIL: test3
PASS: test4
...
PASS: test60

============================================================================
Functional tests summary
============================================================================
# TOTAL: 60
# PASS:  59
# FAIL:  1
```

**Comment by reneengelhard** [comment]
@kayrus see

commit 0bdefaba3532fe4d3058332558f3682a9f669e40
Author: Rene Engelhard <rene@endocode.com>
Date:   Tue Feb 23 16:26:40 2016 +0100

    (re)sort output

commit 70efb11f25b8f9df380c72c3a1a3451422b9f9fc
Author: Rene Engelhard <rene@endocode.com>
Date:   Tue Feb 23 16:04:06 2016 +0100

    add test statistics to functional tests

in kayrus/docker_test

**Comment by jonboulle** [comment]
idea/patch LGTM
