### ISSUE TITLE
Problem in MAC address

### ISSUE THREAD

**Issue by arkkanoid** [coreos/fleet#1438]
I get the following error in one node with Coreos:

    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Gained carrier
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Configured
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-udevd[14316]: Could not generate persistent MAC address for veth7726b88: No such file or directory
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth7726b 88: Configured
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Lost carrier
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Removing non-existent address: fe80::42:aff:fef4:425b/64 (valid for ever)

Moreover, I can't run any command of systemctl neither run docker containers. I'm not sure if both errors are related.

How can I solve this problem?

**Comment by kayrus** [comment]
@arkkanoid does this issue relate to fleet?

**Comment by arkkanoid** [comment]
I'm not sure, it's about network configuration so I expected that this error was related with fleet

**Comment by kayrus** [comment]
@arkkanoid Please create a ticket here: https://github.com/coreos/bugs/issues/new
