### ISSUE TITLE
usability: show warning for the fleetctl subcommands

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1443]
Current behavior:

```
$ fleetctl destroy # start/stop/load/any fleet subcommand
# nothing is here
$ echo $?
0
```

Desired behavior:

```
$ fleetctl destroy # start/stop/load/any fleet subcommand
Too few arguments.
$ echo $?
1
```

**Comment by kayrus** [comment]
relates https://github.com/coreos/fleet/issues/1445

**Comment by tixxdz** [comment]
running: `fleetctl journal` 
`One unit file must be provided.`

We should just be consistent and of course tell the user that he must supply the right arguments.

**Comment by jonboulle** [comment]
Following previous discussions about the semantics of `fleetctl destroy <nonexistent unit>`, and for example #1417, it's not _immediately_ obvious to me that `fleetctl destroy` should error. We need to justify making a backwards-incompatible change here

**Comment by jonboulle** [comment]
How about we just write something to stderr saying "No units given"

**Comment by kayrus** [comment]
and 0 exit code? ok.
