### ISSUE TITLE
Help: Escaping %s

### ISSUE THREAD

**Issue by ivankennethwang** [coreos/fleet#1444]
Is there a way to escape `%s` such that when I do

`ExecStartPre=/bin/bash -c '/usr/bin/echo "%s" > test'`

it will just write `%s` literally to test?

**Comment by kayrus** [comment]
More information about specifiers could be found [here](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers)

In your case if you wish to write down '%s' you have to use '%%s'

**Comment by ivankennethwang** [comment]
thanks
