### ISSUE TITLE
tests: add functional test which deals with the TLS etcd authentication

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1447]
subj

**Comment by kayrus** [comment]
Create cloud-config which will start two etcd instances. One with TLS, second with plain HTTP. We can create a loop like:

```sh
for type in plain tls; do
  test $type
done
```

@jonboulle, any suggestions? probably we can avoid extra containers spawn.

**Comment by jonboulle** [comment]
I don't see a strong use case for such a functional test - we are basically just directly leveraging the etcd/client library's functionality right?

**Comment by kayrus** [comment]
@jonboulle in future we will implement etcd's ACL. and I'd like to test this feature in bundle with TLS auth. If you don't this it worth that, let's close this issue.

**Comment by mischief** [comment]
having a etcd2+fleet tls test in github.com/coreos/mantle might be nice.

**Comment by jonboulle** [comment]
I also think it's probably something more suitable for mantle.

**Comment by dongsupark** [comment]
It looks like this is not a fleet issue. Closing.
