### ISSUE TITLE
Godeps: migrate to vishvananada/netlink dependency

### ISSUE THREAD

**Issue by onlyjob** [coreos/fleet#1468]
Obsolete _libcontainer_ is still used by [machine/coreos.go](../blob/master/machine/coreos.go#L26). Please migrate to [runc](http://github.com/opencontainers/runc/releases).

**Comment by onlyjob** [comment]
Relevant project: https://github.com/vishvananda/netlink

**Comment by tixxdz** [comment]
@onlyjob hey if we are using only netlink for communication with the kernel then it makes sense to try to only have netlink and not other unrelated stuff, but then is this netlink library you linked is official somewhere ? do you have some links on which projects are using it ? the README does'nt say anything. Anyway perhaps we may update later to what runc is using if there are real bugs perhaps in libcontainer that affect fleet and that can't be fixed or new features..., otherwise I'll let @jonboulle complete.

**Comment by jonboulle** [comment]
We should change the dep to `github.com/vishvananda/netlink`, since the current one is now a dangling pointer.

**Comment by onlyjob** [comment]
From the quick lookup the following projects use "vishvananda/netlink": docker, docker-libnetwork, rkt, runc, appc-cni, cadvisor. Some of them may be using it indirectly through dependencies...

**Comment by onlyjob** [comment]
Notable commit: https://github.com/crosbymichael/docker/commit/d0fdc3b5dfa951870f4a7c0a08dea8c1bc68a31b

**Comment by onlyjob** [comment]
Could somebody review 27cc0df please? It compiles but it is not tested. I'm illiterate in Golang so I don't really understand what am I doing... Thanks.

**Comment by kayrus** [comment]
@onlyjob try to create a pull request and these changes should be tested autimatically.

**Comment by onlyjob** [comment]
Thanks, @kayrus. As I've said it builds and all unit tests (i.e. `go test`) are passing.
I'd like human to review code and (ideally) test runtime as well.

I'm not making pull request as it should take care of vendoring that I'm not sure how to handle nor I have time for it... :(

**Comment by kayrus** [comment]
@onlyjob unit tests are not enough. we also have [functional tests](https://github.com/coreos/fleet/blob/master/functional/README.md). Creating of the pull request will not harm. And we'll be able to review your code inside PR.

**Comment by reneengelhard** [comment]
I checked out onlyjob/fleet and ran the functional tests, They succeed.

**Comment by reneengelhard** [comment]
ignore me, wrong branch. retrying...

**Comment by reneengelhard** [comment]
ok, also succeeding with the correct branch.

but the "internal copy" of vishvananda/netlink is missing

**Comment by jonboulle** [comment]
Yeah, it needs to be vendored. Instructions are here:
https://github.com/coreos/docs/blob/master/golang/godep.md

**Comment by onlyjob** [comment]
> ok, also succeeding with the correct branch.

Thanks for checking, Rene.

> but the "internal copy" of vishvananda/netlink is missing

Yeah, somebody have to finish my half-baked commit properly...

**Comment by reneengelhard** [comment]
https://github.com/coreos/fleet/pull/1483
