### ISSUE TITLE
usability: reload fleetd configuration

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1470]
relates to https://github.com/coreos/fleet/issues/1190

It is not possible to reload configuration for fleet. `systemctl restart fleet` will restart fleet with *all* its scheduled units. The workaround is `kill -9 $(pidof fleetd); systemctl restart fleet` but it is a hack. We have to provide proper built-in solution.

/cc @jonboulle

**Comment by dongsupark** [comment]
Hasn't this issue been already resolved by https://github.com/coreos/fleet/pull/1517 ?

**Comment by dongsupark** [comment]
Closed via https://github.com/coreos/fleet/pull/1517
