### ISSUE TITLE
Update vendoring to allow `ssh` package use outside of fleet

### ISSUE THREAD

**Issue by jasonmoo** [coreos/fleet#1477]
`github.com/coreos/fleet/ssh` has a nice known hosts check that is compatible with `golang.org/x/crypto/ssh`, but vendoring with Godeps creates a namespacing problem which prevents it from being used outside the `fleet` library fwict.

```go
func EnsureKnownHosts(hostsFile string, config *ssh.ClientConfig) {
	key := fleetssh.NewHostKeyFile(hostsFile)
	check := fleetssh.NewHostKeyChecker(key)
	config.HostKeyCallback = check.Check
}
```
```bash
./ssh_config.go:36: cannot use check.Check (type func(string, net.Addr, "github.com/coreos/fleet/Godeps/_workspace/src/golang.org/x/crypto/ssh".PublicKey) error) as type func(string, net.Addr, "golang.org/x/crypto/ssh".PublicKey) error in assignment
```

 It's possible I'm misusing this library somehow, but it seems like the [Go vendor experiment](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) that has been adopted in [go 1.6](https://golang.org/doc/go1.6) might enable this type of use.

**Comment by dongsupark** [comment]
I think this issue is already resolved since fleet started using govendor instead of Godeps. As far as I tested it shortly, it's already possible to call methods of ``github.com/coreos/fleet/ssh``, even outside of fleet.
So I'm closing it. Thanks!

**Comment by jasonmoo** [comment]
Cool I actually went ahead and wrote a slightly more robust version.  But glad you guys are making this available.

https://github.com/emptyinterface/knownhosts
