### ISSUE TITLE
Failed building SSH client: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running.

### ISSUE THREAD

**Issue by ghy200692162** [coreos/fleet#1480]
When I try to use command 'fleetctl ssh simeunit.service' I got the error message below

    Failed building SSH client: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running. See https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md for help.

Then I fixed this error use the following command,just start the ssh agent and add the public key

    1.eval ssh-agent

    2.ssh-add ~/.ssh/some_key

While I have to repeat the process every time when I login the System.

I open an issue here to show the way to add the command to $HOME/~bashrc
But it looks like to modify the configuration in the System scope.

How can I start ssh-agent and add public key when  fleet  init after my coreos has been configured and started?

**Comment by kayrus** [comment]
@ghy200692162 you can forward ssh agent to the target host with the `ssh -A core@coreos.host`. And it is not quite correct to keep private keys on the remote servers.

You can find more info here: http://www.unixwiz.net/techtips/ssh-agent-forwarding.html and here http://linux.die.net/man/1/ssh
