### ISSUE TITLE
fleet "Requires=" and "After=" keeps my service dead

### ISSUE THREAD

**Issue by Alino** [coreos/fleet#1494]
this is how I start my services:
```bash
fleetctl submit elasticsearch@.service elasticsearch-discovery@.service; \
fleetctl start elasticsearch@9200.service elasticsearch-discovery@9200.service; \
fleetctl submit mongo2es@.service mongo2es-discovery@.service; \
fleetctl start mongo2es@3001.service mongo2es-discovery@3001.service;
```

This is [Unit] section of my `mongo2es@.service`
```
[Unit]
Description=Mongo2ES service on port %i

# Requirements
Requires=etcd2.service
Requires=docker.service
Requires=mongo2es-discovery@%i.service
Requires=elasticsearch@9200.service

# Dependency ordering
After=etcd2.service
After=docker.service
After=elasticsearch@9200.service
Before=mongo2es-discovery@%i.service
```

This results into **dead** mongo2es@3001 service even though elasticsearch@9200 is UP!
Here is a screenshot:
<img width="776" alt="screenshot_09_03_16_19_10" src="https://cloud.githubusercontent.com/assets/763194/13645461/6573516e-e62b-11e5-901e-5b8d08ef8e88.png">

checking logs with fleetctl status and fleetctl journal -f gives only these results:

<img width="817" alt="screenshot_09_03_16_19_22" src="https://cloud.githubusercontent.com/assets/763194/13645517/9b9960c6-e62b-11e5-8c90-87262c78a556.png">

Why is mongo2es DEAD? If Elasticsearch@9200 is running? Because if I remove these two lines in mongo2es [Unit] section:
```
Requires=elasticsearch@9200.service
After=elasticsearch@9200.service
```
then it works. Mongo2es is then running. But I need to be always sure that elasticsearch is running before running Mongo2es. That's why I am trying to solve it with Requires and After inside `mongo2es@.service`.

Any suggestions?

**Comment by Alino** [comment]
here are unit files for `elasticsearch@.service` and `mongo2es@.service` if necessary.
https://gist.github.com/Alino/87fba4a6f7c9210db6b0

**Comment by Alino** [comment]
I gave up on 'Requires' (removed that line) and as a workaround I do this instead:
```
ExecStartPre=/bin/bash -c '\
  set -e; \
  status=$$(fleetctl list-units | grep elasticsearch@9200 | awk \'{print $$3}\'); \
  if [ $status != "active" ]; then \
    echo "EXITING YOLO BITCH YOLO!!!"; \
    exit 1; \
  fi; \
  echo $status;'
```

in combination with:
```
Restart=on-failure
RestartSec=5s
```

inspired by: http://unix.stackexchange.com/questions/213185/restarting-systemd-service-on-dependency-failure

**Comment by kayrus** [comment]
I've noticed that has `elasticsearch@.service` has `Conflicts=mongo*.service`. It doesn't explain the issue but it looks weird. `mongo*.service` includes `mongo2es@.service`.
Can you also share `*-discovery*` services?

**Comment by kayrus** [comment]
elasticsearch unit has `Conflicts=mongo*.service` which includes `mongo2es@.service` so it can not run on the same machine with mongo services.

`mongo2es@.service` has `Requires=elasticsearch@9200.service` which is incompatible with the condition above.

**Comment by Alino** [comment]
oh so 'Requires' is only for the same coreos node. I thought it works across the whole cluster. Thanks for making this clear.

**Comment by kayrus** [comment]
Yes, `Requires` is [systemd](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Requires=) option. Fleet/cluster related options are defined in [`X-Fleet`](https://github.com/coreos/fleet/blob/master/Documentation/unit-files-and-scheduling.md#fleet-specific-options) section.
