### ISSUE TITLE
fleetctl equivalent for "systemctl is-active"

### ISSUE THREAD

**Issue by Alino** [coreos/fleet#1495]
Is there equivalent for fleetctl?

I like that if I run `systemctl is-active docker` I get `active`
I also want to be able to get status of unit which was staretd by fleetctl start.

Meanwhile as a workaround I do this:
`fleetctl list-units | grep mongo@1 | awk '{print $3}'`

**Comment by kayrus** [comment]
You can use `fleetctl status mongo@1`
