### ISSUE TITLE
Intermittent failure in TestScheduleOneWayConflict

### ISSUE THREAD

**Issue by antrik** [coreos/fleet#1504]
This test sometimes fails (see https://semaphoreci.com/coreos/fleet/branches/pull-request-1501/builds/3 ) due to a race condition in the test case. There is actually a [comment](https://github.com/coreos/fleet/blob/master/functional/scheduling_test.go#L286) in there saying:

```
// TODO(jonboulle): fix this race. Since we no longer immediately
// remove unit state on unit destruction (and instead wait for
// UnitStateGenerator/UnitStatePublisher to clean up), the old unit
// shows up as active for quite some time.
```

I guess it could be fixed by using a similar loop as the one in [WaitForNActiveUnits()](https://github.com/coreos/fleet/blob/master/functional/platform/nspawn.go#L107). I wonder though whether checking the number of known units like that before checking the active units is really necessary? Maybe it could just be moved after the active units check -- or even dropped altogether?..

**Comment by jonboulle** [comment]
@antrik I think you might be right - looks like it's probably just redundant with WaitForNActiveUnits?

**Comment by antrik** [comment]
@jonboulle well, it's not *entirely* redundant, as it checks the total number of units, rather than "only" the active ones. It's not clear to me though whether or not there is much value in doing this...

Note that once https://github.com/coreos/fleet/pull/1501/commits/520a90f269c3bfd554d99f4b39371eb37a157c96 lands, it will be very easy to fix the race while keeping the extra test. I'm fine with either option.

**Comment by antrik** [comment]
@jonboulle in fact, https://github.com/coreos/fleet/pull/1509/commits/8a22f07cf4c842723491dbbf06335fba0e41e9fe (and the followup https://github.com/coreos/fleet/pull/1509/commits/cd3a786cb655e5bb9d8eb46a5ad2283ab87aeb1b ) want to add a dedicated function just for that, which could be used here as well... I could just go ahead and add this function independently.

**Comment by antrik** [comment]
Finding an appropriate wait condition turned out slightly more involved in the end; but it's working now with https://github.com/coreos/fleet/pull/1531.
