### ISSUE TITLE
Documentation slightly confusing regarding AND'ing and OR'ing of MachineMetadata

### ISSUE THREAD

**Issue by daniellowtw** [coreos/fleet#1511]
While reading the documentation on https://github.com/coreos/fleet/blob/master/Documentation/unit-files-and-scheduling.md#schedule-unit-to-machine-with-specific-metadata I erroneously interpreted metadata restriction as OR'ing everything from different lines and AND'ing everything on the same line as suggested by the first few examples.

However, looking at the code, there is no difference between separating them with space in the same line or having them on separate lines. The following modified test illustrates this:

https://github.com/coreos/fleet/blob/master/job/job_test.go#L323

```
...
func TestJobRequiredMetadata(t *testing.T) {
	testCases := []struct {
		unit string
		out  map[string]pkg.Set
	}{
		// multiple different key-value pairs in a single line
		{
			`[X-Fleet]
MachineMetadata="foo=bar" "duck=quack"
MachineMetadata="foo=car"`,
			map[string]pkg.Set{
				"foo":  pkg.NewUnsafeSet("bar", "car"),
				"duck": pkg.NewUnsafeSet("quack"),
			},
		},
		{
			`[X-Fleet]
MachineMetadata=foo=bar
MachineMetadata=foo=car
MachineMetadata="duck=quack"`,
			map[string]pkg.Set{
				"foo":  pkg.NewUnsafeSet("bar", "car"),
				"duck": pkg.NewUnsafeSet("quack"),
			},
		},
	}
	for i, tt := range testCases {
		j := NewJob("echo.service", *newUnit(t, tt.unit))
		md := j.RequiredTargetMetadata()
		if !reflect.DeepEqual(md, tt.out) {
			t.Errorf("case %d: metadata differs", i)
			t.Logf("got: %#v", md)
			t.Logf("want: %#v", tt.out)
		}
	}
...
```

Hence, in the documentation, there should be another example illustrating this logic.

```
[X-Fleet]
MachineMetadata="region=us-east-1" "job=foo"
MachineMetadata="region=us-west-1" "job=bar"
```
Would correspond to 

```
(job=foo OR job=bar) AND (region=us-east-1 OR region=us-west-1)
```

as it is very easy to confuse it as 

```
(job=foo AND region=us-east-1) OR (job=bar AND region=us-west-1)
```

Or better still, emphasize that separating requirements with spaces or specifying them on separate lines make no difference (if that is indeed the intention).

**Comment by kayrus** [comment]
@daniellowtw there is no difference whether you put space or not and documentation doesn't tell about that. "OR" statement takes place only when you define the key several times:

`A single key may also be defined multiple times, in which case only one of the conditions needs to be met`

It doesn't matter how exactly do you define these statements:

```ini
[X-Fleet]
MachineMetadata="region=us-east-1" "diskType=SSD"
MachineMetadata=region=us-west-1
```

will make the same result as:

```ini
[X-Fleet]
MachineMetadata="region=us-east-1" "diskType=SSD" "region=us-west-1"
```

**Comment by kayrus** [comment]
@joshix @robszumski can you suggest better explanation for this logic?
