### ISSUE TITLE
Build doesn't define GLDFLAGS anymore

### ISSUE THREAD

**Issue by hectorj2f** [coreos/fleet#1519]
I remember to see in build 
`-GLDFLAGS="-X $(go_linker_dashX github.com/coreos/fleet/version.Version ${VERSION})"` 

Did you remove it by any reason ? If so, build file shouldn't use in my opinion. E.g.:
`  CGO_ENABLED=0 go build -o bin/fleetd -a -installsuffix netgo -ldflags "${GLDFLAGS}" ${REPO_PATH}/fleetd`

**Comment by tixxdz** [comment]
Hi @hectorj2f 

https://github.com/coreos/fleet/blob/master/build-env

https://github.com/coreos/fleet/blob/master/build#L15

?

**Comment by hectorj2f** [comment]
@tixxdz Ops! Sure. I didn't find it :+1:
