### ISSUE TITLE
Dependency in Global unit on non-global unit

### ISSUE THREAD

**Issue by dmytro** [coreos/fleet#1522]
I want to run `logsprout` as a global unit so it will be collecting logs from all hosts. Logsprout requires Logstash to deliver logs to Elastic Search, but I want to run single instance of LS and link to it using overlay network with Docker DNS.

I tried adding dependency to logsprout unit as:
```
[Unit]
Requires=logstash.service
After=logstash.service

[X-Fleet]
Global=true
``` 
However `logsprout` fails to start on hosts where Logstash is not running. 
Is there a way to have both dependency and `Global` at the same time?

**Comment by kayrus** [comment]
@dmytro As you defined "Requires=logstash.service" it requires "logstash.service" on the host. If host doesn't have this unit file, `logsprout.service` will fail.

Just remove this dependency and start the service. Please note that fleet recognizes only `[X-Fleet]` section. It doesn't process `[Unit]`, `[Service]`, etc. These sections are processed directly by systemd.

**Comment by dmytro** [comment]
Thank you for the clarification.
