### ISSUE TITLE
Limit number of units per node

### ISSUE THREAD

**Issue by omykuji** [coreos/fleet#1530]
Hi, 
Is possible to limit the number of units per node, so if fleet check that one node is full runs the unit in another node?

**Comment by hectorj2f** [comment]
@omykuji no, fleet uses a simple scheduling algorithm that checks the amount of units in the nodes and schedule the unit in the one with the lower number. So, I believe you'd need to either use a proper scheduler like k8s (but this is far from your needs) or adapt the fleet decision making algo to your needs. It should be quite easy. According to that, there were some issues that aimed to improve the scheduling algo like https://github.com/coreos/fleet/issues/1055, https://github.com/coreos/fleet/issues/747.

Recently, there was a discussion in https://github.com/coreos/fleet/issues/1262 where they asked for a new metadata property MaxAllowed which could refer to units but nothing was decided.

**Comment by omykuji** [comment]
thanks @hectorj2f
