### ISSUE TITLE
build: replace gopdep with vendor

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1536]
abandon golang 1.4 support and replace godep with vendor.
@tixxdz @antrik @jonboulle comments?

**Comment by hectorj2f** [comment]
Sorry for jumping in, +1 on this :).

**Comment by tixxdz** [comment]
@kayrus yes as suggested by coreos and others. thanks!

**Comment by dongsupark** [comment]
Closed via https://github.com/coreos/fleet/pull/1555.
