### ISSUE TITLE
tests: automatically fetch systemd-nspawn jounal logs when functional tests are failed

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1565]
Sometimes functional tests are failed for an unknown reason. In these cases automatic logs fetching could help to debug the problem.
/cc @tixxdz @jonboulle @dongsupark

**Comment by jonboulle** [comment]
hmm what do you mean automatically fetch? From where?

**Comment by kayrus** [comment]
@jonboulle from the nspawn container.
