### ISSUE TITLE
Documentation shows AWS_ACCESS_KEY & AWS_SECRET_KEY

### ISSUE THREAD

**Issue by ewoutp** [coreos/fleet#1607]
See github.com/coreos/fleet/blob/master/Documentation/examples/example-deployment.md

**Comment by dongsupark** [comment]
@ewoutp ok, that's definitely not good. I wasn't aware of that, as it was written a long time ago. Can you probably create a PR to fix it?

**Comment by ewoutp** [comment]
@dongsupark See #1608
