### ISSUE TITLE
[RFC] vendor: use glide for package management

### ISSUE THREAD

**Issue by dongsupark** [coreos/fleet#1610]
As @kayrus suggested, we need to consider using ``glide`` for package management, instead of ``govendor``.

I'm fine with using glide. Currently many CoreOS projects are already using glide, and other projects like etcd are also preparing the conversion. For fleet, the conversion looks much easier than I thought, because we already converted ``Godeps`` into ``vendor``. One downside is that glide doesn't support updating a single repo yet, but the functionality is going to be implemented soon.

One open question is whether we keep vendor/* checked in (just like now) or not (like torus). I would prefer to just keeping vendors, as I saw several build issues when they are not checked in.

**Comment by jonboulle** [comment]
+1, moving glide would be great, and please keep vendor/ checked in, thanks!
