### ISSUE TITLE
What is current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [coreos/fleet#1611]
The releases page describes 0.11.7 as the "latest release," but there are also 0.12.0 and 0.13.0 tags. For the purposes of Homebrew's fleectl formula, which should we be distributing as the current stable version? Right now it's 0.11.7, but I wasn't sure whether that ought to be bumped to 0.13.0 or not yet.

**Comment by dongsupark** [comment]
(I'm not exactly right person to answer such questions, but I'm trying not to be unresponsive over a week.)

Short answer is 0.11.7, which is the version installed on CoreOS alpha 1081.

Long answer: I think a particular version of fleet needs to be included in a CoreOS alpha image, to be verified to work in various use cases. As both 0.12 and 0.13 have never been included in CoreOS images, the versions have more steps ahead.
On the other hand, I don't know why even 0.12 is not included in CoreOS alpha. When newer versions could be included in CoreOS images, it would help us find unexpected bugs in advance.
By the way I'm testing fleet 0.13 (and newer) nearly every day, and I've tested it also with CoreOS alpha 1081. So far it seems to work fine. No error.

**Comment by aneeth** [comment]
are fixes for issues [1290](https://github.com/coreos/fleet/issues/1290) [1291](https://github.com/coreos/fleet/pull/1291) [1456](https://github.com/coreos/fleet/issues/1456) included in 0.12 or 0.13?

**Comment by dongsupark** [comment]
@aneeth PR #1291 (for issue #1290) is not merged yet, and not available yet in 0.12 or 0.13. I reimplemented the same one as #1510 , which is still pending. More reviews are welcome.
I suppose #1456 is also about the same issue.

**Comment by dongsupark** [comment]
I assume the original question was already clarified. Closing.
