### ISSUE TITLE
core os 部署完群集，发现iowait在20%-40%

### ISSUE THREAD

**Issue by hupp123** [coreos/fleet#1629]
core os 部署完群集，发现iowait在20%-40%

**Comment by dongsupark** [comment]
English, please? ;-)
A precise bug description would be also great. Thanks.

**Comment by hupp123** [comment]
when we deployed  coreos cluster on the Azure, the iowait of the vm is very high between 20%-40%,but if the environment is single coreos  vm ,the iowait is normal

**Comment by kayrus** [comment]
I suggest this issue doesn't relate to fleet, please file a bug following the link below:
https://github.com/coreos/bugs/issues/new
