### ISSUE TITLE
Ignored environment variables.

### ISSUE THREAD

**Issue by odolbeau** [coreos/fleet#1631]
Hi.

In v0.13.0 it seems environment variables are not taken into account.
I tried with `FLEETCTL_ENDPOINT` for example.

**Comment by dongsupark** [comment]
Yeah, true.
From a quick research, I think the env variable ``FLEETCTL_ENDPOINT`` is never taken into account, neither in v0.13 nor in v0.11.7. I'm not sure since when it has been broken, but that's clearly a bug.
As a workaround, please use the cmdline option ``--endpoint``.

**Comment by odolbeau** [comment]
It works correctly in v0.11.7. :)

**Comment by odolbeau** [comment]
It works correctly in v0.11.7. :)

**Comment by dongsupark** [comment]
@odolbeau Fixed a bug. See https://github.com/coreos/fleet/pull/1633. Thanks for the bug report.

**Comment by berglh** [comment]
Confirmed latest master ```fleetctl version v0.12.0-281-ge98df4c``` resolved this issue - thanks.

**Comment by dongsupark** [comment]
@berglh Glad to hear that. Thanks!
