### ISSUE TITLE
fleetctl status needs  SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by f0** [coreos/fleet#1680]
Hi,

i try to use fleetctl from inside a rkt container, to made this work i bind mount the fleet.sock.

I can successfully run fleetctl list-machines and list-units 

When i try to run fleetctl status <some_unit> i got this error

> Error running remote command: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running. See https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md for help.

is this expected ?

regards f0

**Comment by jonboulle** [comment]
`fleetctl status` uses ssh under the hood so it will need access to run successfully..

**Comment by f0** [comment]
@jonboulle ok thx, then we use the api
