### ISSUE TITLE
Warning if (duplicate) unit is already in systemd

### ISSUE THREAD

**Issue by BenjaminHerbert** [coreos/fleet#1687]
I submitted a changed service file with fleetctl and it was accepted without warning.
Upon starting the unit, I discovered that the old unit was still used. The reason seems to be that in systemd there was a unit with the same name (and old content), which was invoked instead of the file scheduled to fleetctl.

Is it possible to issue a warning or fail the command in such a case?

**Comment by dongsupark** [comment]
I'm not sure about failing the command, but in theory it would be possible to print out a warning.
Apart from that, in this use case, I think you would probably want to run `"fleetctl --replace"` to replace the existing unit file with a new one. That option was implemented via https://github.com/coreos/fleet/pull/1509 (already in master), which will be included in release v0.13.

**Comment by dongsupark** [comment]
Aha, "printing a warning" was already addressed by https://github.com/coreos/fleet/pull/1560, which is included in release [v0.13.0](https://github.com/coreos/fleet/releases/tag/v0.13.0).
So I'm closing this issue. Thanks.
