### ISSUE TITLE
Error creating units: error retrieving Unit(appname-16@1.service) from Registry: Get http://domain-sock/fleet/v1/units/appname-16%401.service?alt=json: EOF

### ISSUE THREAD

**Issue by anuiq** [coreos/fleet#1688]
I have set up my Coreos cluster on AWS using cloud formation. I am trying to deploy my application but I get this problem. I have looked at other closed issues about this but none of them have really resolved my problem. 

fleetctl list-machines 
MACHINE     IP      METADATA
2e08ddd2... 100.99.254.114  -
4dffa611... 100.99.254.113  -
8a5bgg09... 100.99.254.115  -

What are the possible causes for this issue ?

**Comment by dongsupark** [comment]
The first point to check is of course etcd, as the error message `"error retrieving Unit(...) from Registry"` means that fleet could not get the unit from etcd registry.
Is that a temporary error, or persistent one? Does it work again after restarting etcd?
