### ISSUE TITLE
Vagrant cluster demo does not work with fleet.

### ISSUE THREAD

**Issue by HelloGrayson** [coreos/fleet#211]
https://coreos.com/docs/running-coreos/platforms/vagrant/

I'm guessing because these systems are not properly setup with SSH.

Getting issue detailed here: https://github.com/coreos/fleet/issues/143

**Comment by tscolari** [comment]
This bug report was very useful for me, thanks!
For who else may be having this issue, another solution for this is to add the `public-ip` to the `fleet` configuration in your cloud-config, e.g.:

```
fleet:
  public-ip: $public_ipv4
``
