### ISSUE TITLE
Factor OS update-to-date-ness into scheduling decisions

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#283]
When the engine is choosing where to schedule a job among different Agents, I propose that it factor in a preference for Agents running on more up-to-date versions of CoreOS. For example, with all other requirements being equal, an Agent running CoreOS 273.0.0 would be chosen over one running CoreOS 271.0.0 

This should minimise the possibility that a system on which a Job is scheduled is likely to imminently be rebooted to apply a CoreOS update; and consequently, should maximise the lifetime of services, and (at a large enough scale) reduce the impact of update-initiated reboots on a cluster.

**Comment by bcwaldon** [comment]
This might be something that falls out of #1055, but it will not be natively supported in fleet independent of that discussion
