### ISSUE TITLE
distro packages and repositories would be helpful

### ISSUE THREAD

**Issue by danieldreier** [coreos/fleet#425]
Yum/apt repositories would simplify fleet installs, and if packages in the repositories tracked the versions in CoreOS it'd make it much simpler to keep workstations in sync with the server versions. 

https://github.com/jordansissel/fpm is an excellent, simple tool for creating the rpm/dpkg packages, but some amount of key management would also be needed for GPG signed packages.

**Comment by onlyjob** [comment]
Official [Debian](https://tracker.debian.org/pkg/fleet) [packages](https://packages.debian.org/unstable/fleet) are available. ;)

I strongly recommend to avoid _fpm_ as a packaging tool -- I haven't seen packages worse that what it produces...

**Comment by danieldreier** [comment]
awesome! thanks!
