### ISSUE TITLE
filter ListUnits dbus method to subscribed units

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#478]
Per philips, we should do something like the following to narrow down what messages we actually listen to
http://cgit.freedesktop.org/systemd/systemd/commit/?id=cdc06ed7b6120c1049305fa7033f228ee9d86043

**Comment by jonboulle** [comment]
This might be low hanging fruit to potentially improve performance with large numbers of units. Needs benchmarking.

**Comment by kayrus** [comment]
@jonboulle this filter applies on units' status only. and there is no method which will request units info only for specified unit names or filter. here is experimental implementation of this feature:
https://github.com/endocode/systemd/commit/ebe011c3bc64cf67096b65b66472894f99f8e399

**Comment by kayrus** [comment]
@jonboulle @antrik @tixxdz quick benchmark of the https://github.com/endocode/systemd/commit/ebe011c3bc64cf67096b65b66472894f99f8e399:

patched systemd and systemctl version:

```sh
time for i in {1..1000}; do ./systemctl list-units fleet.service > /dev/null 2>&1; done

real    0m4.087s
user    0m0.901s
sys     0m1.023s
```

original version:

```sh
time for i in {1..1000}; do systemctl list-units fleet.service > /dev/null 2>&1; done

real    0m7.305s
user    0m1.914s
sys     0m1.279s
```

**Comment by tixxdz** [comment]
@jonboulle this one is not really a low hanging fruit, if fixed correctly from systemd to other layers it will also make fleet much better, since it does not only covers some if not all case of PR #1418 but it will also reflect on other parts of the code. However, the task is not really easy and it needs several fixes.

Thanks!
