### ISSUE TITLE
fleetctl submit - name conflict

### ISSUE THREAD

**Issue by porjo** [coreos/fleet#614]
When I submit a unit file with the same name as one already in the registry, but where content differs, I get the following message:

```
$ fleetctl submit xxxx.service
WARNING: Job(xxxx.service) in Registry differs from local Unit(xxxx.service)
```

I find this message misleading. My expecation is that the unit file has been updated with the new content, however that is not the case. Running `fleetctl cat xxxx.service` shows the old content.

A clearer message would be:

```
ERROR: Job(xxxx.service) in Registry differs from local Unit(xxxx.service). No change made.
```

Alternatively, a 'force' flag could be added for those occasions when you really do want to overwrite the unit file. In that case the WARNING message would be appropriate.

**Comment by jonboulle** [comment]
Let's just do a simple UX fix improvement here.

**Comment by antrik** [comment]
This UI change seems interconnected with the upcoming addition of the --replace flag (following up on https://github.com/coreos/fleet/pull/1295 and https://github.com/coreos/fleet/pull/1442 ) -- maybe it should in fact be done as part of that?

**Comment by tixxdz** [comment]
@antrik indeed, maybe it should just warn the user "please use --replace" ?!

**Comment by antrik** [comment]
Exact wording TBD; but basically that's what I meant indeed.

**Comment by tixxdz** [comment]
After #1509 is merged this one can just be fixed with this branch: https://github.com/endocode/fleet/commits/tixxdz/fleetctl-warn-user-aboutt-replace

Thanks!
