### ISSUE TITLE
agent: check for existing machine-ids on startup

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#615]
If multiple systems in a cluster happen to have the same machine-id, all hell can break loose. It would be nice if the agent could be able to do a simple sanity check when first registering itself in the cluster; if there's an existing machine with its machine-id, it can log something useful and/or back off and try again (e.g. in case a previously-pushed machineState just hasn't TTLed yet)

**Comment by steveeJ** [comment]
I strongly vote for including a sanity check to ensure unique machine-ids. I came across this due to cloned VMs and spent hours of debugging until @jonboulle pointed me in the right direction.

**Comment by jasonkeene** [comment]
+1 this was a head scratcher

**Comment by tixxdz** [comment]
@antrik could you take this one, and it seems there is a PR https://github.com/coreos/fleet/pull/1288
