### ISSUE TITLE
Idea: SideKick Job Removal

### ISSUE THREAD

**Issue by sukrit007** [coreos/fleet#668]
As a fleet user, When I remove a main job , all the sidekick jobs which "BindsTo" the main job should automatically get removed, so that we do not have to cleanup the sidekick jobs explicitly (as sidekick job can not can get scheduled again because the main job was removed).

Currently, fleet does stop these sidekick jobs but does not automatically remove them. 

This idea is based on discussions at:
https://github.com/coreos/bugs/issues/66

**Comment by bcwaldon** [comment]
fleet is not going to provide any sort of cascading deletion of other units in the system
