### ISSUE TITLE
use new `systemctl is-system-running` in functional tests

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#699]
from systemd 215 release notes
>        * A new command "systemctl is-system-running" has been added
          that allows checking the overall state of the system, for
          example whether it is fully up and running.

I think we can use this [here](https://github.com/coreos/fleet/blob/f46dd4e19bf5f78178ce0d8f5959f3f2623631b5/functional/platform/nspawn.go#L280), but need to test and confirm

**Comment by bcwaldon** [comment]
The functional tests have evolved a lot since this ticket was filed. Please reopen if this is still relevant.
