### ISSUE TITLE
Document template units

### ISSUE THREAD

**Issue by tiagoboldt** [coreos/fleet#703]
I believe multiple instances for an unit should be possibly started using a single service file, such as: 

```
fleetctl start --num 2 hello.service
```

Note: discussed in #302

**Comment by gdoteof** [comment]
The example above hangs for me as well.  bash expansion appears to be working

`core@ztest01 ~ $ cat hello\@.service`
```
[Service]
ExecStartPre=/bin/echo "hello world from %n"
ExecStart=/bin/sleep 600
```

`core@ztest01 ~ $ fleetctl --version`
```
fleetctl version 0.9.0
```

`core@ztest01 ~ $ fleetctl start hello@{1..3}.service`

```
^C       #hangs here till ctrl-c
```

`core@ztest01 ~ $ echo {1..3} `
```    
1 2 3
```
`core@ztest01 ~ $ fleetctl start hello@4.service`
```
# hangs here as well
```
