### ISSUE TITLE
fleetctl using wildcards can be dangerous

### ISSUE THREAD

**Issue by developerinlondon** [coreos/fleet#710]
currently using wildcards with `fleetctl destroy x` picks up the filenames from the current directory instead of whats shown in `fleetctl list-units`

this can be dangerous as the current directory does not necessarily reflect whats in list-units. 

the correct behaviour might be to use the wildcards for units that are already there or not accept wildcards at all.

**Comment by wuqixuan** [comment]
@bcwaldon , I checked the code, in main() function, os.Exit(cmd.Run(cmd.Flags.Args())),  cmd.Flags.Args()  function call will find the file using wildcards in current directory.  I think should not give the array of units to cmd.Run. Need search from etcd/http client , then pass it to cmd.Run. 
What do you think? Should we modify it ?

**Comment by wuqixuan** [comment]
@bcwaldon , If need modify as what I suggest, I can help to implement.

**Comment by wuqixuan** [comment]
@bcwaldon @jonboulle , I have given the patch. Do you have any comment ?

**Comment by jonboulle** [comment]
Let's try shepherd this change in for v0.13.0

**Comment by antrik** [comment]
This is not entirely clear: but it seems like @developerinlondon assumed the undesired file globbing was performed by fleetctl itself (hello Windows...) -- whereas it's in fact performed by the shell. As such, I guess this bug qualifies as invalid.

The linked PR on the other hand proposes adding globbing of units within fleetctl -- which is an entirely new feature; and is only marginally related to the actual problem at hand IMHO... Having said that, it sounds fairly useful on it's own -- but it needs quite some work. (See my comment over there.)

**Comment by jonboulle** [comment]
@antrik I agree with your assessment. Let's continue in #1256.
