### ISSUE TITLE
idempotency of commands is confusing

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#745]
Commands like `submit`, `start`, `stop`, `unload` are actually idempotent, so running `fleetctl unload` against a unit that already has the desired state of `inactive` results in no work being done. This is confusing, as nothing is logged to indicate that no work is being done.

Maybe we should add a `set-desired-state` command that is actually idempotent, while the `submit`, `start`, `stop`, and `unload` commands should actually do work.

**Comment by databus23** [comment]
+1 from me as well.
Its really confusing that you can't start a service that has been stopped somehow outside of fleet with `fleetctl start` while the same time `fleetctl list-units` will show the unit as being *inactive*.

**Comment by pmoust** [comment]
+1 as well

**Comment by wuqixuan** [comment]
@bcwaldon ,+1, i think it's fine to add set-desired-state command, and check for other command.

**Comment by jonboulle** [comment]
I don't think we're going to change the commands, but we definitely plan to make this clearer: #1404
