### ISSUE TITLE
Let's fix presence

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#746]
fleet currently uses TTL'd etcd keys to represent the presence of each machine and the jobs each machine has loaded/launched in the cluster. This is bad for two reasons:
1. etcd downtime longer than the presence TTLs cause loss of presence information, which the engine unnecessarily acts on by rescheduling work
2. fleet should not store ephemeral data in etcd - this causes unnecessary load on etcd, and on the developers to support old data formats

To fix this, we switch to a model where only persistent data is stored in etcd:
1. static machine configuration (i.e. /machines without a TTL)
2. job & unit models
3. schedule

And we gather the ephemeral state through HTTP APIs hosted on each fleet node.

**Comment by jonboulle** [comment]
Assigning this as a maybe for v1 as this may be solved via Giant Swarm's patch set.

**Comment by jonboulle** [comment]
#1426 essentially fixes this

**Comment by jonboulle** [comment]
Actually just going to close this in favour of that.
