### ISSUE TITLE
Redeploy unit in place

### ISSUE THREAD

**Issue by jcderr** [coreos/fleet#760]
It would be quite nice to be able to replace an existing unit in one go, if a change must be made, preserving its location.

* `fleetctl submit some.unit.service`
* `fleetctl run some.unit.service`
* _edit some.unit.service_
* `fleetctl reload some.unit.service`

Fleet should replace the unit conf in-place, stop the running unit, and restart it using the new conf.

**Comment by bcwaldon** [comment]
This should be easy to do now. We could accept a new unit file using something like `fleetctl --overwrite start foo.service`, which would trigger the reconciler on a given machine to tear down the existing unit based on a hash mismatch.

**Comment by ernado** [comment]
:+1:

**Comment by Vish0007** [comment]
which fleet version has the --overwrite option?

**Comment by Vish0007** [comment]
Hi Brian,

Is this fix available now?

**Comment by bcwaldon** [comment]
@Vish0007 no code has been written to support this

**Comment by klausenbusk** [comment]
+1

**Comment by jotsif** [comment]
+1

**Comment by lukebarton** [comment]
+1

**Comment by ghaering** [comment]
+1

**Comment by thuey** [comment]
+1

**Comment by NeMO84** [comment]
+1

**Comment by pcross616** [comment]
+1

**Comment by maticmeznar** [comment]
+1 @bcwaldon Whats the ETA for this?

**Comment by cookandy** [comment]
+1

**Comment by tylerFowler** [comment]
+1

**Comment by h0tbird** [comment]
+1 And what about a rolling update of `Global=true` units?

**Comment by kayrus** [comment]
dup #1295

**Comment by tixxdz** [comment]
Hi new replace functionality is in this new PR #1509 which needs testing... there are many corner cases... if you guys are still on it.

**Comment by antrik** [comment]
@kayrus why have you closed this issue? The PR is not in yet...

**Comment by dradtke** [comment]
Here's a possible workaround for reloading a service across the fleet. Note that this isn't really tested, so it's more theoretical than anything:

```bash
# Get the IP address of each host running <name>.service, then ssh into each one
# and reload it using systemctl.
for ADDR in $(fleetctl list-units --no-legend | grep <name>.service | awk '{ print $2 }' | awk --field-separator '/' '{ print $2 }'); do
  ssh $ADDR systemctl reload <name>.service
done
```

Another approach:

```bash
# Same idea, but using machine id instead of IP address. Not sure if it supports
# the same syntax as bare `ssh` for running a command on the server and exiting.
for MACHINE in $(fleetctl list-units --full --no-legend | grep website.service | awk '{ print $2 }' | awk --field-separator '/' '{ print $1 }'); do
  fleetctl ssh $MACHINE systemctl reload <name>.service
done
```
