### ISSUE TITLE
Menacing fleetd logs

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#888]
Every 5min or so, something like this will appear in the fleetd logs:

```
Sep 09 16:47:33 core-01 fleetd[1375]: INFO client.go:278: Failed getting response from http://localhost:4001/: unexpected EOF
Sep 09 16:47:33 core-01 fleetd[1375]: ERROR client.go:200: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
```

This is due to etcd closing all watcher connections ever 5min. It would be great to handle this error gracefully and not log, as this is a total red herring when debugging real issues.

**Comment by radeksimko** [comment]
:+1:

**Comment by dongsupark** [comment]
I tried to find out places where such error messages are printed out, but couldn't find any. Probably it has been already gone.
So I'm closing it.
