### ISSUE TITLE
Question: recommendations for stateful containers in CoreOS?

### ISSUE THREAD

**Issue by jokeyrhyme** [coreos/fleet#892]
CoreOS seems like the obvious choice for stateless services running in containers across a cluster: e.g. web servers, simple cron tasks, etc. It's very easy to set these up with fleet and rest easy knowing that they'll be spawned elsewhere if the machine fails beneath them.

However, I've been having issues wrapping my brain around the concept of stateful containers: e.g. databases, logging, etc.

Is anyone running a production MongoDB or MySQL as containers across multiple CoreOS nodes? It would seem that the easiest thing to do in these cases is to just allow the database software to handle data replication, but there are stateful applications where this isn't always available (and doing this at the database-layer might be less efficient in any case).

Is it in scope for fleet (or perhaps another part of CoreOS) to seamlessly migrate data volumes across when a container is moved between nodes?

Does it make sense for CoreOS to integrate something like Flocker? https://clusterhq.com/blog/data-focused-docker-clustering/?

**Comment by MichielDeMey** [comment]
Would it be fair to say that Amazon's Elastic File System (http://aws.amazon.com/efs/) offers an interesting solution to this problem?

**Comment by jokeyrhyme** [comment]
@MichielDeMey yeah, I can't wait until it's generally available in every region. AWS EFS looks like it takes some of the pain out of this. However, it's not a database clustering solution, it's a distributed file-system. If your database has it's own clustering mechanism, that will still probably be safer and more optimal than relying on the file-system to do it.

**Comment by MichielDeMey** [comment]
Agreed. I was actually only thinking about the filesystem part since that's more difficult to set up than a clustered database environment.

**Comment by FractalizeR** [comment]
@MichielDeMey They offer a filesystem solution only. This is still not a HA database cluster.

**Comment by lukemarsden** [comment]
Flocker now works on CoreOS, using shared block storage e.g. Amazon EBS as a backend. We support many other shared storage backends too. See https://clusterhq.com/2015/09/01/flocker-runs-on-coreos/
