### ISSUE TITLE
How to update unit? (question related to fleetctl)

### ISSUE THREAD

**Issue by ernado** [coreos/fleet#914]
For example, when I run
```bash
~/fleet$ fleetctl submit stun.service 
WARNING: Unit stun.service in registry differs from local unit file stun.servic
```
I expect that unit will be updated, but it stays the same version.

Currently I reached the desired effect with
```bash
ernado@node:~/fleet$ fleetctl destroy stun.service 
Destroyed stun.service
ernado@node:~/fleet$ fleetctl submit stun.service
ernado@node:~/fleet$ fleetctl start stun.service 
Unit stun.service launched on xxxxx.../xx.xx.xx.xx
```

**Comment by bcwaldon** [comment]
See #760

**Comment by celevra** [comment]
what if i want to update the unit file but don't want to restart the service? Could be there are dependencies and i only want to update the unit file for the next reboot
