### ISSUE TITLE
MachineID cannot be used with Conflicts

### ISSUE THREAD

**Issue by sheldonh** [coreos/fleet#934]
Since the fleet 0.8.2 upgrade, my manual fail-over strategy doesn't work because of

```
Error creating units: MachineID cannot be used with Conflicts
```

Why was this use case desupported?

**Comment by JarenGlover** [comment]
@bcwaldon - what is the best way to tie a nginx container (reverse proxy) to a particular node? i.e. I want this container to always load up on this machine (which has an IP that I know - DNS purposes) ...
