### ISSUE TITLE
Fleet start hangs on invalid/unfulfillable conditions

### ISSUE THREAD

**Issue by gucki** [coreos/fleet#964]
I just put a machine ID contraint which could not be satisfied (machine does not exist or is dead). Then `fleetctl start test.service` just hangs forever. After a few seconds it starts outputting

    core@core-02 ~ $ fleetctl start test.service
    2014/10/06 12:47:18 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: too many redirects
    2014/10/06 12:47:18 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/job/test.service}, retrying in 100ms

test.service

    [Unit]
    Description=MyApp
    After=docker.service
    Requires=docker.service

    [Service]
    TimeoutStartSec=0
    ExecStartPre=-/usr/bin/docker kill busybox1
    ExecStartPre=-/usr/bin/docker rm busybox1
    ExecStartPre=/usr/bin/docker pull busybox
    ExecStart=/usr/bin/docker run --name busybox1 busybox /bin/sh -c "while true; do echo Hello World; sleep 1; done"
    ExecStop=/usr/bin/docker stop busybox1

    [X-Fleet]
    MachineID=01234567890

Also etcd and fleetd consume a lot of cpu (100% of one core?) till the failing job is destroyed.

**Comment by bcwaldon** [comment]
Seems like we don't have any more to debug here.
