### ISSUE TITLE
Clarify failure to SSH to remote hosts

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#995]
If I don't have an SSH agent running and I call `fleetctl journal`, I see the following output:

```
cluster-1413996494-01 ~ # fleetctl journal -f app-populate.service
Error running remote command: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running. See https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md for help.
```

The first thing this error message should say is "unable to SSH to remote host" to make it easier to understand. The same thing goes for any command that attempts to SSH around the cluster.

**Comment by ianbytchek** [comment]
:+1:

**Comment by sheerun** [comment]
Yes, please
